DROP INDEX IF EXISTS idx_coaching_recording_renderer_capabilities_expiry;
DROP TABLE IF EXISTS coaching_recording_renderer_capabilities;
DROP INDEX IF EXISTS idx_coaching_booking_participant_state_fresh;
DROP TABLE IF EXISTS coaching_recording_attempt_files;
DROP TABLE IF EXISTS coaching_booking_participant_state;
DROP INDEX IF EXISTS idx_coaching_recording_attempt_imports_pending;
DROP TABLE IF EXISTS coaching_recording_attempt_imports;
DROP INDEX IF EXISTS idx_coaching_recording_attempts_reconcile;
DROP INDEX IF EXISTS idx_coaching_recording_attempts_one_active;
DROP TABLE IF EXISTS coaching_recording_attempts;
DROP TABLE IF EXISTS coaching_recording_collections;
DROP INDEX IF EXISTS idx_videos_asset_sort_order;
ALTER TABLE videos DROP COLUMN IF EXISTS sort_order;
DROP TYPE IF EXISTS coaching_recording_attempt_import_status;
DROP TYPE IF EXISTS coaching_recording_collection_status;
