/**
 * GENERATED by scripts/sync-tokens.mjs from web/dashboard-next/src/styles.scss
 * — do not edit by hand; run `pnpm run sync:tokens`.
 *
 * Zeta design tokens as raw values, for the places NativeWind classes cannot
 * reach: icon `color` props, navigator options, placeholderTextColor.
 * Mobile uses the Material-3 tonal "ember orange" palette, which diverges from
 * the flat web token values; see scripts/sync-tokens.mjs.
 */
export const colors = {
  bg: '#fff8f4',
  surface: '#fdf1ea',
  surfaceWarm: '#faece2',
  surfaceMuted: '#f5e6db',
  text: '#221a15',
  muted: '#54443b',
  primary: '#bd4309',
  primaryStrong: '#bd4309',
  primarySoft: '#ffdbc8',
  accent: '#f59e0b',
  border: '#d8c3b6',
  success: '#15803d',
  successSoft: '#c7f1d2',
  warning: '#b45309',
  warningSoft: '#fef3c7',
  danger: '#be123c',
  dangerSoft: '#ffe4e6',
  /** Mobile-only: icon/text on primary-colored surfaces (e.g. the FAB). */
  onPrimary: '#ffffff',
} as const;
