/**
 * GENERATED by scripts/sync-tokens.mjs from web/dashboard-next/src/styles.scss
 * — do not edit by hand; run `pnpm run sync:tokens`.
 *
 * Semantic role tokens for light and dark mode.
 * Light roles are derived from the flat web design tokens.
 * Dark roles use warm-neutral dark surfaces to preserve brand warmth;
 * see the derivation rationale in scripts/sync-tokens.mjs.
 *
 * Usage:
 *   - NativeWind: bg-accent / text-on-surface / bg-surface-variant etc.
 *   - Native tier: import { roles } from './roles' for icon color props etc.
 */
export const roles = {
  light: {
    accent: '#ea580c',
    onAccent: '#ffffff',
    accentContainer: '#fed7aa',
    onAccentContainer: '#c2410c',
    success: '#15803d',
    onSuccess: '#ffffff',
    successContainer: '#dcfce7',
    onSuccessContainer: '#15803d',
    warning: '#b45309',
    onWarning: '#ffffff',
    warningContainer: '#fef3c7',
    onWarningContainer: '#b45309',
    danger: '#be123c',
    onDanger: '#ffffff',
    dangerContainer: '#ffe4e6',
    onDangerContainer: '#be123c',
    background: '#fff8ed',
    surface: '#ffffff',
    surfaceVariant: '#fff1dc',
    onSurface: '#26180f',
    onSurfaceVariant: '#735f4d',
    outline: '#ead2b8',
  },
  dark: {
    accent: '#fb923c',
    onAccent: '#ffffff',
    accentContainer: '#7c2d0a',
    onAccentContainer: '#fed7aa',
    success: '#4ade80',
    onSuccess: '#052e16',
    successContainer: '#14532d',
    onSuccessContainer: '#86efac',
    warning: '#fbbf24',
    onWarning: '#451a03',
    warningContainer: '#3b1500',
    onWarningContainer: '#fde68a',
    danger: '#fb7185',
    onDanger: '#4c0519',
    dangerContainer: '#500724',
    onDangerContainer: '#fda4af',
    background: '#1a0f08',
    surface: '#231409',
    surfaceVariant: '#2e1b0e',
    onSurface: '#f5e6d3',
    onSurfaceVariant: '#a8917c',
    outline: '#4a3020',
  },
} as const;
