/**
 * GENERATED by scripts/sync-tokens.mjs from web/dashboard-next/src/styles.scss
 * — do not edit by hand; run `pnpm run sync:tokens`.
 *
 * Semantic role tokens for light and dark mode — Mobile Material-3 tonal
 * palette ("ember orange"). Mobile diverges from the flat web tokens to the
 * Material-You tonal scheme (darker tonal primary + warm-tinted surfaces);
 * web styles.scss is untouched. Dark roles use Material orange-dark surfaces;
 * see the values and rationale in scripts/sync-tokens.mjs.
 *
 * Usage:
 *   - NativeWind: bg-accent / text-on-surface / bg-surface-variant etc.
 *   - Native tier: import { roles } from './roles' for icon color props etc.
 */
export const roles = {
  light: {
    accent: '#bd4309',
    onAccent: '#ffffff',
    accentContainer: '#ffdbc8',
    onAccentContainer: '#3a1400',
    accentStrong: '#bd4309',
    secondaryContainer: '#ffdcc4',
    onSecondaryContainer: '#5a3214',
    success: '#15803d',
    onSuccess: '#ffffff',
    successContainer: '#c7f1d2',
    onSuccessContainer: '#05351a',
    warning: '#b45309',
    onWarning: '#ffffff',
    warningContainer: '#fef3c7',
    onWarningContainer: '#b45309',
    danger: '#be123c',
    onDanger: '#ffffff',
    dangerContainer: '#ffe4e6',
    onDangerContainer: '#be123c',
    background: '#fff8f4',
    surface: '#fdf1ea',
    surfaceVariant: '#faece2',
    onSurface: '#221a15',
    onSurfaceVariant: '#54443b',
    outline: '#d8c3b6',
    outlineStrong: '#897668',
  },
  dark: {
    accent: '#ffb68f',
    onAccent: '#ffffff',
    accentContainer: '#7c3500',
    onAccentContainer: '#ffdbc8',
    accentStrong: '#bd4309',
    secondaryContainer: '#5d4030',
    onSecondaryContainer: '#ffdcc4',
    success: '#7fd99a',
    onSuccess: '#052e16',
    successContainer: '#1f4a30',
    onSuccessContainer: '#c7f1d2',
    warning: '#fbbf24',
    onWarning: '#451a03',
    warningContainer: '#3b1500',
    onWarningContainer: '#fde68a',
    danger: '#fb7185',
    onDanger: '#4c0519',
    dangerContainer: '#500724',
    onDangerContainer: '#fda4af',
    background: '#18120d',
    surface: '#1f160f',
    surfaceVariant: '#261c14',
    onSurface: '#f2dfd2',
    onSurfaceVariant: '#d8c3b6',
    outline: '#54443b',
    outlineStrong: '#a18d80',
  },
} as const;
