// Code generated by MockGen. DO NOT EDIT.
// Source: workos.go
//
// Generated by this command:
//
//	mockgen -source=workos.go -destination=mocks/mock_workos.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"

	usermanagement "github.com/workos/workos-go/v4/pkg/usermanagement"
	gomock "go.uber.org/mock/gomock"
)

// MockUserManagement is a mock of UserManagement interface.
type MockUserManagement struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementMockRecorder
	isgomock struct{}
}

// MockUserManagementMockRecorder is the mock recorder for MockUserManagement.
type MockUserManagementMockRecorder struct {
	mock *MockUserManagement
}

// NewMockUserManagement creates a new mock instance.
func NewMockUserManagement(ctrl *gomock.Controller) *MockUserManagement {
	mock := &MockUserManagement{ctrl: ctrl}
	mock.recorder = &MockUserManagementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagement) EXPECT() *MockUserManagementMockRecorder {
	return m.recorder
}

// AuthenticateWithCode mocks base method.
func (m *MockUserManagement) AuthenticateWithCode(ctx context.Context, opts usermanagement.AuthenticateWithCodeOpts) (usermanagement.AuthenticateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateWithCode", ctx, opts)
	ret0, _ := ret[0].(usermanagement.AuthenticateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateWithCode indicates an expected call of AuthenticateWithCode.
func (mr *MockUserManagementMockRecorder) AuthenticateWithCode(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateWithCode", reflect.TypeOf((*MockUserManagement)(nil).AuthenticateWithCode), ctx, opts)
}

// AuthenticateWithPassword mocks base method.
func (m *MockUserManagement) AuthenticateWithPassword(ctx context.Context, opts usermanagement.AuthenticateWithPasswordOpts) (usermanagement.AuthenticateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateWithPassword", ctx, opts)
	ret0, _ := ret[0].(usermanagement.AuthenticateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateWithPassword indicates an expected call of AuthenticateWithPassword.
func (mr *MockUserManagementMockRecorder) AuthenticateWithPassword(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateWithPassword", reflect.TypeOf((*MockUserManagement)(nil).AuthenticateWithPassword), ctx, opts)
}

// AuthenticateWithRefreshToken mocks base method.
func (m *MockUserManagement) AuthenticateWithRefreshToken(ctx context.Context, opts usermanagement.AuthenticateWithRefreshTokenOpts) (usermanagement.RefreshAuthenticationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateWithRefreshToken", ctx, opts)
	ret0, _ := ret[0].(usermanagement.RefreshAuthenticationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateWithRefreshToken indicates an expected call of AuthenticateWithRefreshToken.
func (mr *MockUserManagementMockRecorder) AuthenticateWithRefreshToken(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateWithRefreshToken", reflect.TypeOf((*MockUserManagement)(nil).AuthenticateWithRefreshToken), ctx, opts)
}

// CreateOrganizationMembership mocks base method.
func (m *MockUserManagement) CreateOrganizationMembership(ctx context.Context, opts usermanagement.CreateOrganizationMembershipOpts) (usermanagement.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganizationMembership", ctx, opts)
	ret0, _ := ret[0].(usermanagement.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationMembership indicates an expected call of CreateOrganizationMembership.
func (mr *MockUserManagementMockRecorder) CreateOrganizationMembership(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationMembership", reflect.TypeOf((*MockUserManagement)(nil).CreateOrganizationMembership), ctx, opts)
}

// GetAuthorizationURL mocks base method.
func (m *MockUserManagement) GetAuthorizationURL(opts usermanagement.GetAuthorizationURLOpts) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", opts)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockUserManagementMockRecorder) GetAuthorizationURL(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockUserManagement)(nil).GetAuthorizationURL), opts)
}

// GetLogoutURL mocks base method.
func (m *MockUserManagement) GetLogoutURL(opts usermanagement.GetLogoutURLOpts) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogoutURL", opts)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogoutURL indicates an expected call of GetLogoutURL.
func (mr *MockUserManagementMockRecorder) GetLogoutURL(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogoutURL", reflect.TypeOf((*MockUserManagement)(nil).GetLogoutURL), opts)
}

// GetUser mocks base method.
func (m *MockUserManagement) GetUser(ctx context.Context, opts usermanagement.GetUserOpts) (usermanagement.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, opts)
	ret0, _ := ret[0].(usermanagement.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserManagementMockRecorder) GetUser(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserManagement)(nil).GetUser), ctx, opts)
}

// ListOrganizationMemberships mocks base method.
func (m *MockUserManagement) ListOrganizationMemberships(ctx context.Context, opts usermanagement.ListOrganizationMembershipsOpts) (usermanagement.ListOrganizationMembershipsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationMemberships", ctx, opts)
	ret0, _ := ret[0].(usermanagement.ListOrganizationMembershipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMemberships indicates an expected call of ListOrganizationMemberships.
func (mr *MockUserManagementMockRecorder) ListOrganizationMemberships(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMemberships", reflect.TypeOf((*MockUserManagement)(nil).ListOrganizationMemberships), ctx, opts)
}

// UpdateUser mocks base method.
func (m *MockUserManagement) UpdateUser(ctx context.Context, opts usermanagement.UpdateUserOpts) (usermanagement.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, opts)
	ret0, _ := ret[0].(usermanagement.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserManagementMockRecorder) UpdateUser(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserManagement)(nil).UpdateUser), ctx, opts)
}
