// Code generated by MockGen. DO NOT EDIT.
// Source: internal/assets/mux.go
//
// Generated by this command:
//
//	mockgen -source=internal/assets/mux.go -destination=internal/assets/mocks/mock_mux.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	mux_go "github.com/muxinc/mux-go"
	gomock "go.uber.org/mock/gomock"
)

// MockMuxClient is a mock of MuxClient interface.
type MockMuxClient struct {
	ctrl     *gomock.Controller
	recorder *MockMuxClientMockRecorder
	isgomock struct{}
}

// MockMuxClientMockRecorder is the mock recorder for MockMuxClient.
type MockMuxClientMockRecorder struct {
	mock *MockMuxClient
}

// NewMockMuxClient creates a new mock instance.
func NewMockMuxClient(ctrl *gomock.Controller) *MockMuxClient {
	mock := &MockMuxClient{ctrl: ctrl}
	mock.recorder = &MockMuxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxClient) EXPECT() *MockMuxClientMockRecorder {
	return m.recorder
}

// CreateDirectUpload mocks base method.
func (m *MockMuxClient) CreateDirectUpload(req mux_go.CreateUploadRequest) (mux_go.UploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDirectUpload", req)
	ret0, _ := ret[0].(mux_go.UploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDirectUpload indicates an expected call of CreateDirectUpload.
func (mr *MockMuxClientMockRecorder) CreateDirectUpload(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirectUpload", reflect.TypeOf((*MockMuxClient)(nil).CreateDirectUpload), req)
}

// GetAsset mocks base method.
func (m *MockMuxClient) GetAsset(assetID string) (mux_go.AssetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", assetID)
	ret0, _ := ret[0].(mux_go.AssetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockMuxClientMockRecorder) GetAsset(assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockMuxClient)(nil).GetAsset), assetID)
}

// GetDirectUpload mocks base method.
func (m *MockMuxClient) GetDirectUpload(uploadID string) (mux_go.UploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectUpload", uploadID)
	ret0, _ := ret[0].(mux_go.UploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectUpload indicates an expected call of GetDirectUpload.
func (mr *MockMuxClientMockRecorder) GetDirectUpload(uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectUpload", reflect.TypeOf((*MockMuxClient)(nil).GetDirectUpload), uploadID)
}
