/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange an AuthKit authorization code (PKCE) for a token pair */
        post: operations["exchangeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a token pair using a refresh token
         * @description WorkOS invalidates the presented refresh token. Clients must always replace their stored pair with the returned one.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile, role, permissions, and preferences */
        get: operations["getMe"];
        /** Update profile and notification preferences */
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets visible to the current user */
        get: operations["listAssets"];
        put?: never;
        /** Create a new asset and get upload URLs for each video file */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single visible asset including its video parts */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all video parts as uploaded and transition the asset to pending review */
        post: operations["completeAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups the current user belongs to */
        get: operations["listGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session and get the WorkOS logout URL */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        LogoutResponse: {
            logoutUrl: string;
        };
        TokenExchangeRequest: {
            /** @description Authorization code from the AuthKit redirect */
            code: string;
            /** @description PKCE code verifier matching the code_challenge sent to AuthKit. Required for the mobile PKCE flow; omitted only when a confidential client exchanges a code without PKCE. */
            code_verifier?: string;
        };
        TokenRefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
        };
        EmailPreferences: {
            notifications_enabled: boolean;
            asset_uploads_enabled: boolean;
            asset_reviews_enabled: boolean;
            invitation_updates_enabled: boolean;
            group_membership_updates_enabled: boolean;
            coaching_booking_updates_enabled: boolean;
            coaching_reminders_enabled: boolean;
        };
        Me: {
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            /** @enum {string} */
            language: "en" | "de" | "fr";
            /** @description Base64-encoded avatar image, empty when unset */
            avatar: string;
            timezone: string;
            email_preferences: components["schemas"]["EmailPreferences"];
            role: string;
            permissions: string[];
        };
        UpdateMeRequest: {
            first_name?: string;
            last_name?: string;
            /** @enum {string} */
            language?: "en" | "de" | "fr";
            /** @description Base64-encoded avatar image; omit to keep the current one */
            avatar?: string;
            timezone: string;
            email_preferences?: components["schemas"]["EmailPreferences"];
        };
        AssetGroup: {
            id: string;
            name: string;
            /** @description Base64-encoded group avatar; omitted when unset */
            avatar?: string;
        };
        AssetVideo: {
            id: string;
            /** @description Mux public playback ID; empty while the upload is processing */
            playback_id: string;
            status: string;
            /** Format: int64 */
            review_count: number;
        };
        /** @description Parent reviewable submission (UI copy calls it a video). List responses omit videos and group; the detail response includes them. */
        Asset: {
            id: string;
            title: string;
            description: string;
            owner_id: string;
            /** @enum {string} */
            status: "waiting_upload" | "pending" | "completed";
            /** @description Mux thumbnail URL; omitted while no playback ID exists */
            thumbnail?: string;
            playback_id?: string;
            /** Format: int64 */
            review_count: number;
            videos?: components["schemas"]["AssetVideo"][];
            group?: components["schemas"]["AssetGroup"];
        };
        CreateAssetRequest: {
            title: string;
            description: string;
            filenames: string[];
            /** Format: uuid */
            group_id: string;
        };
        CreateAssetVideo: {
            id: string;
            /** @description Mux direct-upload URL; PUT the file binary here */
            upload_url: string;
            filename: string;
        };
        CreateAssetResponse: {
            asset_id: string;
            videos: components["schemas"]["CreateAssetVideo"][];
        };
        Group: {
            id: string;
            name: string;
            owner_id: string;
            /** @description Base64-encoded group avatar */
            avatar: string | null;
            description: string;
            created_at: string;
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    exchangeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Token pair for the authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Missing code or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WorkOS rejected the authorization code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Missing refresh_token or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token expired or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Invalid or missing timezone, invalid body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible assets (students see their own, experts their groups') */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset created with Mux upload URLs for each video file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAssetResponse"];
                };
            };
            /** @description Missing title or group_id, invalid body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing assets:create permission or not a group member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset with its videos and group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Invalid asset id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload marked as complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Invalid asset id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups the authenticated user is a member of */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout URL to open for session termination at WorkOS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
}
