/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange an AuthKit authorization code (PKCE) for a token pair */
        post: operations["exchangeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a token pair using a refresh token
         * @description WorkOS invalidates the presented refresh token. Clients must always replace their stored pair with the returned one.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile, role, permissions, and preferences */
        get: operations["getMe"];
        /** Update profile and notification preferences */
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets visible to the current user */
        get: operations["listAssets"];
        put?: never;
        /** Create a new asset and get upload URLs for each video file */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single visible asset including its video parts */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all video parts as uploaded and transition the asset to pending review */
        post: operations["completeAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark the video as reviewed (finalize)
         * @description Transitions the asset to completed. Requires assets:finalize and that every video part already has at least one review (400 otherwise).
         */
        post: operations["finalizeAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups the current user belongs to */
        get: operations["listGroups"];
        put?: never;
        /** Create a group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single group by ID */
        get: operations["getGroup"];
        /** Update group preferences (name, description, avatar) */
        put: operations["updateGroup"];
        post?: never;
        /** Delete a group (owner only) */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave a group */
        delete: operations["leaveGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List student members of a group */
        get: operations["listGroupStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/experts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List expert members of a group */
        get: operations["listGroupExperts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/users/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a group */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a group invitation (link/QR, optionally emailed) */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/invitations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invitation info by code */
        get: operations["getInvitationInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a group invitation */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/invitations/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline a group invitation */
        post: operations["declineInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/videos/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a video */
        get: operations["listVideoReviews"];
        put?: never;
        /** Create a review on a video */
        post: operations["createVideoReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/videos/{id}/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a review on a video */
        put: operations["updateVideoReview"];
        post?: never;
        /** Delete a review on a video */
        delete: operations["deleteVideoReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewrite review text with the AI enhancer */
        post: operations["enhanceReviewText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session and get the WorkOS logout URL */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coaching/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all bookings for the current user across all groups
         * @description Returns every booking where the caller is either the student or the expert, regardless of group. Requires the coaching:bookings:read permission.
         */
        get: operations["listMyBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/session-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List coaching session types for a group
         * @description Experts with coaching:availability:manage see only their own session types. Users with coaching:slots:read see all active types in the group. Returns 403 if the caller has neither permission.
         */
        get: operations["listGroupSessionTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/experts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List coaching experts in a group
         * @description Returns the active experts for the given group. Requires group membership and coaching:slots:read.
         */
        get: operations["listCoachingExperts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available booking slots for an expert
         * @description Computes open time slots for the given expert and session type over the next 28 days, excluding blocked slots, existing bookings, and times that fall within the minimum booking notice window. Both expert_id and session_type_id are required.
         */
        get: operations["listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book a coaching session
         * @description Creates a booking for the authenticated user with the specified expert, session type, and scheduled time. The slot is checked for conflicts inside a serializable transaction. Requires group membership and coaching:book.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/bookings/{bookingID}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate an Agora RTC token for a coaching session
         * @description Returns the Agora app ID, channel name, a short-lived RTC token, and a participant UID for the authenticated user. The caller must hold the coaching:video:connect permission and be a participant (student or expert) of the booking. The connect window opens 15 minutes before the scheduled start time and closes at the session end (scheduled_at + duration_minutes). If recording is enabled and has not yet been started, this call also triggers recording — a recording start failure returns 500 (the token is NOT issued in that case).
         */
        get: operations["connectToBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/bookings/{bookingID}/recording/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop the cloud recording for a coaching booking
         * @description Stops the Agora Cloud Recording for the given booking. The caller must hold the coaching:video:connect permission and be a participant of the booking. If recording is disabled or there is no active recording to stop, the call succeeds silently (idempotent). Returns 200 with a status confirmation body on success.
         */
        post: operations["stopBookingRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/coaching/bookings/{bookingID}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cancel a coaching booking
         * @description Cancels a booking. The caller must be a participant (either the student or the expert) — this is enforced inside the handler without a permission middleware. Returns 404 if the booking does not exist or the caller is not a participant. Cancellations must be made at least the configured cancellation-notice period before the session.
         */
        put: operations["cancelBooking"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a device for push notifications
         * @description Registers (or updates) the calling user's device with an Expo push token. If the token is already registered to this user, the record is refreshed (last_seen_at updated). Requires a valid bearer token.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unregister a device push token
         * @description Removes the push token from the calling user's device list. Silently succeeds when the token is not found (idempotent). Requires a valid bearer token.
         */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        LogoutResponse: {
            logoutUrl: string;
        };
        TokenExchangeRequest: {
            /** @description Authorization code from the AuthKit redirect */
            code: string;
            /** @description PKCE code verifier matching the code_challenge sent to AuthKit. Required for the mobile PKCE flow; omitted only when a confidential client exchanges a code without PKCE. */
            code_verifier?: string;
        };
        TokenRefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
        };
        EmailPreferences: {
            notifications_enabled: boolean;
            asset_uploads_enabled: boolean;
            asset_reviews_enabled: boolean;
            invitation_updates_enabled: boolean;
            group_membership_updates_enabled: boolean;
            coaching_booking_updates_enabled: boolean;
            coaching_reminders_enabled: boolean;
        };
        /** @description Push notification preferences. Mirrors EmailPreferences but omits coaching_reminders (push reminders are out of scope). */
        PushPreferences: {
            notifications_enabled: boolean;
            asset_uploads_enabled: boolean;
            asset_reviews_enabled: boolean;
            invitation_updates_enabled: boolean;
            group_membership_updates_enabled: boolean;
            coaching_booking_updates_enabled: boolean;
        };
        RegisterDeviceRequest: {
            /** @description Expo push notification token from the device */
            expo_push_token: string;
            /** @description Device platform (e.g. ios, android); omit when unknown */
            platform?: string;
        };
        Me: {
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            /** @enum {string} */
            language: "en" | "de" | "fr";
            /** @description Base64-encoded avatar image, empty when unset */
            avatar: string;
            timezone: string;
            email_preferences: components["schemas"]["EmailPreferences"];
            push_preferences: components["schemas"]["PushPreferences"];
            role: string;
            permissions: string[];
        };
        UpdateMeRequest: {
            first_name?: string;
            last_name?: string;
            /** @enum {string} */
            language?: "en" | "de" | "fr";
            /** @description Base64-encoded avatar image; omit to keep the current one */
            avatar?: string;
            timezone: string;
            email_preferences?: components["schemas"]["EmailPreferences"];
            push_preferences?: components["schemas"]["PushPreferences"];
        };
        AssetGroup: {
            id: string;
            name: string;
            /** @description Base64-encoded group avatar; omitted when unset */
            avatar?: string;
        };
        AssetVideo: {
            id: string;
            /** @description Mux public playback ID; empty while the upload is processing */
            playback_id: string;
            status: string;
            /** Format: int64 */
            review_count: number;
        };
        /** @description Parent reviewable submission (UI copy calls it a video). List responses omit videos and group; the detail response includes them. */
        Asset: {
            id: string;
            title: string;
            description: string;
            owner_id: string;
            /** @enum {string} */
            status: "waiting_upload" | "pending" | "completed";
            /** @description Mux thumbnail URL; omitted while no playback ID exists */
            thumbnail?: string;
            playback_id?: string;
            /** Format: int64 */
            review_count: number;
            videos?: components["schemas"]["AssetVideo"][];
            group?: components["schemas"]["AssetGroup"];
        };
        CreateAssetRequest: {
            title: string;
            description: string;
            filenames: string[];
            /** Format: uuid */
            group_id: string;
        };
        CreateAssetVideo: {
            id: string;
            /** @description Mux direct-upload URL; PUT the file binary here */
            upload_url: string;
            filename: string;
        };
        CreateAssetResponse: {
            asset_id: string;
            videos: components["schemas"]["CreateAssetVideo"][];
        };
        Group: {
            id: string;
            name: string;
            owner_id: string;
            /** @description Base64-encoded group avatar */
            avatar: string | null;
            description: string;
            created_at: string;
            updated_at: string;
        };
        ReviewAuthor: {
            name: string;
            /** @description Base64-encoded avatar; omitted when unset */
            avatar?: string;
        };
        Review: {
            id: string;
            content: string;
            /**
             * Format: int32
             * @description Player position the comment refers to; omitted for untimed comments
             */
            timestamp_seconds?: number;
            /** @description Present on replies */
            parent_id?: string;
            author?: components["schemas"]["ReviewAuthor"];
            /** Format: date-time */
            created_at: string;
        };
        CreateReviewRequest: {
            content: string;
            /** Format: int32 */
            timestamp_seconds?: number;
            parent_id?: string;
        };
        UpdateReviewRequest: {
            content: string;
        };
        UpdateReviewResponse: {
            id: string;
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        EnhanceTextRequest: {
            text: string;
        };
        EnhanceTextResponse: {
            enhanced_text: string;
        };
        FinalizeAssetResponse: {
            /** @enum {string} */
            status: "completed";
        };
        GroupUser: {
            id: string;
            email: string;
            first_name: string;
            last_name: string;
            /** @description Base64-encoded avatar; omitted when unset */
            avatar?: string;
            role: string;
        };
        GroupUserList: {
            data: components["schemas"]["GroupUser"][];
        };
        InvitationInfo: {
            code: string;
            group_id: string;
            group_name: string;
            /** @description Base64-encoded group avatar; empty string when the group has no avatar set */
            group_avatar: string;
            already_member: boolean;
        };
        AcceptInvitationRequest: {
            code: string;
        };
        AcceptInvitationResponse: {
            group_id: string;
        };
        DeclineInvitationRequest: {
            code: string;
        };
        CreateGroupRequest: {
            name: string;
            description?: string;
            /** @description Base64-encoded image data (max 300KB) */
            avatar: string;
        };
        UpdateGroupRequest: {
            name: string;
            description?: string;
            /** @description Base64-encoded image data (max 300KB); omit or empty to keep the current avatar */
            avatar?: string;
        };
        CreateInvitationRequest: {
            /** @description Optional invitee email; if it maps to a registered user, an email + in-app notification are sent */
            email?: string;
        };
        GroupInvitation: {
            id: string;
            code: string;
        };
        /** @description Recording metadata attached to a completed booking */
        BookingRecording: {
            /** @description Recording pipeline status */
            status: string;
            /**
             * Format: uuid
             * @description Parent asset ID; present once the recording is processed
             */
            asset_id?: string;
            /**
             * Format: uuid
             * @description Video part ID; present once the recording is processed
             */
            video_id?: string;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            expert_id: string;
            expert_name: string;
            student_id: string;
            student_name: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            session_type_id: string;
            /** @description Omitted when not available (e.g. after cancel without a name lookup) */
            session_type_name?: string;
            /** Format: date-time */
            scheduled_at: string;
            /** Format: int32 */
            duration_minutes: number;
            /**
             * @description Derived at response time: cancelled if is_cancelled is set; done if scheduled_at is in the past; otherwise pending.
             * @enum {string}
             */
            status: "pending" | "done" | "cancelled";
            /** @description Provided reason; omitted when not cancelled or no reason given */
            cancellation_reason?: string;
            /** @description User ID of whoever cancelled; omitted when not cancelled */
            cancelled_by?: string;
            /** @description Optional notes from the student; omitted when absent */
            notes?: string;
            recording?: components["schemas"]["BookingRecording"];
            /** Format: date-time */
            created_at: string;
        };
        SessionType: {
            /** Format: uuid */
            id: string;
            expert_id: string;
            /** Format: uuid */
            group_id: string;
            name: string;
            description: string;
            /** Format: int32 */
            duration_minutes: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CoachingSlot: {
            /** @description WorkOS user ID of the expert this slot belongs to */
            expert_id: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: int32 */
            duration_minutes: number;
        };
        CoachingExpert: {
            /** @description WorkOS user ID */
            expert_id: string;
            first_name: string;
            last_name: string;
            /** @description Base64-encoded avatar; omitted when unset */
            avatar?: string;
        };
        CreateBookingRequest: {
            /** @description WorkOS user ID of the expert to book */
            expert_id: string;
            /** Format: uuid */
            session_type_id: string;
            /**
             * Format: date-time
             * @description Desired session start time (RFC3339)
             */
            scheduled_at: string;
            /** @description Optional notes to share with the expert */
            notes?: string;
        };
        CancelBookingRequest: {
            /** @description Optional reason for cancellation */
            cancellation_reason?: string;
        };
        /** @description Agora RTC credentials returned by the connect endpoint */
        BookingConnectInfo: {
            /** @description Agora application ID */
            app_id: string;
            /** @description Agora channel name for this booking session */
            channel: string;
            /** @description Short-lived Agora RTC credential — never log it. Valid for 3600 seconds from issuance. */
            token: string;
            /** @description Participant UID for the Agora channel (uint32). Students always receive UID 1; experts always receive UID 2. */
            uid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    exchangeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Token pair for the authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Missing code or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WorkOS rejected the authorization code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded for this client */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Missing refresh_token or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token expired or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded for this client */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Invalid or missing timezone, invalid body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible assets (students see their own, experts their groups') */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset created with Mux upload URLs for each video file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAssetResponse"];
                };
            };
            /** @description Missing title or group_id, invalid body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing assets:create permission or not a group member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset with its videos and group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Invalid asset id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload marked as complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Invalid asset id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not the asset owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finalizeAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video marked as reviewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeAssetResponse"];
                };
            };
            /** @description Invalid asset id, or a video part has no reviews */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing assets:finalize permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups the authenticated user is a member of */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description The created group (caller is added as the owner/first member) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Invalid body, or missing name/avatar */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:create permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to create the group */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:read permission or caller is not a member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description The updated group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Invalid group ID, invalid body, or missing name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:preferences:edit permission or caller is not a member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to update the group */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:delete permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to delete the group */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    leaveGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully left the group */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid group ID or caller is the group owner */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:membership:leave permission or caller is not a member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot leave the group as the last member */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroupStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student members of the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupUserList"];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:user-list:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroupExperts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expert and admin members of the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupUserList"];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:expert-list:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid group ID, missing user ID, or target is the group owner */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:user-list:delete permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to remove the member */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description The created invitation (carries the shareable code) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInvitation"];
                };
            };
            /** @description Invalid group ID, invalid body, or invalid email address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing groups:invites:create permission or caller is not a member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to create the invitation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInvitationInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation details including group info and membership status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationInfo"];
                };
            };
            /** @description Invitation already used (and caller is not a member) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invitation or group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation accepted (or caller was already a member) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInvitationResponse"];
                };
            };
            /** @description Missing or empty code, or invitation already used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invitation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    declineInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation declined (or generic-link notification dismissed) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or empty code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invitation not found or caller is not the addressed recipient */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVideoReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description video id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews for the video */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Invalid video id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing reviews:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createVideoReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description video id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Review created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Invalid video id, invalid body, missing content, or invalid parent_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing reviews:create permission or video is part of a completed asset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateVideoReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description video id */
                id: string;
                /** @description review id */
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewRequest"];
            };
        };
        responses: {
            /** @description Review updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReviewResponse"];
                };
            };
            /** @description Invalid id, invalid body, or missing content */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing reviews:edit permission, not the author, or video is part of a completed asset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review not found or video not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteVideoReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description video id */
                id: string;
                /** @description review id */
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing reviews:delete permission, not the author, or video is part of a completed asset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review not found or video not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enhanceReviewText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhanceTextRequest"];
            };
        };
        responses: {
            /** @description Enhanced text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhanceTextResponse"];
                };
            };
            /** @description Invalid body or missing text */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing reviews:edit permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Enhancement failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout URL to open for session termination at WorkOS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    listMyBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings across all groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing coaching:bookings:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroupSessionTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session types available in this group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionType"][];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member, or has neither coaching:availability:manage nor coaching:slots:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCoachingExperts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Experts in the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachingExpert"][];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member or missing coaching:slots:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAvailableSlots: {
        parameters: {
            query: {
                /** @description WorkOS user ID of the expert */
                expert_id: string;
                /** @description Session type whose duration governs slot sizing */
                session_type_id: string;
            };
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available slots within the lookahead window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachingSlot"][];
                };
            };
            /** @description Invalid group ID, missing expert_id, missing or invalid session_type_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member or missing coaching:slots:read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session type not found in this group */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Invalid group ID, missing expert_id, invalid session_type_id, invalid scheduled_at (must be RFC3339), or session must be booked further in advance (minimum booking notice not met) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member or missing coaching:book permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session type not found in this group */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Time slot is no longer available (conflict) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connectToBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
                bookingID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agora RTC credentials for the session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingConnectInfo"];
                };
            };
            /** @description Invalid booking ID; booking is cancelled; or the current time is outside the connect window (too early or session has already ended) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member or missing coaching:video:connect permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found or caller is not a participant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to generate the Agora token or start recording */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video calling is not configured on the server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stopBookingRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
                bookingID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording stopped (or was already stopped / not running) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Invalid booking ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member or missing coaching:video:connect permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found or caller is not a participant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to stop the recording */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupID: string;
                bookingID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            /** @description Booking cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Invalid booking ID or cancellation is too close to the session start (cancellation notice period not met) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a group member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found or caller is not a participant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking is already cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Device registered or refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description Missing expo_push_token or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expo push token to remove */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device unregistered (or was already absent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
