// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_enhancer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnhancer is a mock of Enhancer interface.
type MockEnhancer struct {
	ctrl     *gomock.Controller
	recorder *MockEnhancerMockRecorder
	isgomock struct{}
}

// MockEnhancerMockRecorder is the mock recorder for MockEnhancer.
type MockEnhancerMockRecorder struct {
	mock *MockEnhancer
}

// NewMockEnhancer creates a new mock instance.
func NewMockEnhancer(ctrl *gomock.Controller) *MockEnhancer {
	mock := &MockEnhancer{ctrl: ctrl}
	mock.recorder = &MockEnhancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnhancer) EXPECT() *MockEnhancerMockRecorder {
	return m.recorder
}

// EnhanceReviewText mocks base method.
func (m *MockEnhancer) EnhanceReviewText(ctx context.Context, originalText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnhanceReviewText", ctx, originalText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnhanceReviewText indicates an expected call of EnhanceReviewText.
func (mr *MockEnhancerMockRecorder) EnhanceReviewText(ctx, originalText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnhanceReviewText", reflect.TypeOf((*MockEnhancer)(nil).EnhanceReviewText), ctx, originalText)
}
