// Generates the Zeta color tokens for the app from the dashboard stylesheet.
// The dashboard owns the design tokens; run `pnpm run sync:tokens` after
// changing them. Rewrites the marked block in global.css and the whole
// src/theme/colors.ts.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sourcePath = join(here, '..', '..', 'web', 'dashboard-next', 'src', 'styles.scss');
const cssPath = join(here, '..', 'global.css');
const colorsPath = join(here, '..', 'src', 'theme', 'colors.ts');

// Mobile-only tokens with no dashboard counterpart. Keys are camelCase as
// exported from colors.ts.
const MOBILE_EXTRAS = {
  onPrimary: {
    value: '#ffffff',
    comment: 'Mobile-only: icon/text on primary-colored surfaces (e.g. the FAB).',
  },
};

function extractTokens(scss) {
  const root = scss.match(/:root\s*\{([^}]*)\}/);
  if (!root) throw new Error('no :root block found in the dashboard stylesheet');
  const tokens = [...root[1].matchAll(/--z-([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8})\s*;/g)].map(
    ([, name, value]) => [name, value.toLowerCase()],
  );
  if (tokens.length === 0) throw new Error('no --z-* tokens found in the dashboard stylesheet');
  return tokens;
}

const camelCase = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const tokens = extractTokens(readFileSync(sourcePath, 'utf8'));

// global.css: replace the marker-delimited token block.
const BEGIN = '/* BEGIN GENERATED TOKENS (scripts/sync-tokens.mjs — do not edit by hand) */';
const END = '/* END GENERATED TOKENS */';
const css = readFileSync(cssPath, 'utf8');
const begin = css.indexOf(BEGIN);
const end = css.indexOf(END);
if (begin === -1 || end === -1 || end < begin) {
  throw new Error('global.css is missing the BEGIN/END GENERATED TOKENS markers');
}
const cssBlock = [
  BEGIN,
  ':root {',
  ...tokens.map(([name, value]) => `  --z-${name}: ${value};`),
  '}',
  END,
].join('\n');
writeFileSync(cssPath, css.slice(0, begin) + cssBlock + css.slice(end + END.length));
console.log(`synced ${tokens.length} tokens into global.css`);

// src/theme/colors.ts: fully generated.
const colorLines = tokens.map(([name, value]) => `  ${camelCase(name)}: '${value}',`);
for (const [key, { value, comment }] of Object.entries(MOBILE_EXTRAS)) {
  colorLines.push(`  /** ${comment} */`, `  ${key}: '${value}',`);
}
writeFileSync(
  colorsPath,
  `/**
 * GENERATED by scripts/sync-tokens.mjs from web/dashboard-next/src/styles.scss
 * — do not edit by hand; run \`pnpm run sync:tokens\`.
 *
 * Zeta design tokens as raw values, for the places NativeWind classes cannot
 * reach: icon \`color\` props, navigator options, placeholderTextColor.
 */
export const colors = {
${colorLines.join('\n')}
} as const;
`,
);
console.log(`synced ${tokens.length} tokens + ${Object.keys(MOBILE_EXTRAS).length} mobile extras into src/theme/colors.ts`);
