// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mocks/mock_querier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/OZIOisgood/zeta/internal/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockQuerier) AddUserToGroup(ctx context.Context, arg db.AddUserToGroupParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockQuerierMockRecorder) AddUserToGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockQuerier)(nil).AddUserToGroup), ctx, arg)
}

// CancelBooking mocks base method.
func (m *MockQuerier) CancelBooking(ctx context.Context, arg db.CancelBookingParams) (db.CoachingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, arg)
	ret0, _ := ret[0].(db.CoachingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockQuerierMockRecorder) CancelBooking(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockQuerier)(nil).CancelBooking), ctx, arg)
}

// CheckUserGroup mocks base method.
func (m *MockQuerier) CheckUserGroup(ctx context.Context, arg db.CheckUserGroupParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserGroup", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserGroup indicates an expected call of CheckUserGroup.
func (mr *MockQuerierMockRecorder) CheckUserGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserGroup", reflect.TypeOf((*MockQuerier)(nil).CheckUserGroup), ctx, arg)
}

// CountConflictingBookings mocks base method.
func (m *MockQuerier) CountConflictingBookings(ctx context.Context, arg db.CountConflictingBookingsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConflictingBookings", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConflictingBookings indicates an expected call of CountConflictingBookings.
func (mr *MockQuerierMockRecorder) CountConflictingBookings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConflictingBookings", reflect.TypeOf((*MockQuerier)(nil).CountConflictingBookings), ctx, arg)
}

// CountVideosWithoutReviews mocks base method.
func (m *MockQuerier) CountVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVideosWithoutReviews", ctx, assetID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountVideosWithoutReviews indicates an expected call of CountVideosWithoutReviews.
func (mr *MockQuerierMockRecorder) CountVideosWithoutReviews(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVideosWithoutReviews", reflect.TypeOf((*MockQuerier)(nil).CountVideosWithoutReviews), ctx, assetID)
}

// CreateAsset mocks base method.
func (m *MockQuerier) CreateAsset(ctx context.Context, arg db.CreateAssetParams) (db.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", ctx, arg)
	ret0, _ := ret[0].(db.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockQuerierMockRecorder) CreateAsset(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockQuerier)(nil).CreateAsset), ctx, arg)
}

// CreateAvailability mocks base method.
func (m *MockQuerier) CreateAvailability(ctx context.Context, arg db.CreateAvailabilityParams) (db.CoachingAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailability", ctx, arg)
	ret0, _ := ret[0].(db.CoachingAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAvailability indicates an expected call of CreateAvailability.
func (mr *MockQuerierMockRecorder) CreateAvailability(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailability", reflect.TypeOf((*MockQuerier)(nil).CreateAvailability), ctx, arg)
}

// CreateBlockedSlot mocks base method.
func (m *MockQuerier) CreateBlockedSlot(ctx context.Context, arg db.CreateBlockedSlotParams) (db.CoachingBlockedSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlockedSlot", ctx, arg)
	ret0, _ := ret[0].(db.CoachingBlockedSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlockedSlot indicates an expected call of CreateBlockedSlot.
func (mr *MockQuerierMockRecorder) CreateBlockedSlot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlockedSlot", reflect.TypeOf((*MockQuerier)(nil).CreateBlockedSlot), ctx, arg)
}

// CreateBooking mocks base method.
func (m *MockQuerier) CreateBooking(ctx context.Context, arg db.CreateBookingParams) (db.CoachingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, arg)
	ret0, _ := ret[0].(db.CoachingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockQuerierMockRecorder) CreateBooking(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockQuerier)(nil).CreateBooking), ctx, arg)
}

// CreateBookingReminder mocks base method.
func (m *MockQuerier) CreateBookingReminder(ctx context.Context, arg db.CreateBookingReminderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookingReminder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBookingReminder indicates an expected call of CreateBookingReminder.
func (mr *MockQuerierMockRecorder) CreateBookingReminder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookingReminder", reflect.TypeOf((*MockQuerier)(nil).CreateBookingReminder), ctx, arg)
}

// CreateGroup mocks base method.
func (m *MockQuerier) CreateGroup(ctx context.Context, arg db.CreateGroupParams) (db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, arg)
	ret0, _ := ret[0].(db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockQuerierMockRecorder) CreateGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockQuerier)(nil).CreateGroup), ctx, arg)
}

// CreateGroupInvitation mocks base method.
func (m *MockQuerier) CreateGroupInvitation(ctx context.Context, arg db.CreateGroupInvitationParams) (db.GroupInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupInvitation", ctx, arg)
	ret0, _ := ret[0].(db.GroupInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroupInvitation indicates an expected call of CreateGroupInvitation.
func (mr *MockQuerierMockRecorder) CreateGroupInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupInvitation", reflect.TypeOf((*MockQuerier)(nil).CreateGroupInvitation), ctx, arg)
}

// CreateSessionType mocks base method.
func (m *MockQuerier) CreateSessionType(ctx context.Context, arg db.CreateSessionTypeParams) (db.CoachingSessionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionType", ctx, arg)
	ret0, _ := ret[0].(db.CoachingSessionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionType indicates an expected call of CreateSessionType.
func (mr *MockQuerierMockRecorder) CreateSessionType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionType", reflect.TypeOf((*MockQuerier)(nil).CreateSessionType), ctx, arg)
}

// CreateVideo mocks base method.
func (m *MockQuerier) CreateVideo(ctx context.Context, arg db.CreateVideoParams) (db.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, arg)
	ret0, _ := ret[0].(db.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockQuerierMockRecorder) CreateVideo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockQuerier)(nil).CreateVideo), ctx, arg)
}

// CreateVideoReview mocks base method.
func (m *MockQuerier) CreateVideoReview(ctx context.Context, arg db.CreateVideoReviewParams) (db.VideoReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideoReview", ctx, arg)
	ret0, _ := ret[0].(db.VideoReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideoReview indicates an expected call of CreateVideoReview.
func (mr *MockQuerierMockRecorder) CreateVideoReview(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideoReview", reflect.TypeOf((*MockQuerier)(nil).CreateVideoReview), ctx, arg)
}

// DeactivateSessionType mocks base method.
func (m *MockQuerier) DeactivateSessionType(ctx context.Context, arg db.DeactivateSessionTypeParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateSessionType", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateSessionType indicates an expected call of DeactivateSessionType.
func (mr *MockQuerierMockRecorder) DeactivateSessionType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateSessionType", reflect.TypeOf((*MockQuerier)(nil).DeactivateSessionType), ctx, arg)
}

// DeleteAvailability mocks base method.
func (m *MockQuerier) DeleteAvailability(ctx context.Context, arg db.DeleteAvailabilityParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailability", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvailability indicates an expected call of DeleteAvailability.
func (mr *MockQuerierMockRecorder) DeleteAvailability(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailability", reflect.TypeOf((*MockQuerier)(nil).DeleteAvailability), ctx, arg)
}

// DeleteBlockedSlot mocks base method.
func (m *MockQuerier) DeleteBlockedSlot(ctx context.Context, arg db.DeleteBlockedSlotParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlockedSlot", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlockedSlot indicates an expected call of DeleteBlockedSlot.
func (mr *MockQuerierMockRecorder) DeleteBlockedSlot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlockedSlot", reflect.TypeOf((*MockQuerier)(nil).DeleteBlockedSlot), ctx, arg)
}

// DeleteGroup mocks base method.
func (m *MockQuerier) DeleteGroup(ctx context.Context, arg db.DeleteGroupParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockQuerierMockRecorder) DeleteGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockQuerier)(nil).DeleteGroup), ctx, arg)
}

// DeleteVideoReview mocks base method.
func (m *MockQuerier) DeleteVideoReview(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideoReview", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideoReview indicates an expected call of DeleteVideoReview.
func (mr *MockQuerierMockRecorder) DeleteVideoReview(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideoReview", reflect.TypeOf((*MockQuerier)(nil).DeleteVideoReview), ctx, id)
}

// GetAsset mocks base method.
func (m *MockQuerier) GetAsset(ctx context.Context, id pgtype.UUID) (db.GetAssetRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", ctx, id)
	ret0, _ := ret[0].(db.GetAssetRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockQuerierMockRecorder) GetAsset(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockQuerier)(nil).GetAsset), ctx, id)
}

// GetAssetOwnerByVideoID mocks base method.
func (m *MockQuerier) GetAssetOwnerByVideoID(ctx context.Context, id pgtype.UUID) (db.GetAssetOwnerByVideoIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetOwnerByVideoID", ctx, id)
	ret0, _ := ret[0].(db.GetAssetOwnerByVideoIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetOwnerByVideoID indicates an expected call of GetAssetOwnerByVideoID.
func (mr *MockQuerierMockRecorder) GetAssetOwnerByVideoID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetOwnerByVideoID", reflect.TypeOf((*MockQuerier)(nil).GetAssetOwnerByVideoID), ctx, id)
}

// GetAssetStatusByVideoID mocks base method.
func (m *MockQuerier) GetAssetStatusByVideoID(ctx context.Context, id pgtype.UUID) (db.AssetStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetStatusByVideoID", ctx, id)
	ret0, _ := ret[0].(db.AssetStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetStatusByVideoID indicates an expected call of GetAssetStatusByVideoID.
func (mr *MockQuerierMockRecorder) GetAssetStatusByVideoID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetStatusByVideoID", reflect.TypeOf((*MockQuerier)(nil).GetAssetStatusByVideoID), ctx, id)
}

// GetAssetVideos mocks base method.
func (m *MockQuerier) GetAssetVideos(ctx context.Context, assetID pgtype.UUID) ([]db.GetAssetVideosRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetVideos", ctx, assetID)
	ret0, _ := ret[0].([]db.GetAssetVideosRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetVideos indicates an expected call of GetAssetVideos.
func (mr *MockQuerierMockRecorder) GetAssetVideos(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetVideos", reflect.TypeOf((*MockQuerier)(nil).GetAssetVideos), ctx, assetID)
}

// GetBooking mocks base method.
func (m *MockQuerier) GetBooking(ctx context.Context, arg db.GetBookingParams) (db.CoachingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooking", ctx, arg)
	ret0, _ := ret[0].(db.CoachingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooking indicates an expected call of GetBooking.
func (mr *MockQuerierMockRecorder) GetBooking(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooking", reflect.TypeOf((*MockQuerier)(nil).GetBooking), ctx, arg)
}

// GetGroup mocks base method.
func (m *MockQuerier) GetGroup(ctx context.Context, id pgtype.UUID) (db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, id)
	ret0, _ := ret[0].(db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockQuerierMockRecorder) GetGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockQuerier)(nil).GetGroup), ctx, id)
}

// GetGroupInvitationByCode mocks base method.
func (m *MockQuerier) GetGroupInvitationByCode(ctx context.Context, code string) (db.GroupInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupInvitationByCode", ctx, code)
	ret0, _ := ret[0].(db.GroupInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupInvitationByCode indicates an expected call of GetGroupInvitationByCode.
func (mr *MockQuerierMockRecorder) GetGroupInvitationByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupInvitationByCode", reflect.TypeOf((*MockQuerier)(nil).GetGroupInvitationByCode), ctx, code)
}

// GetGroupInvitationByID mocks base method.
func (m *MockQuerier) GetGroupInvitationByID(ctx context.Context, arg db.GetGroupInvitationByIDParams) (db.GroupInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupInvitationByID", ctx, arg)
	ret0, _ := ret[0].(db.GroupInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupInvitationByID indicates an expected call of GetGroupInvitationByID.
func (mr *MockQuerierMockRecorder) GetGroupInvitationByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupInvitationByID", reflect.TypeOf((*MockQuerier)(nil).GetGroupInvitationByID), ctx, arg)
}

// GetSessionType mocks base method.
func (m *MockQuerier) GetSessionType(ctx context.Context, arg db.GetSessionTypeParams) (db.CoachingSessionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionType", ctx, arg)
	ret0, _ := ret[0].(db.CoachingSessionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionType indicates an expected call of GetSessionType.
func (mr *MockQuerierMockRecorder) GetSessionType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionType", reflect.TypeOf((*MockQuerier)(nil).GetSessionType), ctx, arg)
}

// GetUserPreferences mocks base method.
func (m *MockQuerier) GetUserPreferences(ctx context.Context, userID string) (db.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPreferences", ctx, userID)
	ret0, _ := ret[0].(db.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPreferences indicates an expected call of GetUserPreferences.
func (mr *MockQuerierMockRecorder) GetUserPreferences(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPreferences", reflect.TypeOf((*MockQuerier)(nil).GetUserPreferences), ctx, userID)
}

// GetUserTimezone mocks base method.
func (m *MockQuerier) GetUserTimezone(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTimezone", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTimezone indicates an expected call of GetUserTimezone.
func (mr *MockQuerierMockRecorder) GetUserTimezone(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTimezone", reflect.TypeOf((*MockQuerier)(nil).GetUserTimezone), ctx, userID)
}

// HasVideosWithoutReviews mocks base method.
func (m *MockQuerier) HasVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasVideosWithoutReviews", ctx, assetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasVideosWithoutReviews indicates an expected call of HasVideosWithoutReviews.
func (mr *MockQuerierMockRecorder) HasVideosWithoutReviews(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVideosWithoutReviews", reflect.TypeOf((*MockQuerier)(nil).HasVideosWithoutReviews), ctx, assetID)
}

// ListActiveExpertsInGroup mocks base method.
func (m *MockQuerier) ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveExpertsInGroup", ctx, groupID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveExpertsInGroup indicates an expected call of ListActiveExpertsInGroup.
func (mr *MockQuerierMockRecorder) ListActiveExpertsInGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveExpertsInGroup", reflect.TypeOf((*MockQuerier)(nil).ListActiveExpertsInGroup), ctx, groupID)
}

// ListAssets mocks base method.
func (m *MockQuerier) ListAssets(ctx context.Context) ([]db.ListAssetsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssets", ctx)
	ret0, _ := ret[0].([]db.ListAssetsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssets indicates an expected call of ListAssets.
func (mr *MockQuerierMockRecorder) ListAssets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssets", reflect.TypeOf((*MockQuerier)(nil).ListAssets), ctx)
}

// ListAvailabilityByExpertGroup mocks base method.
func (m *MockQuerier) ListAvailabilityByExpertGroup(ctx context.Context, arg db.ListAvailabilityByExpertGroupParams) ([]db.CoachingAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailabilityByExpertGroup", ctx, arg)
	ret0, _ := ret[0].([]db.CoachingAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailabilityByExpertGroup indicates an expected call of ListAvailabilityByExpertGroup.
func (mr *MockQuerierMockRecorder) ListAvailabilityByExpertGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailabilityByExpertGroup", reflect.TypeOf((*MockQuerier)(nil).ListAvailabilityByExpertGroup), ctx, arg)
}

// ListAvailabilityByExpertGroupDay mocks base method.
func (m *MockQuerier) ListAvailabilityByExpertGroupDay(ctx context.Context, arg db.ListAvailabilityByExpertGroupDayParams) ([]db.CoachingAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailabilityByExpertGroupDay", ctx, arg)
	ret0, _ := ret[0].([]db.CoachingAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailabilityByExpertGroupDay indicates an expected call of ListAvailabilityByExpertGroupDay.
func (mr *MockQuerierMockRecorder) ListAvailabilityByExpertGroupDay(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailabilityByExpertGroupDay", reflect.TypeOf((*MockQuerier)(nil).ListAvailabilityByExpertGroupDay), ctx, arg)
}

// ListAvailabilityByGroup mocks base method.
func (m *MockQuerier) ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]db.CoachingAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailabilityByGroup", ctx, groupID)
	ret0, _ := ret[0].([]db.CoachingAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailabilityByGroup indicates an expected call of ListAvailabilityByGroup.
func (mr *MockQuerierMockRecorder) ListAvailabilityByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailabilityByGroup", reflect.TypeOf((*MockQuerier)(nil).ListAvailabilityByGroup), ctx, groupID)
}

// ListBlockedSlots mocks base method.
func (m *MockQuerier) ListBlockedSlots(ctx context.Context, arg db.ListBlockedSlotsParams) ([]db.CoachingBlockedSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedSlots", ctx, arg)
	ret0, _ := ret[0].([]db.CoachingBlockedSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockedSlots indicates an expected call of ListBlockedSlots.
func (mr *MockQuerierMockRecorder) ListBlockedSlots(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedSlots", reflect.TypeOf((*MockQuerier)(nil).ListBlockedSlots), ctx, arg)
}

// ListBookingsByExpertInRange mocks base method.
func (m *MockQuerier) ListBookingsByExpertInRange(ctx context.Context, arg db.ListBookingsByExpertInRangeParams) ([]db.CoachingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookingsByExpertInRange", ctx, arg)
	ret0, _ := ret[0].([]db.CoachingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookingsByExpertInRange indicates an expected call of ListBookingsByExpertInRange.
func (mr *MockQuerierMockRecorder) ListBookingsByExpertInRange(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookingsByExpertInRange", reflect.TypeOf((*MockQuerier)(nil).ListBookingsByExpertInRange), ctx, arg)
}

// ListGroupBookings mocks base method.
func (m *MockQuerier) ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]db.ListGroupBookingsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupBookings", ctx, groupID)
	ret0, _ := ret[0].([]db.ListGroupBookingsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupBookings indicates an expected call of ListGroupBookings.
func (mr *MockQuerierMockRecorder) ListGroupBookings(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupBookings", reflect.TypeOf((*MockQuerier)(nil).ListGroupBookings), ctx, groupID)
}

// ListGroupMembers mocks base method.
func (m *MockQuerier) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupMembers", ctx, groupID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupMembers indicates an expected call of ListGroupMembers.
func (mr *MockQuerierMockRecorder) ListGroupMembers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupMembers", reflect.TypeOf((*MockQuerier)(nil).ListGroupMembers), ctx, groupID)
}

// ListMyBookings mocks base method.
func (m *MockQuerier) ListMyBookings(ctx context.Context, arg db.ListMyBookingsParams) ([]db.ListMyBookingsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyBookings", ctx, arg)
	ret0, _ := ret[0].([]db.ListMyBookingsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyBookings indicates an expected call of ListMyBookings.
func (mr *MockQuerierMockRecorder) ListMyBookings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyBookings", reflect.TypeOf((*MockQuerier)(nil).ListMyBookings), ctx, arg)
}

// ListPendingReminders mocks base method.
func (m *MockQuerier) ListPendingReminders(ctx context.Context) ([]db.ListPendingRemindersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingReminders", ctx)
	ret0, _ := ret[0].([]db.ListPendingRemindersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingReminders indicates an expected call of ListPendingReminders.
func (mr *MockQuerierMockRecorder) ListPendingReminders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingReminders", reflect.TypeOf((*MockQuerier)(nil).ListPendingReminders), ctx)
}

// ListSessionTypesByExpertGroup mocks base method.
func (m *MockQuerier) ListSessionTypesByExpertGroup(ctx context.Context, arg db.ListSessionTypesByExpertGroupParams) ([]db.CoachingSessionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionTypesByExpertGroup", ctx, arg)
	ret0, _ := ret[0].([]db.CoachingSessionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionTypesByExpertGroup indicates an expected call of ListSessionTypesByExpertGroup.
func (mr *MockQuerierMockRecorder) ListSessionTypesByExpertGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionTypesByExpertGroup", reflect.TypeOf((*MockQuerier)(nil).ListSessionTypesByExpertGroup), ctx, arg)
}

// ListSessionTypesByGroup mocks base method.
func (m *MockQuerier) ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]db.CoachingSessionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionTypesByGroup", ctx, groupID)
	ret0, _ := ret[0].([]db.CoachingSessionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionTypesByGroup indicates an expected call of ListSessionTypesByGroup.
func (mr *MockQuerierMockRecorder) ListSessionTypesByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionTypesByGroup", reflect.TypeOf((*MockQuerier)(nil).ListSessionTypesByGroup), ctx, groupID)
}

// ListUserGroups mocks base method.
func (m *MockQuerier) ListUserGroups(ctx context.Context, userID string) ([]db.ListUserGroupsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserGroups", ctx, userID)
	ret0, _ := ret[0].([]db.ListUserGroupsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserGroups indicates an expected call of ListUserGroups.
func (mr *MockQuerierMockRecorder) ListUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserGroups", reflect.TypeOf((*MockQuerier)(nil).ListUserGroups), ctx, userID)
}

// ListVideoReviews mocks base method.
func (m *MockQuerier) ListVideoReviews(ctx context.Context, videoID pgtype.UUID) ([]db.VideoReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideoReviews", ctx, videoID)
	ret0, _ := ret[0].([]db.VideoReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideoReviews indicates an expected call of ListVideoReviews.
func (mr *MockQuerierMockRecorder) ListVideoReviews(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideoReviews", reflect.TypeOf((*MockQuerier)(nil).ListVideoReviews), ctx, videoID)
}

// MarkReminderSent mocks base method.
func (m *MockQuerier) MarkReminderSent(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReminderSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReminderSent indicates an expected call of MarkReminderSent.
func (mr *MockQuerierMockRecorder) MarkReminderSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReminderSent", reflect.TypeOf((*MockQuerier)(nil).MarkReminderSent), ctx, id)
}

// RemoveUserFromGroup mocks base method.
func (m *MockQuerier) RemoveUserFromGroup(ctx context.Context, arg db.RemoveUserFromGroupParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockQuerierMockRecorder) RemoveUserFromGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockQuerier)(nil).RemoveUserFromGroup), ctx, arg)
}

// UpdateAssetStatus mocks base method.
func (m *MockQuerier) UpdateAssetStatus(ctx context.Context, arg db.UpdateAssetStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssetStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAssetStatus indicates an expected call of UpdateAssetStatus.
func (mr *MockQuerierMockRecorder) UpdateAssetStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssetStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateAssetStatus), ctx, arg)
}

// UpdateAvailability mocks base method.
func (m *MockQuerier) UpdateAvailability(ctx context.Context, arg db.UpdateAvailabilityParams) (db.CoachingAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailability", ctx, arg)
	ret0, _ := ret[0].(db.CoachingAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvailability indicates an expected call of UpdateAvailability.
func (mr *MockQuerierMockRecorder) UpdateAvailability(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailability", reflect.TypeOf((*MockQuerier)(nil).UpdateAvailability), ctx, arg)
}

// UpdateGroup mocks base method.
func (m *MockQuerier) UpdateGroup(ctx context.Context, arg db.UpdateGroupParams) (db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, arg)
	ret0, _ := ret[0].(db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockQuerierMockRecorder) UpdateGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockQuerier)(nil).UpdateGroup), ctx, arg)
}

// UpdateGroupInvitationStatus mocks base method.
func (m *MockQuerier) UpdateGroupInvitationStatus(ctx context.Context, arg db.UpdateGroupInvitationStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupInvitationStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroupInvitationStatus indicates an expected call of UpdateGroupInvitationStatus.
func (mr *MockQuerierMockRecorder) UpdateGroupInvitationStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupInvitationStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateGroupInvitationStatus), ctx, arg)
}

// UpdateSessionType mocks base method.
func (m *MockQuerier) UpdateSessionType(ctx context.Context, arg db.UpdateSessionTypeParams) (db.CoachingSessionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionType", ctx, arg)
	ret0, _ := ret[0].(db.CoachingSessionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSessionType indicates an expected call of UpdateSessionType.
func (mr *MockQuerierMockRecorder) UpdateSessionType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionType", reflect.TypeOf((*MockQuerier)(nil).UpdateSessionType), ctx, arg)
}

// UpdateUserAvatar mocks base method.
func (m *MockQuerier) UpdateUserAvatar(ctx context.Context, arg db.UpdateUserAvatarParams) (db.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatar", ctx, arg)
	ret0, _ := ret[0].(db.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserAvatar indicates an expected call of UpdateUserAvatar.
func (mr *MockQuerierMockRecorder) UpdateUserAvatar(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatar", reflect.TypeOf((*MockQuerier)(nil).UpdateUserAvatar), ctx, arg)
}

// UpdateVideoMuxAssetID mocks base method.
func (m *MockQuerier) UpdateVideoMuxAssetID(ctx context.Context, arg db.UpdateVideoMuxAssetIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoMuxAssetID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoMuxAssetID indicates an expected call of UpdateVideoMuxAssetID.
func (mr *MockQuerierMockRecorder) UpdateVideoMuxAssetID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoMuxAssetID", reflect.TypeOf((*MockQuerier)(nil).UpdateVideoMuxAssetID), ctx, arg)
}

// UpdateVideoReview mocks base method.
func (m *MockQuerier) UpdateVideoReview(ctx context.Context, arg db.UpdateVideoReviewParams) (db.VideoReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoReview", ctx, arg)
	ret0, _ := ret[0].(db.VideoReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVideoReview indicates an expected call of UpdateVideoReview.
func (mr *MockQuerierMockRecorder) UpdateVideoReview(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoReview", reflect.TypeOf((*MockQuerier)(nil).UpdateVideoReview), ctx, arg)
}

// UpdateVideoStatus mocks base method.
func (m *MockQuerier) UpdateVideoStatus(ctx context.Context, arg db.UpdateVideoStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoStatus indicates an expected call of UpdateVideoStatus.
func (mr *MockQuerierMockRecorder) UpdateVideoStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateVideoStatus), ctx, arg)
}

// UpdateVideoStatusByUploadID mocks base method.
func (m *MockQuerier) UpdateVideoStatusByUploadID(ctx context.Context, arg db.UpdateVideoStatusByUploadIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoStatusByUploadID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoStatusByUploadID indicates an expected call of UpdateVideoStatusByUploadID.
func (mr *MockQuerierMockRecorder) UpdateVideoStatusByUploadID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoStatusByUploadID", reflect.TypeOf((*MockQuerier)(nil).UpdateVideoStatusByUploadID), ctx, arg)
}

// UpsertUserAvatar mocks base method.
func (m *MockQuerier) UpsertUserAvatar(ctx context.Context, arg db.UpsertUserAvatarParams) (db.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserAvatar", ctx, arg)
	ret0, _ := ret[0].(db.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserAvatar indicates an expected call of UpsertUserAvatar.
func (mr *MockQuerierMockRecorder) UpsertUserAvatar(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserAvatar", reflect.TypeOf((*MockQuerier)(nil).UpsertUserAvatar), ctx, arg)
}

// UpsertUserPreferences mocks base method.
func (m *MockQuerier) UpsertUserPreferences(ctx context.Context, arg db.UpsertUserPreferencesParams) (db.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserPreferences", ctx, arg)
	ret0, _ := ret[0].(db.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserPreferences indicates an expected call of UpsertUserPreferences.
func (mr *MockQuerierMockRecorder) UpsertUserPreferences(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserPreferences", reflect.TypeOf((*MockQuerier)(nil).UpsertUserPreferences), ctx, arg)
}

// UpsertUserTimezone mocks base method.
func (m *MockQuerier) UpsertUserTimezone(ctx context.Context, arg db.UpsertUserTimezoneParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserTimezone", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserTimezone indicates an expected call of UpsertUserTimezone.
func (mr *MockQuerierMockRecorder) UpsertUserTimezone(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserTimezone", reflect.TypeOf((*MockQuerier)(nil).UpsertUserTimezone), ctx, arg)
}
