// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateAssetParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.Name, arg.Description)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (asset_id, mux_upload_id, status)
VALUES ($1, $2, $3)
RETURNING id, asset_id, mux_upload_id, mux_asset_id, status, created_at, updated_at
`

type CreateVideoParams struct {
	AssetID     pgtype.UUID
	MuxUploadID string
	Status      VideoStatus
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.AssetID, arg.MuxUploadID, arg.Status)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.MuxUploadID,
		&i.MuxAssetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoMuxAssetID = `-- name: UpdateVideoMuxAssetID :exec
UPDATE videos
SET mux_asset_id = $2, status = 'ready', updated_at = NOW()
WHERE id = $1
`

type UpdateVideoMuxAssetIDParams struct {
	ID         pgtype.UUID
	MuxAssetID pgtype.Text
}

func (q *Queries) UpdateVideoMuxAssetID(ctx context.Context, arg UpdateVideoMuxAssetIDParams) error {
	_, err := q.db.Exec(ctx, updateVideoMuxAssetID, arg.ID, arg.MuxAssetID)
	return err
}
