// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    actor_id, actor_type, actor_label, action,
    resource_type, resource_id, group_id,
    old_values, new_values, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
`

type CreateAuditEventParams struct {
	ActorID      pgtype.Text `json:"actor_id"`
	ActorType    string      `json:"actor_type"`
	ActorLabel   pgtype.Text `json:"actor_label"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	GroupID      pgtype.Text `json:"group_id"`
	OldValues    []byte      `json:"old_values"`
	NewValues    []byte      `json:"new_values"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ActorID,
		arg.ActorType,
		arg.ActorLabel,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.GroupID,
		arg.OldValues,
		arg.NewValues,
		arg.Metadata,
	)
	return err
}
