// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCoachingSession = `-- name: CancelCoachingSession :exec
UPDATE coaching_sessions
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelCoachingSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelCoachingSession, id)
	return err
}

const createCoachingSession = `-- name: CreateCoachingSession :one
INSERT INTO coaching_sessions (title, description, group_id, student_id, expert_id, scheduled_at, duration_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, group_id, student_id, expert_id, status, scheduled_at, duration_minutes, created_at, updated_at
`

type CreateCoachingSessionParams struct {
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	GroupID         pgtype.UUID        `json:"group_id"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
}

func (q *Queries) CreateCoachingSession(ctx context.Context, arg CreateCoachingSessionParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, createCoachingSession,
		arg.Title,
		arg.Description,
		arg.GroupID,
		arg.StudentID,
		arg.ExpertID,
		arg.ScheduledAt,
		arg.DurationMinutes,
	)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GroupID,
		&i.StudentID,
		&i.ExpertID,
		&i.Status,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoachingSessionReminder = `-- name: CreateCoachingSessionReminder :one
INSERT INTO coaching_session_reminders (session_id, reminder_24h_sent, reminder_1h_sent, reminder_15m_sent)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, reminder_24h_sent, reminder_1h_sent, reminder_15m_sent
`

type CreateCoachingSessionReminderParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	Reminder24hSent bool        `json:"reminder_24h_sent"`
	Reminder1hSent  bool        `json:"reminder_1h_sent"`
	Reminder15mSent bool        `json:"reminder_15m_sent"`
}

func (q *Queries) CreateCoachingSessionReminder(ctx context.Context, arg CreateCoachingSessionReminderParams) (CoachingSessionReminder, error) {
	row := q.db.QueryRow(ctx, createCoachingSessionReminder,
		arg.SessionID,
		arg.Reminder24hSent,
		arg.Reminder1hSent,
		arg.Reminder15mSent,
	)
	var i CoachingSessionReminder
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Reminder24hSent,
		&i.Reminder1hSent,
		&i.Reminder15mSent,
	)
	return i, err
}

const getCoachingSession = `-- name: GetCoachingSession :one
SELECT cs.id, cs.title, cs.description, cs.group_id, cs.student_id, cs.expert_id, cs.status, cs.scheduled_at, cs.duration_minutes, cs.created_at, cs.updated_at,
       g.name AS group_name
FROM coaching_sessions cs
JOIN groups g ON g.id = cs.group_id
WHERE cs.id = $1
`

type GetCoachingSessionRow struct {
	ID              pgtype.UUID           `json:"id"`
	Title           string                `json:"title"`
	Description     string                `json:"description"`
	GroupID         pgtype.UUID           `json:"group_id"`
	StudentID       string                `json:"student_id"`
	ExpertID        string                `json:"expert_id"`
	Status          CoachingSessionStatus `json:"status"`
	ScheduledAt     pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes int32                 `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	GroupName       string                `json:"group_name"`
}

func (q *Queries) GetCoachingSession(ctx context.Context, id pgtype.UUID) (GetCoachingSessionRow, error) {
	row := q.db.QueryRow(ctx, getCoachingSession, id)
	var i GetCoachingSessionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GroupID,
		&i.StudentID,
		&i.ExpertID,
		&i.Status,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupName,
	)
	return i, err
}

const getSessionsNeedingReminder15m = `-- name: GetSessionsNeedingReminder15m :many
SELECT cs.id, cs.title, cs.description, cs.student_id, cs.expert_id, cs.scheduled_at, cs.duration_minutes,
       g.name AS group_name
FROM coaching_sessions cs
JOIN coaching_session_reminders csr ON csr.session_id = cs.id
JOIN groups g ON g.id = cs.group_id
WHERE cs.status = 'scheduled'
  AND NOT csr.reminder_15m_sent
  AND cs.scheduled_at BETWEEN NOW() + INTERVAL '14 minutes' AND NOW() + INTERVAL '15 minutes 1 second'
`

type GetSessionsNeedingReminder15mRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	GroupName       string             `json:"group_name"`
}

func (q *Queries) GetSessionsNeedingReminder15m(ctx context.Context) ([]GetSessionsNeedingReminder15mRow, error) {
	rows, err := q.db.Query(ctx, getSessionsNeedingReminder15m)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsNeedingReminder15mRow
	for rows.Next() {
		var i GetSessionsNeedingReminder15mRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StudentID,
			&i.ExpertID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsNeedingReminder1h = `-- name: GetSessionsNeedingReminder1h :many
SELECT cs.id, cs.title, cs.description, cs.student_id, cs.expert_id, cs.scheduled_at, cs.duration_minutes,
       g.name AS group_name
FROM coaching_sessions cs
JOIN coaching_session_reminders csr ON csr.session_id = cs.id
JOIN groups g ON g.id = cs.group_id
WHERE cs.status = 'scheduled'
  AND NOT csr.reminder_1h_sent
  AND cs.scheduled_at BETWEEN NOW() + INTERVAL '59 minutes' AND NOW() + INTERVAL '1 hour 1 minute'
`

type GetSessionsNeedingReminder1hRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	GroupName       string             `json:"group_name"`
}

func (q *Queries) GetSessionsNeedingReminder1h(ctx context.Context) ([]GetSessionsNeedingReminder1hRow, error) {
	rows, err := q.db.Query(ctx, getSessionsNeedingReminder1h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsNeedingReminder1hRow
	for rows.Next() {
		var i GetSessionsNeedingReminder1hRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StudentID,
			&i.ExpertID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsNeedingReminder24h = `-- name: GetSessionsNeedingReminder24h :many
SELECT cs.id, cs.title, cs.description, cs.student_id, cs.expert_id, cs.scheduled_at, cs.duration_minutes,
       g.name AS group_name
FROM coaching_sessions cs
JOIN coaching_session_reminders csr ON csr.session_id = cs.id
JOIN groups g ON g.id = cs.group_id
WHERE cs.status = 'scheduled'
  AND NOT csr.reminder_24h_sent
  AND cs.scheduled_at BETWEEN NOW() + INTERVAL '23 hours 59 minutes' AND NOW() + INTERVAL '24 hours 1 minute'
`

type GetSessionsNeedingReminder24hRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	GroupName       string             `json:"group_name"`
}

func (q *Queries) GetSessionsNeedingReminder24h(ctx context.Context) ([]GetSessionsNeedingReminder24hRow, error) {
	rows, err := q.db.Query(ctx, getSessionsNeedingReminder24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsNeedingReminder24hRow
	for rows.Next() {
		var i GetSessionsNeedingReminder24hRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StudentID,
			&i.ExpertID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachingSessionsAll = `-- name: ListCoachingSessionsAll :many
SELECT cs.id, cs.title, cs.description, cs.group_id, cs.student_id, cs.expert_id, cs.status, cs.scheduled_at, cs.duration_minutes, cs.created_at, cs.updated_at,
       g.name AS group_name
FROM coaching_sessions cs
JOIN groups g ON g.id = cs.group_id
ORDER BY cs.scheduled_at DESC
`

type ListCoachingSessionsAllRow struct {
	ID              pgtype.UUID           `json:"id"`
	Title           string                `json:"title"`
	Description     string                `json:"description"`
	GroupID         pgtype.UUID           `json:"group_id"`
	StudentID       string                `json:"student_id"`
	ExpertID        string                `json:"expert_id"`
	Status          CoachingSessionStatus `json:"status"`
	ScheduledAt     pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes int32                 `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	GroupName       string                `json:"group_name"`
}

func (q *Queries) ListCoachingSessionsAll(ctx context.Context) ([]ListCoachingSessionsAllRow, error) {
	rows, err := q.db.Query(ctx, listCoachingSessionsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachingSessionsAllRow
	for rows.Next() {
		var i ListCoachingSessionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GroupID,
			&i.StudentID,
			&i.ExpertID,
			&i.Status,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachingSessionsByExpert = `-- name: ListCoachingSessionsByExpert :many
SELECT cs.id, cs.title, cs.description, cs.group_id, cs.student_id, cs.expert_id, cs.status, cs.scheduled_at, cs.duration_minutes, cs.created_at, cs.updated_at,
       g.name AS group_name
FROM coaching_sessions cs
JOIN groups g ON g.id = cs.group_id
WHERE cs.expert_id = $1
ORDER BY cs.scheduled_at DESC
`

type ListCoachingSessionsByExpertRow struct {
	ID              pgtype.UUID           `json:"id"`
	Title           string                `json:"title"`
	Description     string                `json:"description"`
	GroupID         pgtype.UUID           `json:"group_id"`
	StudentID       string                `json:"student_id"`
	ExpertID        string                `json:"expert_id"`
	Status          CoachingSessionStatus `json:"status"`
	ScheduledAt     pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes int32                 `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	GroupName       string                `json:"group_name"`
}

func (q *Queries) ListCoachingSessionsByExpert(ctx context.Context, expertID string) ([]ListCoachingSessionsByExpertRow, error) {
	rows, err := q.db.Query(ctx, listCoachingSessionsByExpert, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachingSessionsByExpertRow
	for rows.Next() {
		var i ListCoachingSessionsByExpertRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GroupID,
			&i.StudentID,
			&i.ExpertID,
			&i.Status,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachingSessionsByStudent = `-- name: ListCoachingSessionsByStudent :many
SELECT cs.id, cs.title, cs.description, cs.group_id, cs.student_id, cs.expert_id, cs.status, cs.scheduled_at, cs.duration_minutes, cs.created_at, cs.updated_at,
       g.name AS group_name
FROM coaching_sessions cs
JOIN groups g ON g.id = cs.group_id
WHERE cs.student_id = $1
ORDER BY cs.scheduled_at DESC
`

type ListCoachingSessionsByStudentRow struct {
	ID              pgtype.UUID           `json:"id"`
	Title           string                `json:"title"`
	Description     string                `json:"description"`
	GroupID         pgtype.UUID           `json:"group_id"`
	StudentID       string                `json:"student_id"`
	ExpertID        string                `json:"expert_id"`
	Status          CoachingSessionStatus `json:"status"`
	ScheduledAt     pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes int32                 `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	GroupName       string                `json:"group_name"`
}

func (q *Queries) ListCoachingSessionsByStudent(ctx context.Context, studentID string) ([]ListCoachingSessionsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listCoachingSessionsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachingSessionsByStudentRow
	for rows.Next() {
		var i ListCoachingSessionsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GroupID,
			&i.StudentID,
			&i.ExpertID,
			&i.Status,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminder15mSent = `-- name: MarkReminder15mSent :exec
UPDATE coaching_session_reminders SET reminder_15m_sent = TRUE WHERE session_id = $1
`

func (q *Queries) MarkReminder15mSent(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminder15mSent, sessionID)
	return err
}

const markReminder1hSent = `-- name: MarkReminder1hSent :exec
UPDATE coaching_session_reminders SET reminder_1h_sent = TRUE WHERE session_id = $1
`

func (q *Queries) MarkReminder1hSent(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminder1hSent, sessionID)
	return err
}

const markReminder24hSent = `-- name: MarkReminder24hSent :exec
UPDATE coaching_session_reminders SET reminder_24h_sent = TRUE WHERE session_id = $1
`

func (q *Queries) MarkReminder24hSent(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminder24hSent, sessionID)
	return err
}

const updateCoachingSession = `-- name: UpdateCoachingSession :one
UPDATE coaching_sessions
SET title = $2, description = $3, scheduled_at = $4, duration_minutes = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, group_id, student_id, expert_id, status, scheduled_at, duration_minutes, created_at, updated_at
`

type UpdateCoachingSessionParams struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
}

func (q *Queries) UpdateCoachingSession(ctx context.Context, arg UpdateCoachingSessionParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, updateCoachingSession,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.DurationMinutes,
	)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GroupID,
		&i.StudentID,
		&i.ExpertID,
		&i.Status,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCoachingSessionStatus = `-- name: UpdateCoachingSessionStatus :exec
UPDATE coaching_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCoachingSessionStatusParams struct {
	ID     pgtype.UUID           `json:"id"`
	Status CoachingSessionStatus `json:"status"`
}

func (q *Queries) UpdateCoachingSessionStatus(ctx context.Context, arg UpdateCoachingSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateCoachingSessionStatus, arg.ID, arg.Status)
	return err
}
