// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConflictingBookings = `-- name: CountConflictingBookings :one
SELECT COUNT(*) FROM coaching_bookings
WHERE expert_id = $1
  AND status != 'cancelled'
  AND scheduled_at < $3
  AND scheduled_at + (duration_minutes * interval '1 minute') > $2
`

type CountConflictingBookingsParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

func (q *Queries) CountConflictingBookings(ctx context.Context, arg CountConflictingBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConflictingBookings, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvailability = `-- name: CreateAvailability :one

INSERT INTO coaching_availability (expert_id, group_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type CreateAvailabilityParams struct {
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

// === Availability ===
func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.ExpertID,
		arg.GroupID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBlockedSlot = `-- name: CreateBlockedSlot :one

INSERT INTO coaching_blocked_slots (expert_id, blocked_date, start_time, end_time, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, blocked_date, start_time, end_time, reason, created_at
`

type CreateBlockedSlotParams struct {
	ExpertID    string      `json:"expert_id"`
	BlockedDate pgtype.Date `json:"blocked_date"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	Reason      pgtype.Text `json:"reason"`
}

// === Blocked Slots ===
func (q *Queries) CreateBlockedSlot(ctx context.Context, arg CreateBlockedSlotParams) (CoachingBlockedSlot, error) {
	row := q.db.QueryRow(ctx, createBlockedSlot,
		arg.ExpertID,
		arg.BlockedDate,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i CoachingBlockedSlot
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.BlockedDate,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO coaching_bookings (expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, status, cancellation_reason, cancelled_by, notes, created_at, updated_at
`

type CreateBookingParams struct {
	ExpertID        string             `json:"expert_id"`
	StudentID       string             `json:"student_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SessionTypeID   pgtype.UUID        `json:"session_type_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ExpertID,
		arg.StudentID,
		arg.GroupID,
		arg.SessionTypeID,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.Notes,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionType = `-- name: CreateSessionType :one

INSERT INTO coaching_session_types (expert_id, group_id, name, description, duration_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type CreateSessionTypeParams struct {
	ExpertID        string      `json:"expert_id"`
	GroupID         pgtype.UUID `json:"group_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
}

// === Session Types ===
func (q *Queries) CreateSessionType(ctx context.Context, arg CreateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, createSessionType,
		arg.ExpertID,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSessionType = `-- name: DeactivateSessionType :exec
UPDATE coaching_session_types
SET is_active = false, updated_at = NOW()
WHERE id = $1 AND expert_id = $2
`

type DeactivateSessionTypeParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeactivateSessionType(ctx context.Context, arg DeactivateSessionTypeParams) error {
	_, err := q.db.Exec(ctx, deactivateSessionType, arg.ID, arg.ExpertID)
	return err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM coaching_availability WHERE id = $1 AND expert_id = $2
`

type DeleteAvailabilityParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAvailability, arg.ID, arg.ExpertID)
	return err
}

const deleteBlockedSlot = `-- name: DeleteBlockedSlot :exec
DELETE FROM coaching_blocked_slots WHERE id = $1 AND expert_id = $2
`

type DeleteBlockedSlotParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteBlockedSlot(ctx context.Context, arg DeleteBlockedSlotParams) error {
	_, err := q.db.Exec(ctx, deleteBlockedSlot, arg.ID, arg.ExpertID)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, status, cancellation_reason, cancelled_by, notes, created_at, updated_at FROM coaching_bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id pgtype.UUID) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionType = `-- name: GetSessionType :one
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types WHERE id = $1
`

func (q *Queries) GetSessionType(ctx context.Context, id pgtype.UUID) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, getSessionType, id)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTimezone = `-- name: GetUserTimezone :one

SELECT timezone FROM user_preferences WHERE user_id = $1
`

// === Timezone ===
func (q *Queries) GetUserTimezone(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserTimezone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const listActiveExpertsInGroup = `-- name: ListActiveExpertsInGroup :many
SELECT DISTINCT expert_id FROM coaching_availability
WHERE group_id = $1 AND is_active = true
`

func (q *Queries) ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveExpertsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var expert_id string
		if err := rows.Scan(&expert_id); err != nil {
			return nil, err
		}
		items = append(items, expert_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByExpertGroup = `-- name: ListAvailabilityByExpertGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY day_of_week, start_time
`

type ListAvailabilityByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListAvailabilityByExpertGroup(ctx context.Context, arg ListAvailabilityByExpertGroupParams) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByGroup = `-- name: ListAvailabilityByGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, day_of_week, start_time
`

func (q *Queries) ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedSlots = `-- name: ListBlockedSlots :many
SELECT id, expert_id, blocked_date, start_time, end_time, reason, created_at FROM coaching_blocked_slots
WHERE expert_id = $1 AND blocked_date >= $2 AND blocked_date <= $3
ORDER BY blocked_date, start_time
`

type ListBlockedSlotsParams struct {
	ExpertID string      `json:"expert_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListBlockedSlots(ctx context.Context, arg ListBlockedSlotsParams) ([]CoachingBlockedSlot, error) {
	rows, err := q.db.Query(ctx, listBlockedSlots, arg.ExpertID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBlockedSlot
	for rows.Next() {
		var i CoachingBlockedSlot
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.BlockedDate,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByExpertInRange = `-- name: ListBookingsByExpertInRange :many

SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, status, cancellation_reason, cancelled_by, notes, created_at, updated_at FROM coaching_bookings
WHERE expert_id = $1
  AND scheduled_at >= $2
  AND scheduled_at < $3
  AND status != 'cancelled'
ORDER BY scheduled_at
`

type ListBookingsByExpertInRangeParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

// === Bookings ===
func (q *Queries) ListBookingsByExpertInRange(ctx context.Context, arg ListBookingsByExpertInRangeParams) ([]CoachingBooking, error) {
	rows, err := q.db.Query(ctx, listBookingsByExpertInRange, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBooking
	for rows.Next() {
		var i CoachingBooking
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupBookings = `-- name: ListGroupBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.status, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cst.name AS session_type_name
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
WHERE cb.group_id = $1 AND cb.status = 'confirmed'
ORDER BY cb.scheduled_at
`

type ListGroupBookingsRow struct {
	ID                 pgtype.UUID           `json:"id"`
	ExpertID           string                `json:"expert_id"`
	StudentID          string                `json:"student_id"`
	GroupID            pgtype.UUID           `json:"group_id"`
	SessionTypeID      pgtype.UUID           `json:"session_type_id"`
	ScheduledAt        pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes    int32                 `json:"duration_minutes"`
	Status             CoachingBookingStatus `json:"status"`
	CancellationReason pgtype.Text           `json:"cancellation_reason"`
	CancelledBy        pgtype.Text           `json:"cancelled_by"`
	Notes              pgtype.Text           `json:"notes"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz    `json:"updated_at"`
	SessionTypeName    string                `json:"session_type_name"`
}

func (q *Queries) ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBookingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupBookings, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupBookingsRow
	for rows.Next() {
		var i ListGroupBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookings = `-- name: ListMyBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.status, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cst.name AS session_type_name
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
WHERE cb.expert_id = $1 OR cb.student_id = $1
ORDER BY cb.scheduled_at DESC
`

type ListMyBookingsRow struct {
	ID                 pgtype.UUID           `json:"id"`
	ExpertID           string                `json:"expert_id"`
	StudentID          string                `json:"student_id"`
	GroupID            pgtype.UUID           `json:"group_id"`
	SessionTypeID      pgtype.UUID           `json:"session_type_id"`
	ScheduledAt        pgtype.Timestamptz    `json:"scheduled_at"`
	DurationMinutes    int32                 `json:"duration_minutes"`
	Status             CoachingBookingStatus `json:"status"`
	CancellationReason pgtype.Text           `json:"cancellation_reason"`
	CancelledBy        pgtype.Text           `json:"cancelled_by"`
	Notes              pgtype.Text           `json:"notes"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz    `json:"updated_at"`
	SessionTypeName    string                `json:"session_type_name"`
}

func (q *Queries) ListMyBookings(ctx context.Context, expertID string) ([]ListMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMyBookings, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyBookingsRow
	for rows.Next() {
		var i ListMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByExpertGroup = `-- name: ListSessionTypesByExpertGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY duration_minutes
`

type ListSessionTypesByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListSessionTypesByExpertGroup(ctx context.Context, arg ListSessionTypesByExpertGroupParams) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByGroup = `-- name: ListSessionTypesByGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, duration_minutes
`

func (q *Queries) ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailability = `-- name: UpdateAvailability :one
UPDATE coaching_availability
SET day_of_week = $2, start_time = $3, end_time = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type UpdateAvailabilityParams struct {
	ID        pgtype.UUID `json:"id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, updateAvailability,
		arg.ID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE coaching_bookings
SET status = $2,
    cancellation_reason = CASE WHEN $2 = 'cancelled' THEN $3 ELSE cancellation_reason END,
    cancelled_by = CASE WHEN $2 = 'cancelled' THEN $4 ELSE cancelled_by END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, status, cancellation_reason, cancelled_by, notes, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID                 pgtype.UUID           `json:"id"`
	Status             CoachingBookingStatus `json:"status"`
	CancellationReason pgtype.Text           `json:"cancellation_reason"`
	CancelledBy        pgtype.Text           `json:"cancelled_by"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus,
		arg.ID,
		arg.Status,
		arg.CancellationReason,
		arg.CancelledBy,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionType = `-- name: UpdateSessionType :one
UPDATE coaching_session_types
SET name = $2, description = $3, duration_minutes = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type UpdateSessionTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, updateSessionType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTimezone = `-- name: UpsertUserTimezone :exec
INSERT INTO user_preferences (user_id, timezone)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET timezone = $2, updated_at = NOW()
`

type UpsertUserTimezoneParams struct {
	UserID   string `json:"user_id"`
	Timezone string `json:"timezone"`
}

func (q *Queries) UpsertUserTimezone(ctx context.Context, arg UpsertUserTimezoneParams) error {
	_, err := q.db.Exec(ctx, upsertUserTimezone, arg.UserID, arg.Timezone)
	return err
}
