// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignBookingRecordingAsset = `-- name: AssignBookingRecordingAsset :one
UPDATE coaching_bookings
SET recording_asset_id = COALESCE(recording_asset_id, $2), updated_at = NOW()
WHERE id = $1
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number
`

type AssignBookingRecordingAssetParams struct {
	ID               pgtype.UUID `json:"id"`
	RecordingAssetID pgtype.UUID `json:"recording_asset_id"`
}

func (q *Queries) AssignBookingRecordingAsset(ctx context.Context, arg AssignBookingRecordingAssetParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, assignBookingRecordingAsset, arg.ID, arg.RecordingAssetID)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordingAssetID,
		&i.NextRecordingPartNumber,
	)
	return i, err
}

const cancelBooking = `-- name: CancelBooking :one
UPDATE coaching_bookings
SET is_cancelled = true,
    cancellation_reason = $2,
    cancelled_by = $3,
    updated_at = NOW()
WHERE id = $1 AND (expert_id = $4 OR student_id = $4)
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number
`

type CancelBookingParams struct {
	ID                 pgtype.UUID `json:"id"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
	CancelledBy        pgtype.Text `json:"cancelled_by"`
	ExpertID           string      `json:"expert_id"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, cancelBooking,
		arg.ID,
		arg.CancellationReason,
		arg.CancelledBy,
		arg.ExpertID,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordingAssetID,
		&i.NextRecordingPartNumber,
	)
	return i, err
}

const claimNextRecordingPart = `-- name: ClaimNextRecordingPart :one

WITH claimed_booking AS (
    UPDATE coaching_bookings booking
    SET next_recording_part_number = next_recording_part_number + 1,
        updated_at = NOW()
    WHERE booking.id = $5
      AND NOT EXISTS (
          SELECT 1 FROM coaching_booking_recordings recording
          WHERE recording.booking_id = booking.id
            AND recording.status IN ('starting', 'started', 'stopping')
      )
      AND NOT EXISTS (
          SELECT 1 FROM coaching_booking_recordings failed
          WHERE failed.booking_id = booking.id
            AND failed.status = 'failed'
            AND failed.updated_at > NOW() - interval '30 seconds'
      )
    RETURNING booking.id, booking.next_recording_part_number - 1 AS part_number
)
INSERT INTO coaching_booking_recordings (
    booking_id, part_number, provider, provider_uid,
    renderer_token_hash, renderer_token_expires_at
)
SELECT id, part_number, $1, $2,
       $3, $4
FROM claimed_booking
RETURNING booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at
`

type ClaimNextRecordingPartParams struct {
	Provider               string             `json:"provider"`
	ProviderUid            pgtype.Text        `json:"provider_uid"`
	RendererTokenHash      []byte             `json:"renderer_token_hash"`
	RendererTokenExpiresAt pgtype.Timestamptz `json:"renderer_token_expires_at"`
	BookingID              pgtype.UUID        `json:"booking_id"`
}

// === Simple recording parts ===
func (q *Queries) ClaimNextRecordingPart(ctx context.Context, arg ClaimNextRecordingPartParams) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, claimNextRecordingPart,
		arg.Provider,
		arg.ProviderUid,
		arg.RendererTokenHash,
		arg.RendererTokenExpiresAt,
		arg.BookingID,
	)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ProviderResourceID,
		&i.ProviderRecordingID,
		&i.ProviderUid,
		&i.OutputPrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.PartNumber,
		&i.Provider,
		&i.RendererTokenHash,
		&i.RendererTokenExpiresAt,
		&i.EmptySinceAt,
	)
	return i, err
}

const claimPendingRecordingPartImports = `-- name: ClaimPendingRecordingPartImports :many
WITH candidates AS (
    SELECT recording_import.id
    FROM coaching_recording_imports recording_import
    WHERE recording_import.status IN ('pending', 'importing', 'processing', 'failed')
      AND recording_import.attempts < 5
      AND (
          recording_import.last_attempt_at IS NULL
          OR (recording_import.status = 'importing' AND recording_import.last_attempt_at <= NOW() - interval '5 minutes')
          OR (recording_import.status <> 'importing' AND recording_import.last_attempt_at <= NOW() - interval '1 minute')
      )
    ORDER BY recording_import.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
), claimed AS (
    UPDATE coaching_recording_imports recording_import
    SET status = 'importing', attempts = attempts + 1, last_attempt_at = NOW(),
        error = NULL, updated_at = NOW()
    FROM candidates
    WHERE recording_import.id = candidates.id
    RETURNING recording_import.status, recording_import.gcs_object_name, recording_import.mux_asset_id, recording_import.mux_playback_id, recording_import.video_id, recording_import.attempts, recording_import.last_attempt_at, recording_import.imported_at, recording_import.error, recording_import.created_at, recording_import.updated_at, recording_import.id, recording_import.recording_id, recording_import.file_index
)
SELECT claimed.status, claimed.gcs_object_name, claimed.mux_asset_id, claimed.mux_playback_id, claimed.video_id, claimed.attempts, claimed.last_attempt_at, claimed.imported_at, claimed.error, claimed.created_at, claimed.updated_at, claimed.id, claimed.recording_id, claimed.file_index, recording.booking_id, recording.part_number, booking.recording_asset_id,
       booking.student_id, booking.group_id, booking.scheduled_at,
       booking.duration_minutes, session_type.name AS session_type_name
FROM claimed
JOIN coaching_booking_recordings recording ON recording.id = claimed.recording_id
JOIN coaching_bookings booking ON booking.id = recording.booking_id
JOIN coaching_session_types session_type ON session_type.id = booking.session_type_id
ORDER BY recording.booking_id, recording.part_number, claimed.file_index
`

type ClaimPendingRecordingPartImportsRow struct {
	Status           CoachingRecordingImportStatus `json:"status"`
	GcsObjectName    pgtype.Text                   `json:"gcs_object_name"`
	MuxAssetID       pgtype.Text                   `json:"mux_asset_id"`
	MuxPlaybackID    pgtype.Text                   `json:"mux_playback_id"`
	VideoID          pgtype.UUID                   `json:"video_id"`
	Attempts         int32                         `json:"attempts"`
	LastAttemptAt    pgtype.Timestamptz            `json:"last_attempt_at"`
	ImportedAt       pgtype.Timestamptz            `json:"imported_at"`
	Error            pgtype.Text                   `json:"error"`
	CreatedAt        pgtype.Timestamptz            `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz            `json:"updated_at"`
	ID               pgtype.UUID                   `json:"id"`
	RecordingID      pgtype.UUID                   `json:"recording_id"`
	FileIndex        int32                         `json:"file_index"`
	BookingID        pgtype.UUID                   `json:"booking_id"`
	PartNumber       int32                         `json:"part_number"`
	RecordingAssetID pgtype.UUID                   `json:"recording_asset_id"`
	StudentID        string                        `json:"student_id"`
	GroupID          pgtype.UUID                   `json:"group_id"`
	ScheduledAt      pgtype.Timestamptz            `json:"scheduled_at"`
	DurationMinutes  int32                         `json:"duration_minutes"`
	SessionTypeName  string                        `json:"session_type_name"`
}

func (q *Queries) ClaimPendingRecordingPartImports(ctx context.Context, limit int32) ([]ClaimPendingRecordingPartImportsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingRecordingPartImports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingRecordingPartImportsRow
	for rows.Next() {
		var i ClaimPendingRecordingPartImportsRow
		if err := rows.Scan(
			&i.Status,
			&i.GcsObjectName,
			&i.MuxAssetID,
			&i.MuxPlaybackID,
			&i.VideoID,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.ImportedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.RecordingID,
			&i.FileIndex,
			&i.BookingID,
			&i.PartNumber,
			&i.RecordingAssetID,
			&i.StudentID,
			&i.GroupID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.SessionTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRecordingPartEmptySince = `-- name: ClearRecordingPartEmptySince :exec
UPDATE coaching_booking_recordings
SET empty_since_at = NULL, updated_at = NOW()
WHERE booking_id = $1 AND status IN ('starting', 'started')
`

func (q *Queries) ClearRecordingPartEmptySince(ctx context.Context, bookingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRecordingPartEmptySince, bookingID)
	return err
}

const countConflictingBookings = `-- name: CountConflictingBookings :one
SELECT COUNT(*) FROM coaching_bookings
WHERE expert_id = $1
  AND is_cancelled = false
  AND scheduled_at < $3
  AND scheduled_at + (duration_minutes * interval '1 minute') > $2
`

type CountConflictingBookingsParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

func (q *Queries) CountConflictingBookings(ctx context.Context, arg CountConflictingBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConflictingBookings, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFreshBookingParticipants = `-- name: CountFreshBookingParticipants :one
SELECT COUNT(*) FROM coaching_booking_presence
WHERE booking_id = $1
  AND last_seen_at >= NOW() - ($2::int * interval '1 second')
`

type CountFreshBookingParticipantsParams struct {
	BookingID    pgtype.UUID `json:"booking_id"`
	FreshSeconds int32       `json:"fresh_seconds"`
}

func (q *Queries) CountFreshBookingParticipants(ctx context.Context, arg CountFreshBookingParticipantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFreshBookingParticipants, arg.BookingID, arg.FreshSeconds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvailability = `-- name: CreateAvailability :one

INSERT INTO coaching_availability (expert_id, group_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type CreateAvailabilityParams struct {
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

// === Availability ===
func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.ExpertID,
		arg.GroupID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBlockedSlot = `-- name: CreateBlockedSlot :one

INSERT INTO coaching_blocked_slots (expert_id, blocked_date, start_time, end_time, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, blocked_date, start_time, end_time, reason, created_at
`

type CreateBlockedSlotParams struct {
	ExpertID    string      `json:"expert_id"`
	BlockedDate pgtype.Date `json:"blocked_date"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	Reason      pgtype.Text `json:"reason"`
}

// === Blocked Slots ===
func (q *Queries) CreateBlockedSlot(ctx context.Context, arg CreateBlockedSlotParams) (CoachingBlockedSlot, error) {
	row := q.db.QueryRow(ctx, createBlockedSlot,
		arg.ExpertID,
		arg.BlockedDate,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i CoachingBlockedSlot
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.BlockedDate,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO coaching_bookings (expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number
`

type CreateBookingParams struct {
	ExpertID        string             `json:"expert_id"`
	StudentID       string             `json:"student_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SessionTypeID   pgtype.UUID        `json:"session_type_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ExpertID,
		arg.StudentID,
		arg.GroupID,
		arg.SessionTypeID,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.Notes,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordingAssetID,
		&i.NextRecordingPartNumber,
	)
	return i, err
}

const createBookingReminder = `-- name: CreateBookingReminder :exec

INSERT INTO coaching_booking_reminders (booking_id, remind_at)
VALUES ($1, $2)
`

type CreateBookingReminderParams struct {
	BookingID pgtype.UUID        `json:"booking_id"`
	RemindAt  pgtype.Timestamptz `json:"remind_at"`
}

// === Booking Reminders ===
func (q *Queries) CreateBookingReminder(ctx context.Context, arg CreateBookingReminderParams) error {
	_, err := q.db.Exec(ctx, createBookingReminder, arg.BookingID, arg.RemindAt)
	return err
}

const createSessionType = `-- name: CreateSessionType :one

INSERT INTO coaching_session_types (expert_id, group_id, name, description, duration_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type CreateSessionTypeParams struct {
	ExpertID        string      `json:"expert_id"`
	GroupID         pgtype.UUID `json:"group_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
}

// === Session Types ===
func (q *Queries) CreateSessionType(ctx context.Context, arg CreateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, createSessionType,
		arg.ExpertID,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSessionType = `-- name: DeactivateSessionType :execrows
UPDATE coaching_session_types
SET is_active = false, updated_at = NOW()
WHERE id = $1 AND expert_id = $2
`

type DeactivateSessionTypeParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeactivateSessionType(ctx context.Context, arg DeactivateSessionTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSessionType, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAvailability = `-- name: DeleteAvailability :execrows
DELETE FROM coaching_availability WHERE id = $1 AND expert_id = $2
`

type DeleteAvailabilityParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailability, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBlockedSlot = `-- name: DeleteBlockedSlot :execrows
DELETE FROM coaching_blocked_slots WHERE id = $1 AND expert_id = $2
`

type DeleteBlockedSlotParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteBlockedSlot(ctx context.Context, arg DeleteBlockedSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedSlot, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureRecordingPartImport = `-- name: EnsureRecordingPartImport :one
INSERT INTO coaching_recording_imports (recording_id, file_index, gcs_object_name, status, error)
VALUES ($1, $2, $3, 'pending', NULL)
ON CONFLICT (recording_id, file_index) DO UPDATE SET
    gcs_object_name = EXCLUDED.gcs_object_name,
    status = CASE WHEN coaching_recording_imports.status = 'ready'
                  THEN coaching_recording_imports.status ELSE 'pending' END,
    error = NULL,
    updated_at = NOW()
RETURNING status, gcs_object_name, mux_asset_id, mux_playback_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at, id, recording_id, file_index
`

type EnsureRecordingPartImportParams struct {
	RecordingID   pgtype.UUID `json:"recording_id"`
	FileIndex     int32       `json:"file_index"`
	GcsObjectName pgtype.Text `json:"gcs_object_name"`
}

func (q *Queries) EnsureRecordingPartImport(ctx context.Context, arg EnsureRecordingPartImportParams) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, ensureRecordingPartImport, arg.RecordingID, arg.FileIndex, arg.GcsObjectName)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.RecordingID,
		&i.FileIndex,
	)
	return i, err
}

const exchangeRecordingRendererCapability = `-- name: ExchangeRecordingRendererCapability :one
SELECT
    recording.id AS recording_id,
    recording.booking_id,
    recording.provider_uid,
    booking.student_id,
    booking.expert_id,
    booking.scheduled_at,
    booking.duration_minutes
FROM coaching_booking_recordings recording
JOIN coaching_bookings booking ON booking.id = recording.booking_id
WHERE recording.renderer_token_hash = $1
  AND recording.renderer_token_expires_at > NOW()
  AND recording.status IN ('starting', 'started')
`

type ExchangeRecordingRendererCapabilityRow struct {
	RecordingID     pgtype.UUID        `json:"recording_id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	ProviderUid     pgtype.Text        `json:"provider_uid"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
}

func (q *Queries) ExchangeRecordingRendererCapability(ctx context.Context, rendererTokenHash []byte) (ExchangeRecordingRendererCapabilityRow, error) {
	row := q.db.QueryRow(ctx, exchangeRecordingRendererCapability, rendererTokenHash)
	var i ExchangeRecordingRendererCapabilityRow
	err := row.Scan(
		&i.RecordingID,
		&i.BookingID,
		&i.ProviderUid,
		&i.StudentID,
		&i.ExpertID,
		&i.ScheduledAt,
		&i.DurationMinutes,
	)
	return i, err
}

const getActiveRecordingPart = `-- name: GetActiveRecordingPart :one
SELECT booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at FROM coaching_booking_recordings
WHERE booking_id = $1 AND status IN ('starting', 'started', 'stopping')
ORDER BY part_number DESC
LIMIT 1
`

func (q *Queries) GetActiveRecordingPart(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, getActiveRecordingPart, bookingID)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ProviderResourceID,
		&i.ProviderRecordingID,
		&i.ProviderUid,
		&i.OutputPrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.PartNumber,
		&i.Provider,
		&i.RendererTokenHash,
		&i.RendererTokenExpiresAt,
		&i.EmptySinceAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number FROM coaching_bookings WHERE id = $1 AND (expert_id = $2 OR student_id = $2)
`

type GetBookingParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, getBooking, arg.ID, arg.ExpertID)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordingAssetID,
		&i.NextRecordingPartNumber,
	)
	return i, err
}

const getBookingForRecordingAssetUpdate = `-- name: GetBookingForRecordingAssetUpdate :one
SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number FROM coaching_bookings WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBookingForRecordingAssetUpdate(ctx context.Context, id pgtype.UUID) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, getBookingForRecordingAssetUpdate, id)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordingAssetID,
		&i.NextRecordingPartNumber,
	)
	return i, err
}

const getSessionType = `-- name: GetSessionType :one
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types WHERE id = $1 AND group_id = $2
`

type GetSessionTypeParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetSessionType(ctx context.Context, arg GetSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, getSessionType, arg.ID, arg.GroupID)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTimezone = `-- name: GetUserTimezone :one

SELECT timezone FROM user_preferences WHERE user_id = $1
`

// === Timezone ===
func (q *Queries) GetUserTimezone(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserTimezone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const listActiveExpertsInGroup = `-- name: ListActiveExpertsInGroup :many
SELECT DISTINCT expert_id FROM coaching_availability
WHERE group_id = $1 AND is_active = true
`

func (q *Queries) ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveExpertsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var expert_id string
		if err := rows.Scan(&expert_id); err != nil {
			return nil, err
		}
		items = append(items, expert_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMyBookings = `-- name: ListAllMyBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cb.recording_asset_id, cb.next_recording_part_number, cst.name AS session_type_name,
       COALESCE(latest.recording_status, '')::varchar AS recording_status,
       latest.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN LATERAL (
    SELECT COALESCE(recording_import.status::text, recording.status::text) AS recording_status,
           recording_import.video_id
    FROM coaching_booking_recordings recording
    LEFT JOIN coaching_recording_imports recording_import ON recording_import.recording_id = recording.id
    WHERE recording.booking_id = cb.id
    ORDER BY recording.part_number DESC, recording_import.file_index DESC NULLS LAST
    LIMIT 1
) latest ON true
WHERE cb.expert_id = $1 OR cb.student_id = $1
ORDER BY cb.scheduled_at ASC
`

type ListAllMyBookingsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	ExpertID                string             `json:"expert_id"`
	StudentID               string             `json:"student_id"`
	GroupID                 pgtype.UUID        `json:"group_id"`
	SessionTypeID           pgtype.UUID        `json:"session_type_id"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes         int32              `json:"duration_minutes"`
	IsCancelled             bool               `json:"is_cancelled"`
	CancellationReason      pgtype.Text        `json:"cancellation_reason"`
	CancelledBy             pgtype.Text        `json:"cancelled_by"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	RecordingAssetID        pgtype.UUID        `json:"recording_asset_id"`
	NextRecordingPartNumber int32              `json:"next_recording_part_number"`
	SessionTypeName         string             `json:"session_type_name"`
	RecordingStatus         string             `json:"recording_status"`
	RecordingVideoID        pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListAllMyBookings(ctx context.Context, expertID string) ([]ListAllMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllMyBookings, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMyBookingsRow
	for rows.Next() {
		var i ListAllMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordingAssetID,
			&i.NextRecordingPartNumber,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByExpertGroup = `-- name: ListAvailabilityByExpertGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY day_of_week, start_time
`

type ListAvailabilityByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListAvailabilityByExpertGroup(ctx context.Context, arg ListAvailabilityByExpertGroupParams) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByExpertGroupDay = `-- name: ListAvailabilityByExpertGroupDay :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE expert_id = $1 AND group_id = $2 AND day_of_week = $3 AND is_active = true
ORDER BY start_time
`

type ListAvailabilityByExpertGroupDayParams struct {
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int16       `json:"day_of_week"`
}

func (q *Queries) ListAvailabilityByExpertGroupDay(ctx context.Context, arg ListAvailabilityByExpertGroupDayParams) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByExpertGroupDay, arg.ExpertID, arg.GroupID, arg.DayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByGroup = `-- name: ListAvailabilityByGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, day_of_week, start_time
`

func (q *Queries) ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedSlots = `-- name: ListBlockedSlots :many
SELECT id, expert_id, blocked_date, start_time, end_time, reason, created_at FROM coaching_blocked_slots
WHERE expert_id = $1 AND blocked_date >= $2 AND blocked_date <= $3
ORDER BY blocked_date, start_time
`

type ListBlockedSlotsParams struct {
	ExpertID string      `json:"expert_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListBlockedSlots(ctx context.Context, arg ListBlockedSlotsParams) ([]CoachingBlockedSlot, error) {
	rows, err := q.db.Query(ctx, listBlockedSlots, arg.ExpertID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBlockedSlot
	for rows.Next() {
		var i CoachingBlockedSlot
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.BlockedDate,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByExpertInRange = `-- name: ListBookingsByExpertInRange :many

SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at, recording_asset_id, next_recording_part_number FROM coaching_bookings
WHERE expert_id = $1
  AND scheduled_at >= $2
  AND scheduled_at < $3
  AND is_cancelled = false
ORDER BY scheduled_at
`

type ListBookingsByExpertInRangeParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

// === Bookings ===
func (q *Queries) ListBookingsByExpertInRange(ctx context.Context, arg ListBookingsByExpertInRangeParams) ([]CoachingBooking, error) {
	rows, err := q.db.Query(ctx, listBookingsByExpertInRange, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBooking
	for rows.Next() {
		var i CoachingBooking
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordingAssetID,
			&i.NextRecordingPartNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupBookings = `-- name: ListGroupBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cb.recording_asset_id, cb.next_recording_part_number, cst.name AS session_type_name,
       COALESCE(latest.recording_status, '')::varchar AS recording_status,
       latest.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN LATERAL (
    SELECT COALESCE(recording_import.status::text, recording.status::text) AS recording_status,
           recording_import.video_id
    FROM coaching_booking_recordings recording
    LEFT JOIN coaching_recording_imports recording_import ON recording_import.recording_id = recording.id
    WHERE recording.booking_id = cb.id
    ORDER BY recording.part_number DESC, recording_import.file_index DESC NULLS LAST
    LIMIT 1
) latest ON true
WHERE cb.group_id = $1
ORDER BY cb.scheduled_at
`

type ListGroupBookingsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	ExpertID                string             `json:"expert_id"`
	StudentID               string             `json:"student_id"`
	GroupID                 pgtype.UUID        `json:"group_id"`
	SessionTypeID           pgtype.UUID        `json:"session_type_id"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes         int32              `json:"duration_minutes"`
	IsCancelled             bool               `json:"is_cancelled"`
	CancellationReason      pgtype.Text        `json:"cancellation_reason"`
	CancelledBy             pgtype.Text        `json:"cancelled_by"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	RecordingAssetID        pgtype.UUID        `json:"recording_asset_id"`
	NextRecordingPartNumber int32              `json:"next_recording_part_number"`
	SessionTypeName         string             `json:"session_type_name"`
	RecordingStatus         string             `json:"recording_status"`
	RecordingVideoID        pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBookingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupBookings, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupBookingsRow
	for rows.Next() {
		var i ListGroupBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordingAssetID,
			&i.NextRecordingPartNumber,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookings = `-- name: ListMyBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cb.recording_asset_id, cb.next_recording_part_number, cst.name AS session_type_name,
       COALESCE(latest.recording_status, '')::varchar AS recording_status,
       latest.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN LATERAL (
    SELECT COALESCE(recording_import.status::text, recording.status::text) AS recording_status,
           recording_import.video_id
    FROM coaching_booking_recordings recording
    LEFT JOIN coaching_recording_imports recording_import ON recording_import.recording_id = recording.id
    WHERE recording.booking_id = cb.id
    ORDER BY recording.part_number DESC, recording_import.file_index DESC NULLS LAST
    LIMIT 1
) latest ON true
WHERE (cb.expert_id = $1 OR cb.student_id = $1) AND cb.group_id = $2
ORDER BY cb.scheduled_at DESC
`

type ListMyBookingsParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

type ListMyBookingsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	ExpertID                string             `json:"expert_id"`
	StudentID               string             `json:"student_id"`
	GroupID                 pgtype.UUID        `json:"group_id"`
	SessionTypeID           pgtype.UUID        `json:"session_type_id"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes         int32              `json:"duration_minutes"`
	IsCancelled             bool               `json:"is_cancelled"`
	CancellationReason      pgtype.Text        `json:"cancellation_reason"`
	CancelledBy             pgtype.Text        `json:"cancelled_by"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	RecordingAssetID        pgtype.UUID        `json:"recording_asset_id"`
	NextRecordingPartNumber int32              `json:"next_recording_part_number"`
	SessionTypeName         string             `json:"session_type_name"`
	RecordingStatus         string             `json:"recording_status"`
	RecordingVideoID        pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMyBookings, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyBookingsRow
	for rows.Next() {
		var i ListMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordingAssetID,
			&i.NextRecordingPartNumber,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReminders = `-- name: ListPendingReminders :many
SELECT r.id, r.booking_id, r.remind_at,
       b.expert_id, b.student_id, b.group_id, b.scheduled_at, b.duration_minutes, b.is_cancelled
FROM coaching_booking_reminders r
JOIN coaching_bookings b ON b.id = r.booking_id
WHERE r.sent_at IS NULL
  AND r.remind_at <= NOW()
ORDER BY r.remind_at
LIMIT 100
`

type ListPendingRemindersRow struct {
	ID              pgtype.UUID        `json:"id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	RemindAt        pgtype.Timestamptz `json:"remind_at"`
	ExpertID        string             `json:"expert_id"`
	StudentID       string             `json:"student_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsCancelled     bool               `json:"is_cancelled"`
}

func (q *Queries) ListPendingReminders(ctx context.Context) ([]ListPendingRemindersRow, error) {
	rows, err := q.db.Query(ctx, listPendingReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRemindersRow
	for rows.Next() {
		var i ListPendingRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.RemindAt,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingPartsReadyToStop = `-- name: ListRecordingPartsReadyToStop :many
SELECT recording.booking_id, recording.status, recording.provider_resource_id, recording.provider_recording_id, recording.provider_uid, recording.output_prefix, recording.started_at, recording.stopped_at, recording.error, recording.created_at, recording.updated_at, recording.id, recording.part_number, recording.provider, recording.renderer_token_hash, recording.renderer_token_expires_at, recording.empty_since_at
FROM coaching_booking_recordings recording
JOIN coaching_bookings booking ON booking.id = recording.booking_id
WHERE recording.status IN ('starting', 'started', 'stopping')
  AND (
      recording.empty_since_at <= NOW() - ($1::int * interval '1 second')
      OR booking.scheduled_at + (booking.duration_minutes * interval '1 minute')
         + ($2::int * interval '1 second') <= NOW()
      OR (recording.status = 'starting' AND recording.updated_at <= NOW() - interval '1 minute')
  )
ORDER BY recording.updated_at
LIMIT $3
`

type ListRecordingPartsReadyToStopParams struct {
	EmptyGraceSeconds int32 `json:"empty_grace_seconds"`
	EndGraceSeconds   int32 `json:"end_grace_seconds"`
	LimitCount        int32 `json:"limit_count"`
}

func (q *Queries) ListRecordingPartsReadyToStop(ctx context.Context, arg ListRecordingPartsReadyToStopParams) ([]CoachingBookingRecording, error) {
	rows, err := q.db.Query(ctx, listRecordingPartsReadyToStop, arg.EmptyGraceSeconds, arg.EndGraceSeconds, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBookingRecording
	for rows.Next() {
		var i CoachingBookingRecording
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.ProviderResourceID,
			&i.ProviderRecordingID,
			&i.ProviderUid,
			&i.OutputPrefix,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.PartNumber,
			&i.Provider,
			&i.RendererTokenHash,
			&i.RendererTokenExpiresAt,
			&i.EmptySinceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByExpertGroup = `-- name: ListSessionTypesByExpertGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY duration_minutes
`

type ListSessionTypesByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListSessionTypesByExpertGroup(ctx context.Context, arg ListSessionTypesByExpertGroupParams) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByGroup = `-- name: ListSessionTypesByGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, duration_minutes
`

func (q *Queries) ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoppedRecordingPartsForDiscovery = `-- name: ListStoppedRecordingPartsForDiscovery :many
SELECT booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at FROM coaching_booking_recordings
WHERE status = 'stopped'
  AND stopped_at >= NOW() - interval '7 days'
ORDER BY stopped_at DESC
LIMIT $1
`

func (q *Queries) ListStoppedRecordingPartsForDiscovery(ctx context.Context, limit int32) ([]CoachingBookingRecording, error) {
	rows, err := q.db.Query(ctx, listStoppedRecordingPartsForDiscovery, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBookingRecording
	for rows.Next() {
		var i CoachingBookingRecording
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.ProviderResourceID,
			&i.ProviderRecordingID,
			&i.ProviderUid,
			&i.OutputPrefix,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.PartNumber,
			&i.Provider,
			&i.RendererTokenHash,
			&i.RendererTokenExpiresAt,
			&i.EmptySinceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmptyRecordingPartsWithoutFreshHumans = `-- name: MarkEmptyRecordingPartsWithoutFreshHumans :execrows
UPDATE coaching_booking_recordings recording
SET empty_since_at = COALESCE(empty_since_at, NOW()), updated_at = NOW()
WHERE recording.status = 'started'
  AND NOT EXISTS (
      SELECT 1 FROM coaching_booking_presence presence
      WHERE presence.booking_id = recording.booking_id
        AND presence.last_seen_at >= NOW() - ($1::int * interval '1 second')
  )
`

func (q *Queries) MarkEmptyRecordingPartsWithoutFreshHumans(ctx context.Context, freshSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, markEmptyRecordingPartsWithoutFreshHumans, freshSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRecordingPartFailed = `-- name: MarkRecordingPartFailed :exec
UPDATE coaching_booking_recordings
SET status = 'failed', stopped_at = NOW(), renderer_token_hash = NULL,
    renderer_token_expires_at = NULL, error = $2, updated_at = NOW()
WHERE id = $1
`

type MarkRecordingPartFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) MarkRecordingPartFailed(ctx context.Context, arg MarkRecordingPartFailedParams) error {
	_, err := q.db.Exec(ctx, markRecordingPartFailed, arg.ID, arg.Error)
	return err
}

const markRecordingPartImportFailed = `-- name: MarkRecordingPartImportFailed :exec
UPDATE coaching_recording_imports
SET status = 'failed', error = $2, updated_at = NOW()
WHERE id = $1
`

type MarkRecordingPartImportFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) MarkRecordingPartImportFailed(ctx context.Context, arg MarkRecordingPartImportFailedParams) error {
	_, err := q.db.Exec(ctx, markRecordingPartImportFailed, arg.ID, arg.Error)
	return err
}

const markRecordingPartImportMuxCreated = `-- name: MarkRecordingPartImportMuxCreated :one
UPDATE coaching_recording_imports
SET status = 'processing', mux_asset_id = $2, mux_playback_id = $3,
    error = NULL, updated_at = NOW()
WHERE id = $1
RETURNING status, gcs_object_name, mux_asset_id, mux_playback_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at, id, recording_id, file_index
`

type MarkRecordingPartImportMuxCreatedParams struct {
	ID            pgtype.UUID `json:"id"`
	MuxAssetID    pgtype.Text `json:"mux_asset_id"`
	MuxPlaybackID pgtype.Text `json:"mux_playback_id"`
}

func (q *Queries) MarkRecordingPartImportMuxCreated(ctx context.Context, arg MarkRecordingPartImportMuxCreatedParams) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, markRecordingPartImportMuxCreated, arg.ID, arg.MuxAssetID, arg.MuxPlaybackID)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.RecordingID,
		&i.FileIndex,
	)
	return i, err
}

const markRecordingPartImportReady = `-- name: MarkRecordingPartImportReady :one
UPDATE coaching_recording_imports
SET status = 'ready', mux_asset_id = $2, mux_playback_id = $3,
    video_id = $4, imported_at = NOW(), error = NULL, updated_at = NOW()
WHERE id = $1
RETURNING status, gcs_object_name, mux_asset_id, mux_playback_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at, id, recording_id, file_index
`

type MarkRecordingPartImportReadyParams struct {
	ID            pgtype.UUID `json:"id"`
	MuxAssetID    pgtype.Text `json:"mux_asset_id"`
	MuxPlaybackID pgtype.Text `json:"mux_playback_id"`
	VideoID       pgtype.UUID `json:"video_id"`
}

func (q *Queries) MarkRecordingPartImportReady(ctx context.Context, arg MarkRecordingPartImportReadyParams) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, markRecordingPartImportReady,
		arg.ID,
		arg.MuxAssetID,
		arg.MuxPlaybackID,
		arg.VideoID,
	)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.RecordingID,
		&i.FileIndex,
	)
	return i, err
}

const markRecordingPartStopped = `-- name: MarkRecordingPartStopped :one
UPDATE coaching_booking_recordings
SET status = 'stopped', stopped_at = NOW(), empty_since_at = NULL,
    renderer_token_hash = NULL, renderer_token_expires_at = NULL,
    error = NULL, updated_at = NOW()
WHERE id = $1
RETURNING booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at
`

func (q *Queries) MarkRecordingPartStopped(ctx context.Context, id pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, markRecordingPartStopped, id)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ProviderResourceID,
		&i.ProviderRecordingID,
		&i.ProviderUid,
		&i.OutputPrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.PartNumber,
		&i.Provider,
		&i.RendererTokenHash,
		&i.RendererTokenExpiresAt,
		&i.EmptySinceAt,
	)
	return i, err
}

const markRecordingPartStopping = `-- name: MarkRecordingPartStopping :one
UPDATE coaching_booking_recordings
SET status = 'stopping', updated_at = NOW()
WHERE id = $1 AND status IN ('started', 'stopping')
RETURNING booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at
`

func (q *Queries) MarkRecordingPartStopping(ctx context.Context, id pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, markRecordingPartStopping, id)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ProviderResourceID,
		&i.ProviderRecordingID,
		&i.ProviderUid,
		&i.OutputPrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.PartNumber,
		&i.Provider,
		&i.RendererTokenHash,
		&i.RendererTokenExpiresAt,
		&i.EmptySinceAt,
	)
	return i, err
}

const markRecordingRendererReady = `-- name: MarkRecordingRendererReady :one
UPDATE coaching_booking_recordings
SET status = 'started', updated_at = NOW()
WHERE renderer_token_hash = $1
  AND renderer_token_expires_at > NOW()
  AND status IN ('starting', 'started')
RETURNING id
`

func (q *Queries) MarkRecordingRendererReady(ctx context.Context, rendererTokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markRecordingRendererReady, rendererTokenHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE coaching_booking_reminders SET sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}

const refreshBookingPresence = `-- name: RefreshBookingPresence :one
UPDATE coaching_booking_presence
SET last_seen_at = NOW()
WHERE booking_id = $1 AND participant_role = $2 AND connection_id = $3
RETURNING booking_id, participant_role, connection_id, last_seen_at
`

type RefreshBookingPresenceParams struct {
	BookingID       pgtype.UUID `json:"booking_id"`
	ParticipantRole string      `json:"participant_role"`
	ConnectionID    pgtype.UUID `json:"connection_id"`
}

func (q *Queries) RefreshBookingPresence(ctx context.Context, arg RefreshBookingPresenceParams) (CoachingBookingPresence, error) {
	row := q.db.QueryRow(ctx, refreshBookingPresence, arg.BookingID, arg.ParticipantRole, arg.ConnectionID)
	var i CoachingBookingPresence
	err := row.Scan(
		&i.BookingID,
		&i.ParticipantRole,
		&i.ConnectionID,
		&i.LastSeenAt,
	)
	return i, err
}

const removeBookingPresence = `-- name: RemoveBookingPresence :execrows
DELETE FROM coaching_booking_presence
WHERE booking_id = $1 AND participant_role = $2 AND connection_id = $3
`

type RemoveBookingPresenceParams struct {
	BookingID       pgtype.UUID `json:"booking_id"`
	ParticipantRole string      `json:"participant_role"`
	ConnectionID    pgtype.UUID `json:"connection_id"`
}

func (q *Queries) RemoveBookingPresence(ctx context.Context, arg RemoveBookingPresenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeBookingPresence, arg.BookingID, arg.ParticipantRole, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRecordingPartProviderStarted = `-- name: SetRecordingPartProviderStarted :one
UPDATE coaching_booking_recordings
SET provider_resource_id = $2,
    provider_recording_id = $3,
    provider_uid = $4,
    output_prefix = $5,
    started_at = COALESCE(started_at, NOW()),
    empty_since_at = NULL,
    error = NULL,
    updated_at = NOW()
WHERE id = $1 AND status IN ('starting', 'started')
RETURNING booking_id, status, provider_resource_id, provider_recording_id, provider_uid, output_prefix, started_at, stopped_at, error, created_at, updated_at, id, part_number, provider, renderer_token_hash, renderer_token_expires_at, empty_since_at
`

type SetRecordingPartProviderStartedParams struct {
	ID                  pgtype.UUID `json:"id"`
	ProviderResourceID  pgtype.Text `json:"provider_resource_id"`
	ProviderRecordingID pgtype.Text `json:"provider_recording_id"`
	ProviderUid         pgtype.Text `json:"provider_uid"`
	OutputPrefix        []string    `json:"output_prefix"`
}

func (q *Queries) SetRecordingPartProviderStarted(ctx context.Context, arg SetRecordingPartProviderStartedParams) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, setRecordingPartProviderStarted,
		arg.ID,
		arg.ProviderResourceID,
		arg.ProviderRecordingID,
		arg.ProviderUid,
		arg.OutputPrefix,
	)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ProviderResourceID,
		&i.ProviderRecordingID,
		&i.ProviderUid,
		&i.OutputPrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.PartNumber,
		&i.Provider,
		&i.RendererTokenHash,
		&i.RendererTokenExpiresAt,
		&i.EmptySinceAt,
	)
	return i, err
}

const updateAvailability = `-- name: UpdateAvailability :one
UPDATE coaching_availability
SET day_of_week = $2, start_time = $3, end_time = $4, updated_at = NOW()
WHERE id = $1 AND expert_id = $5 AND group_id = $6
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type UpdateAvailabilityParams struct {
	ID        pgtype.UUID `json:"id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
}

func (q *Queries) UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, updateAvailability,
		arg.ID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.ExpertID,
		arg.GroupID,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionType = `-- name: UpdateSessionType :one
UPDATE coaching_session_types
SET name = $2, description = $3, duration_minutes = $4, updated_at = NOW()
WHERE id = $1 AND expert_id = $5 AND group_id = $6
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type UpdateSessionTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
	ExpertID        string      `json:"expert_id"`
	GroupID         pgtype.UUID `json:"group_id"`
}

func (q *Queries) UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, updateSessionType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.ExpertID,
		arg.GroupID,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBookingPresence = `-- name: UpsertBookingPresence :one
INSERT INTO coaching_booking_presence (booking_id, participant_role, connection_id, last_seen_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (booking_id, participant_role) DO UPDATE SET
    connection_id = EXCLUDED.connection_id,
    last_seen_at = NOW()
RETURNING booking_id, participant_role, connection_id, last_seen_at
`

type UpsertBookingPresenceParams struct {
	BookingID       pgtype.UUID `json:"booking_id"`
	ParticipantRole string      `json:"participant_role"`
	ConnectionID    pgtype.UUID `json:"connection_id"`
}

func (q *Queries) UpsertBookingPresence(ctx context.Context, arg UpsertBookingPresenceParams) (CoachingBookingPresence, error) {
	row := q.db.QueryRow(ctx, upsertBookingPresence, arg.BookingID, arg.ParticipantRole, arg.ConnectionID)
	var i CoachingBookingPresence
	err := row.Scan(
		&i.BookingID,
		&i.ParticipantRole,
		&i.ConnectionID,
		&i.LastSeenAt,
	)
	return i, err
}
