// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE coaching_bookings
SET is_cancelled = true,
    cancellation_reason = $2,
    cancelled_by = $3,
    updated_at = NOW()
WHERE id = $1 AND (expert_id = $4 OR student_id = $4)
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at
`

type CancelBookingParams struct {
	ID                 pgtype.UUID `json:"id"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
	CancelledBy        pgtype.Text `json:"cancelled_by"`
	ExpertID           string      `json:"expert_id"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, cancelBooking,
		arg.ID,
		arg.CancellationReason,
		arg.CancelledBy,
		arg.ExpertID,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countConflictingBookings = `-- name: CountConflictingBookings :one
SELECT COUNT(*) FROM coaching_bookings
WHERE expert_id = $1
  AND is_cancelled = false
  AND scheduled_at < $3
  AND scheduled_at + (duration_minutes * interval '1 minute') > $2
`

type CountConflictingBookingsParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

func (q *Queries) CountConflictingBookings(ctx context.Context, arg CountConflictingBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConflictingBookings, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvailability = `-- name: CreateAvailability :one

INSERT INTO coaching_availability (expert_id, group_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type CreateAvailabilityParams struct {
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

// === Availability ===
func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.ExpertID,
		arg.GroupID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBlockedSlot = `-- name: CreateBlockedSlot :one

INSERT INTO coaching_blocked_slots (expert_id, blocked_date, start_time, end_time, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, blocked_date, start_time, end_time, reason, created_at
`

type CreateBlockedSlotParams struct {
	ExpertID    string      `json:"expert_id"`
	BlockedDate pgtype.Date `json:"blocked_date"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	Reason      pgtype.Text `json:"reason"`
}

// === Blocked Slots ===
func (q *Queries) CreateBlockedSlot(ctx context.Context, arg CreateBlockedSlotParams) (CoachingBlockedSlot, error) {
	row := q.db.QueryRow(ctx, createBlockedSlot,
		arg.ExpertID,
		arg.BlockedDate,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i CoachingBlockedSlot
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.BlockedDate,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO coaching_bookings (expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at
`

type CreateBookingParams struct {
	ExpertID        string             `json:"expert_id"`
	StudentID       string             `json:"student_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SessionTypeID   pgtype.UUID        `json:"session_type_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ExpertID,
		arg.StudentID,
		arg.GroupID,
		arg.SessionTypeID,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.Notes,
	)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingReminder = `-- name: CreateBookingReminder :exec

INSERT INTO coaching_booking_reminders (booking_id, remind_at)
VALUES ($1, $2)
`

type CreateBookingReminderParams struct {
	BookingID pgtype.UUID        `json:"booking_id"`
	RemindAt  pgtype.Timestamptz `json:"remind_at"`
}

// === Booking Reminders ===
func (q *Queries) CreateBookingReminder(ctx context.Context, arg CreateBookingReminderParams) error {
	_, err := q.db.Exec(ctx, createBookingReminder, arg.BookingID, arg.RemindAt)
	return err
}

const createMissingRecordingImports = `-- name: CreateMissingRecordingImports :execrows
INSERT INTO coaching_recording_imports (booking_id, status)
SELECT r.booking_id, 'pending'
FROM coaching_booking_recordings r
LEFT JOIN coaching_recording_imports ri ON ri.booking_id = r.booking_id
WHERE r.status = 'stopped'
  AND ri.booking_id IS NULL
ON CONFLICT (booking_id) DO NOTHING
`

func (q *Queries) CreateMissingRecordingImports(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, createMissingRecordingImports)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSessionType = `-- name: CreateSessionType :one

INSERT INTO coaching_session_types (expert_id, group_id, name, description, duration_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type CreateSessionTypeParams struct {
	ExpertID        string      `json:"expert_id"`
	GroupID         pgtype.UUID `json:"group_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
}

// === Session Types ===
func (q *Queries) CreateSessionType(ctx context.Context, arg CreateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, createSessionType,
		arg.ExpertID,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSessionType = `-- name: DeactivateSessionType :execrows
UPDATE coaching_session_types
SET is_active = false, updated_at = NOW()
WHERE id = $1 AND expert_id = $2
`

type DeactivateSessionTypeParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeactivateSessionType(ctx context.Context, arg DeactivateSessionTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSessionType, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAvailability = `-- name: DeleteAvailability :execrows
DELETE FROM coaching_availability WHERE id = $1 AND expert_id = $2
`

type DeleteAvailabilityParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailability, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBlockedSlot = `-- name: DeleteBlockedSlot :execrows
DELETE FROM coaching_blocked_slots WHERE id = $1 AND expert_id = $2
`

type DeleteBlockedSlotParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) DeleteBlockedSlot(ctx context.Context, arg DeleteBlockedSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedSlot, arg.ID, arg.ExpertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureRecordingImportPending = `-- name: EnsureRecordingImportPending :one
INSERT INTO coaching_recording_imports (booking_id, status, error)
VALUES ($1, 'pending', NULL)
ON CONFLICT (booking_id) DO UPDATE SET
    status = CASE
        WHEN coaching_recording_imports.status = 'ready' THEN coaching_recording_imports.status
        ELSE 'pending'
    END,
    error = NULL,
    updated_at = NOW()
RETURNING booking_id, status, gcs_object_name, mux_asset_id, mux_playback_id, asset_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at
`

func (q *Queries) EnsureRecordingImportPending(ctx context.Context, bookingID pgtype.UUID) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, ensureRecordingImportPending, bookingID)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.AssetID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at FROM coaching_bookings WHERE id = $1 AND (expert_id = $2 OR student_id = $2)
`

type GetBookingParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, getBooking, arg.ID, arg.ExpertID)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingForRecordingUpdate = `-- name: GetBookingForRecordingUpdate :one
SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at FROM coaching_bookings
WHERE id = $1 AND (expert_id = $2 OR student_id = $2)
FOR UPDATE
`

type GetBookingForRecordingUpdateParams struct {
	ID       pgtype.UUID `json:"id"`
	ExpertID string      `json:"expert_id"`
}

func (q *Queries) GetBookingForRecordingUpdate(ctx context.Context, arg GetBookingForRecordingUpdateParams) (CoachingBooking, error) {
	row := q.db.QueryRow(ctx, getBookingForRecordingUpdate, arg.ID, arg.ExpertID)
	var i CoachingBooking
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.StudentID,
		&i.GroupID,
		&i.SessionTypeID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsCancelled,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingRecording = `-- name: GetBookingRecording :one
SELECT booking_id, status, resource_id, sid, uid, file_prefix, started_at, stopped_at, error, created_at, updated_at FROM coaching_booking_recordings
WHERE booking_id = $1
`

func (q *Queries) GetBookingRecording(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, getBookingRecording, bookingID)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ResourceID,
		&i.Sid,
		&i.Uid,
		&i.FilePrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingRecordingForUpdate = `-- name: GetBookingRecordingForUpdate :one
SELECT booking_id, status, resource_id, sid, uid, file_prefix, started_at, stopped_at, error, created_at, updated_at FROM coaching_booking_recordings
WHERE booking_id = $1
FOR UPDATE
`

func (q *Queries) GetBookingRecordingForUpdate(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, getBookingRecordingForUpdate, bookingID)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ResourceID,
		&i.Sid,
		&i.Uid,
		&i.FilePrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionType = `-- name: GetSessionType :one
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types WHERE id = $1 AND group_id = $2
`

type GetSessionTypeParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetSessionType(ctx context.Context, arg GetSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, getSessionType, arg.ID, arg.GroupID)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTimezone = `-- name: GetUserTimezone :one

SELECT timezone FROM user_preferences WHERE user_id = $1
`

// === Timezone ===
func (q *Queries) GetUserTimezone(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserTimezone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const listActiveExpertsInGroup = `-- name: ListActiveExpertsInGroup :many
SELECT DISTINCT expert_id FROM coaching_availability
WHERE group_id = $1 AND is_active = true
`

func (q *Queries) ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveExpertsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var expert_id string
		if err := rows.Scan(&expert_id); err != nil {
			return nil, err
		}
		items = append(items, expert_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMyBookings = `-- name: ListAllMyBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cst.name AS session_type_name,
       COALESCE(ri.status::text, r.status::text, '')::varchar AS recording_status,
       ri.asset_id AS recording_asset_id,
       ri.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN coaching_booking_recordings r ON r.booking_id = cb.id
LEFT JOIN coaching_recording_imports ri ON ri.booking_id = cb.id
WHERE cb.expert_id = $1 OR cb.student_id = $1
ORDER BY cb.scheduled_at ASC
`

type ListAllMyBookingsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ExpertID           string             `json:"expert_id"`
	StudentID          string             `json:"student_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	SessionTypeID      pgtype.UUID        `json:"session_type_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes    int32              `json:"duration_minutes"`
	IsCancelled        bool               `json:"is_cancelled"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SessionTypeName    string             `json:"session_type_name"`
	RecordingStatus    string             `json:"recording_status"`
	RecordingAssetID   pgtype.UUID        `json:"recording_asset_id"`
	RecordingVideoID   pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListAllMyBookings(ctx context.Context, expertID string) ([]ListAllMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllMyBookings, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMyBookingsRow
	for rows.Next() {
		var i ListAllMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingAssetID,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByExpertGroup = `-- name: ListAvailabilityByExpertGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY day_of_week, start_time
`

type ListAvailabilityByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListAvailabilityByExpertGroup(ctx context.Context, arg ListAvailabilityByExpertGroupParams) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByExpertGroupDay = `-- name: ListAvailabilityByExpertGroupDay :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE expert_id = $1 AND group_id = $2 AND day_of_week = $3 AND is_active = true
ORDER BY start_time
`

type ListAvailabilityByExpertGroupDayParams struct {
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int16       `json:"day_of_week"`
}

func (q *Queries) ListAvailabilityByExpertGroupDay(ctx context.Context, arg ListAvailabilityByExpertGroupDayParams) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByExpertGroupDay, arg.ExpertID, arg.GroupID, arg.DayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByGroup = `-- name: ListAvailabilityByGroup :many
SELECT id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at FROM coaching_availability
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, day_of_week, start_time
`

func (q *Queries) ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingAvailability
	for rows.Next() {
		var i CoachingAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedSlots = `-- name: ListBlockedSlots :many
SELECT id, expert_id, blocked_date, start_time, end_time, reason, created_at FROM coaching_blocked_slots
WHERE expert_id = $1 AND blocked_date >= $2 AND blocked_date <= $3
ORDER BY blocked_date, start_time
`

type ListBlockedSlotsParams struct {
	ExpertID string      `json:"expert_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListBlockedSlots(ctx context.Context, arg ListBlockedSlotsParams) ([]CoachingBlockedSlot, error) {
	rows, err := q.db.Query(ctx, listBlockedSlots, arg.ExpertID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBlockedSlot
	for rows.Next() {
		var i CoachingBlockedSlot
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.BlockedDate,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByExpertInRange = `-- name: ListBookingsByExpertInRange :many

SELECT id, expert_id, student_id, group_id, session_type_id, scheduled_at, duration_minutes, is_cancelled, cancellation_reason, cancelled_by, notes, created_at, updated_at FROM coaching_bookings
WHERE expert_id = $1
  AND scheduled_at >= $2
  AND scheduled_at < $3
  AND is_cancelled = false
ORDER BY scheduled_at
`

type ListBookingsByExpertInRangeParams struct {
	ExpertID      string             `json:"expert_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

// === Bookings ===
func (q *Queries) ListBookingsByExpertInRange(ctx context.Context, arg ListBookingsByExpertInRangeParams) ([]CoachingBooking, error) {
	rows, err := q.db.Query(ctx, listBookingsByExpertInRange, arg.ExpertID, arg.ScheduledAt, arg.ScheduledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBooking
	for rows.Next() {
		var i CoachingBooking
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupBookings = `-- name: ListGroupBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cst.name AS session_type_name,
       COALESCE(ri.status::text, r.status::text, '')::varchar AS recording_status,
       ri.asset_id AS recording_asset_id,
       ri.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN coaching_booking_recordings r ON r.booking_id = cb.id
LEFT JOIN coaching_recording_imports ri ON ri.booking_id = cb.id
WHERE cb.group_id = $1
ORDER BY cb.scheduled_at
`

type ListGroupBookingsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ExpertID           string             `json:"expert_id"`
	StudentID          string             `json:"student_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	SessionTypeID      pgtype.UUID        `json:"session_type_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes    int32              `json:"duration_minutes"`
	IsCancelled        bool               `json:"is_cancelled"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SessionTypeName    string             `json:"session_type_name"`
	RecordingStatus    string             `json:"recording_status"`
	RecordingAssetID   pgtype.UUID        `json:"recording_asset_id"`
	RecordingVideoID   pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBookingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupBookings, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupBookingsRow
	for rows.Next() {
		var i ListGroupBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingAssetID,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookings = `-- name: ListMyBookings :many
SELECT cb.id, cb.expert_id, cb.student_id, cb.group_id, cb.session_type_id, cb.scheduled_at, cb.duration_minutes, cb.is_cancelled, cb.cancellation_reason, cb.cancelled_by, cb.notes, cb.created_at, cb.updated_at, cst.name AS session_type_name,
       COALESCE(ri.status::text, r.status::text, '')::varchar AS recording_status,
       ri.asset_id AS recording_asset_id,
       ri.video_id AS recording_video_id
FROM coaching_bookings cb
JOIN coaching_session_types cst ON cst.id = cb.session_type_id
LEFT JOIN coaching_booking_recordings r ON r.booking_id = cb.id
LEFT JOIN coaching_recording_imports ri ON ri.booking_id = cb.id
WHERE (cb.expert_id = $1 OR cb.student_id = $1) AND cb.group_id = $2
ORDER BY cb.scheduled_at DESC
`

type ListMyBookingsParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

type ListMyBookingsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ExpertID           string             `json:"expert_id"`
	StudentID          string             `json:"student_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	SessionTypeID      pgtype.UUID        `json:"session_type_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes    int32              `json:"duration_minutes"`
	IsCancelled        bool               `json:"is_cancelled"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SessionTypeName    string             `json:"session_type_name"`
	RecordingStatus    string             `json:"recording_status"`
	RecordingAssetID   pgtype.UUID        `json:"recording_asset_id"`
	RecordingVideoID   pgtype.UUID        `json:"recording_video_id"`
}

func (q *Queries) ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMyBookings, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyBookingsRow
	for rows.Next() {
		var i ListMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.SessionTypeID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
			&i.RecordingStatus,
			&i.RecordingAssetID,
			&i.RecordingVideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRecordingImports = `-- name: ListPendingRecordingImports :many
SELECT
    ri.booking_id, ri.status, ri.gcs_object_name, ri.mux_asset_id, ri.mux_playback_id, ri.asset_id, ri.video_id, ri.attempts, ri.last_attempt_at, ri.imported_at, ri.error, ri.created_at, ri.updated_at,
    r.file_prefix,
    b.student_id,
    b.group_id,
    b.scheduled_at,
    b.duration_minutes,
    cst.name AS session_type_name
FROM coaching_recording_imports ri
JOIN coaching_booking_recordings r ON r.booking_id = ri.booking_id
JOIN coaching_bookings b ON b.id = ri.booking_id
JOIN coaching_session_types cst ON cst.id = b.session_type_id
WHERE r.status = 'stopped'
  AND ri.status IN ('pending', 'processing', 'failed')
  AND ri.attempts < 5
  AND (
    ri.last_attempt_at IS NULL
    OR ri.last_attempt_at <= NOW() - interval '1 minute'
  )
ORDER BY ri.created_at
LIMIT $1
`

type ListPendingRecordingImportsRow struct {
	BookingID       pgtype.UUID                   `json:"booking_id"`
	Status          CoachingRecordingImportStatus `json:"status"`
	GcsObjectName   pgtype.Text                   `json:"gcs_object_name"`
	MuxAssetID      pgtype.Text                   `json:"mux_asset_id"`
	MuxPlaybackID   pgtype.Text                   `json:"mux_playback_id"`
	AssetID         pgtype.UUID                   `json:"asset_id"`
	VideoID         pgtype.UUID                   `json:"video_id"`
	Attempts        int32                         `json:"attempts"`
	LastAttemptAt   pgtype.Timestamptz            `json:"last_attempt_at"`
	ImportedAt      pgtype.Timestamptz            `json:"imported_at"`
	Error           pgtype.Text                   `json:"error"`
	CreatedAt       pgtype.Timestamptz            `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz            `json:"updated_at"`
	FilePrefix      []string                      `json:"file_prefix"`
	StudentID       string                        `json:"student_id"`
	GroupID         pgtype.UUID                   `json:"group_id"`
	ScheduledAt     pgtype.Timestamptz            `json:"scheduled_at"`
	DurationMinutes int32                         `json:"duration_minutes"`
	SessionTypeName string                        `json:"session_type_name"`
}

func (q *Queries) ListPendingRecordingImports(ctx context.Context, limit int32) ([]ListPendingRecordingImportsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRecordingImports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRecordingImportsRow
	for rows.Next() {
		var i ListPendingRecordingImportsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.GcsObjectName,
			&i.MuxAssetID,
			&i.MuxPlaybackID,
			&i.AssetID,
			&i.VideoID,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.ImportedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FilePrefix,
			&i.StudentID,
			&i.GroupID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.SessionTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReminders = `-- name: ListPendingReminders :many
SELECT r.id, r.booking_id, r.remind_at,
       b.expert_id, b.student_id, b.group_id, b.scheduled_at, b.duration_minutes, b.is_cancelled
FROM coaching_booking_reminders r
JOIN coaching_bookings b ON b.id = r.booking_id
WHERE r.sent_at IS NULL
  AND r.remind_at <= NOW()
ORDER BY r.remind_at
LIMIT 100
`

type ListPendingRemindersRow struct {
	ID              pgtype.UUID        `json:"id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	RemindAt        pgtype.Timestamptz `json:"remind_at"`
	ExpertID        string             `json:"expert_id"`
	StudentID       string             `json:"student_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsCancelled     bool               `json:"is_cancelled"`
}

func (q *Queries) ListPendingReminders(ctx context.Context) ([]ListPendingRemindersRow, error) {
	rows, err := q.db.Query(ctx, listPendingReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRemindersRow
	for rows.Next() {
		var i ListPendingRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.RemindAt,
			&i.ExpertID,
			&i.StudentID,
			&i.GroupID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsCancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingsPastEnd = `-- name: ListRecordingsPastEnd :many
SELECT r.booking_id, r.status, r.resource_id, r.sid, r.uid, r.file_prefix, r.started_at, r.stopped_at, r.error, r.created_at, r.updated_at
FROM coaching_booking_recordings r
JOIN coaching_bookings b ON b.id = r.booking_id
WHERE r.status IN ('starting', 'started', 'stopping')
  AND b.scheduled_at + (b.duration_minutes * interval '1 minute') + ($1::int * interval '1 second') <= NOW()
ORDER BY b.scheduled_at
LIMIT $2
`

type ListRecordingsPastEndParams struct {
	GraceSeconds int32 `json:"grace_seconds"`
	LimitCount   int32 `json:"limit_count"`
}

func (q *Queries) ListRecordingsPastEnd(ctx context.Context, arg ListRecordingsPastEndParams) ([]CoachingBookingRecording, error) {
	rows, err := q.db.Query(ctx, listRecordingsPastEnd, arg.GraceSeconds, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingBookingRecording
	for rows.Next() {
		var i CoachingBookingRecording
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.ResourceID,
			&i.Sid,
			&i.Uid,
			&i.FilePrefix,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByExpertGroup = `-- name: ListSessionTypesByExpertGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE expert_id = $1 AND group_id = $2 AND is_active = true
ORDER BY duration_minutes
`

type ListSessionTypesByExpertGroupParams struct {
	ExpertID string      `json:"expert_id"`
	GroupID  pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListSessionTypesByExpertGroup(ctx context.Context, arg ListSessionTypesByExpertGroupParams) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByExpertGroup, arg.ExpertID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTypesByGroup = `-- name: ListSessionTypesByGroup :many
SELECT id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at FROM coaching_session_types
WHERE group_id = $1 AND is_active = true
ORDER BY expert_id, duration_minutes
`

func (q *Queries) ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingSessionType, error) {
	rows, err := q.db.Query(ctx, listSessionTypesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachingSessionType
	for rows.Next() {
		var i CoachingSessionType
		if err := rows.Scan(
			&i.ID,
			&i.ExpertID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingRecordingFailed = `-- name: MarkBookingRecordingFailed :exec
INSERT INTO coaching_booking_recordings (booking_id, status, error)
VALUES ($1, 'failed', $2)
ON CONFLICT (booking_id) DO UPDATE SET
    status = 'failed',
    error = EXCLUDED.error,
    updated_at = NOW()
`

type MarkBookingRecordingFailedParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	Error     pgtype.Text `json:"error"`
}

func (q *Queries) MarkBookingRecordingFailed(ctx context.Context, arg MarkBookingRecordingFailedParams) error {
	_, err := q.db.Exec(ctx, markBookingRecordingFailed, arg.BookingID, arg.Error)
	return err
}

const markBookingRecordingStarted = `-- name: MarkBookingRecordingStarted :one
INSERT INTO coaching_booking_recordings (
    booking_id,
    status,
    resource_id,
    sid,
    uid,
    file_prefix,
    started_at,
    stopped_at,
    error
)
VALUES ($1, 'started', $2, $3, $4, $5, NOW(), NULL, NULL)
ON CONFLICT (booking_id) DO UPDATE SET
    status = 'started',
    resource_id = EXCLUDED.resource_id,
    sid = EXCLUDED.sid,
    uid = EXCLUDED.uid,
    file_prefix = EXCLUDED.file_prefix,
    started_at = NOW(),
    stopped_at = NULL,
    error = NULL,
    updated_at = NOW()
RETURNING booking_id, status, resource_id, sid, uid, file_prefix, started_at, stopped_at, error, created_at, updated_at
`

type MarkBookingRecordingStartedParams struct {
	BookingID  pgtype.UUID `json:"booking_id"`
	ResourceID pgtype.Text `json:"resource_id"`
	Sid        pgtype.Text `json:"sid"`
	Uid        pgtype.Text `json:"uid"`
	FilePrefix []string    `json:"file_prefix"`
}

func (q *Queries) MarkBookingRecordingStarted(ctx context.Context, arg MarkBookingRecordingStartedParams) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, markBookingRecordingStarted,
		arg.BookingID,
		arg.ResourceID,
		arg.Sid,
		arg.Uid,
		arg.FilePrefix,
	)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ResourceID,
		&i.Sid,
		&i.Uid,
		&i.FilePrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBookingRecordingStopped = `-- name: MarkBookingRecordingStopped :one
UPDATE coaching_booking_recordings
SET status = 'stopped',
    stopped_at = NOW(),
    error = NULL,
    updated_at = NOW()
WHERE booking_id = $1
RETURNING booking_id, status, resource_id, sid, uid, file_prefix, started_at, stopped_at, error, created_at, updated_at
`

func (q *Queries) MarkBookingRecordingStopped(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, markBookingRecordingStopped, bookingID)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ResourceID,
		&i.Sid,
		&i.Uid,
		&i.FilePrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBookingRecordingStopping = `-- name: MarkBookingRecordingStopping :one
UPDATE coaching_booking_recordings
SET status = 'stopping',
    updated_at = NOW()
WHERE booking_id = $1
  AND status IN ('starting', 'started')
RETURNING booking_id, status, resource_id, sid, uid, file_prefix, started_at, stopped_at, error, created_at, updated_at
`

func (q *Queries) MarkBookingRecordingStopping(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error) {
	row := q.db.QueryRow(ctx, markBookingRecordingStopping, bookingID)
	var i CoachingBookingRecording
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.ResourceID,
		&i.Sid,
		&i.Uid,
		&i.FilePrefix,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecordingImportFailed = `-- name: MarkRecordingImportFailed :exec
UPDATE coaching_recording_imports
SET status = 'failed',
    error = $2,
    updated_at = NOW()
WHERE booking_id = $1
`

type MarkRecordingImportFailedParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	Error     pgtype.Text `json:"error"`
}

func (q *Queries) MarkRecordingImportFailed(ctx context.Context, arg MarkRecordingImportFailedParams) error {
	_, err := q.db.Exec(ctx, markRecordingImportFailed, arg.BookingID, arg.Error)
	return err
}

const markRecordingImportImporting = `-- name: MarkRecordingImportImporting :one
UPDATE coaching_recording_imports
SET status = 'importing',
    attempts = attempts + 1,
    last_attempt_at = NOW(),
    error = NULL,
    updated_at = NOW()
WHERE booking_id = $1
  AND status IN ('pending', 'processing', 'failed')
RETURNING booking_id, status, gcs_object_name, mux_asset_id, mux_playback_id, asset_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at
`

func (q *Queries) MarkRecordingImportImporting(ctx context.Context, bookingID pgtype.UUID) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, markRecordingImportImporting, bookingID)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.AssetID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecordingImportMuxCreated = `-- name: MarkRecordingImportMuxCreated :one
UPDATE coaching_recording_imports
SET status = 'processing',
    gcs_object_name = $2,
    mux_asset_id = $3,
    mux_playback_id = $4,
    error = NULL,
    updated_at = NOW()
WHERE booking_id = $1
RETURNING booking_id, status, gcs_object_name, mux_asset_id, mux_playback_id, asset_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at
`

type MarkRecordingImportMuxCreatedParams struct {
	BookingID     pgtype.UUID `json:"booking_id"`
	GcsObjectName pgtype.Text `json:"gcs_object_name"`
	MuxAssetID    pgtype.Text `json:"mux_asset_id"`
	MuxPlaybackID pgtype.Text `json:"mux_playback_id"`
}

func (q *Queries) MarkRecordingImportMuxCreated(ctx context.Context, arg MarkRecordingImportMuxCreatedParams) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, markRecordingImportMuxCreated,
		arg.BookingID,
		arg.GcsObjectName,
		arg.MuxAssetID,
		arg.MuxPlaybackID,
	)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.AssetID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecordingImportReady = `-- name: MarkRecordingImportReady :one
UPDATE coaching_recording_imports
SET status = 'ready',
    gcs_object_name = $2,
    mux_asset_id = $3,
    mux_playback_id = $4,
    asset_id = $5,
    video_id = $6,
    imported_at = NOW(),
    error = NULL,
    updated_at = NOW()
WHERE booking_id = $1
RETURNING booking_id, status, gcs_object_name, mux_asset_id, mux_playback_id, asset_id, video_id, attempts, last_attempt_at, imported_at, error, created_at, updated_at
`

type MarkRecordingImportReadyParams struct {
	BookingID     pgtype.UUID `json:"booking_id"`
	GcsObjectName pgtype.Text `json:"gcs_object_name"`
	MuxAssetID    pgtype.Text `json:"mux_asset_id"`
	MuxPlaybackID pgtype.Text `json:"mux_playback_id"`
	AssetID       pgtype.UUID `json:"asset_id"`
	VideoID       pgtype.UUID `json:"video_id"`
}

func (q *Queries) MarkRecordingImportReady(ctx context.Context, arg MarkRecordingImportReadyParams) (CoachingRecordingImport, error) {
	row := q.db.QueryRow(ctx, markRecordingImportReady,
		arg.BookingID,
		arg.GcsObjectName,
		arg.MuxAssetID,
		arg.MuxPlaybackID,
		arg.AssetID,
		arg.VideoID,
	)
	var i CoachingRecordingImport
	err := row.Scan(
		&i.BookingID,
		&i.Status,
		&i.GcsObjectName,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.AssetID,
		&i.VideoID,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.ImportedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE coaching_booking_reminders SET sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}

const updateAvailability = `-- name: UpdateAvailability :one
UPDATE coaching_availability
SET day_of_week = $2, start_time = $3, end_time = $4, updated_at = NOW()
WHERE id = $1 AND expert_id = $5 AND group_id = $6
RETURNING id, expert_id, group_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type UpdateAvailabilityParams struct {
	ID        pgtype.UUID `json:"id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	ExpertID  string      `json:"expert_id"`
	GroupID   pgtype.UUID `json:"group_id"`
}

func (q *Queries) UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (CoachingAvailability, error) {
	row := q.db.QueryRow(ctx, updateAvailability,
		arg.ID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.ExpertID,
		arg.GroupID,
	)
	var i CoachingAvailability
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionType = `-- name: UpdateSessionType :one
UPDATE coaching_session_types
SET name = $2, description = $3, duration_minutes = $4, updated_at = NOW()
WHERE id = $1 AND expert_id = $5 AND group_id = $6
RETURNING id, expert_id, group_id, name, description, duration_minutes, is_active, created_at, updated_at
`

type UpdateSessionTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
	ExpertID        string      `json:"expert_id"`
	GroupID         pgtype.UUID `json:"group_id"`
}

func (q *Queries) UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (CoachingSessionType, error) {
	row := q.db.QueryRow(ctx, updateSessionType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.ExpertID,
		arg.GroupID,
	)
	var i CoachingSessionType
	err := row.Scan(
		&i.ID,
		&i.ExpertID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
