// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLandingContactSubmission = `-- name: CreateLandingContactSubmission :one
INSERT INTO landing_contact_submissions (
  name,
  email,
  message,
  locale,
  page_url,
  user_agent
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, name, email, message, locale, page_url, user_agent, email_status, resend_email_id, email_error, created_at, updated_at
`

type CreateLandingContactSubmissionParams struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Message   string `json:"message"`
	Locale    string `json:"locale"`
	PageUrl   string `json:"page_url"`
	UserAgent string `json:"user_agent"`
}

func (q *Queries) CreateLandingContactSubmission(ctx context.Context, arg CreateLandingContactSubmissionParams) (LandingContactSubmission, error) {
	row := q.db.QueryRow(ctx, createLandingContactSubmission,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.Locale,
		arg.PageUrl,
		arg.UserAgent,
	)
	var i LandingContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Locale,
		&i.PageUrl,
		&i.UserAgent,
		&i.EmailStatus,
		&i.ResendEmailID,
		&i.EmailError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markLandingContactEmailFailed = `-- name: MarkLandingContactEmailFailed :exec
UPDATE landing_contact_submissions
SET
  email_status = 'failed',
  email_error = $2,
  updated_at = NOW()
WHERE id = $1
`

type MarkLandingContactEmailFailedParams struct {
	ID         pgtype.UUID `json:"id"`
	EmailError string      `json:"email_error"`
}

func (q *Queries) MarkLandingContactEmailFailed(ctx context.Context, arg MarkLandingContactEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markLandingContactEmailFailed, arg.ID, arg.EmailError)
	return err
}

const markLandingContactEmailSent = `-- name: MarkLandingContactEmailSent :exec
UPDATE landing_contact_submissions
SET
  email_status = 'sent',
  resend_email_id = $2,
  email_error = '',
  updated_at = NOW()
WHERE id = $1
`

type MarkLandingContactEmailSentParams struct {
	ID            pgtype.UUID `json:"id"`
	ResendEmailID string      `json:"resend_email_id"`
}

func (q *Queries) MarkLandingContactEmailSent(ctx context.Context, arg MarkLandingContactEmailSentParams) error {
	_, err := q.db.Exec(ctx, markLandingContactEmailSent, arg.ID, arg.ResendEmailID)
	return err
}
