// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counter.sql

package db

import (
	"context"
)

const getCounter = `-- name: GetCounter :one
SELECT value FROM counters WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getCounter)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const incrementCounter = `-- name: IncrementCounter :one
UPDATE counters 
SET value = value + 1, updated_at = NOW() 
WHERE id = 1 
RETURNING value
`

func (q *Queries) IncrementCounter(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCounter)
	var value int32
	err := row.Scan(&value)
	return value, err
}
