// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM user_devices
WHERE expo_push_token = $1
  AND user_id = $2
`

type DeleteDeviceParams struct {
	ExpoPushToken string `json:"expo_push_token"`
	UserID        string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ExpoPushToken, arg.UserID)
	return err
}

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE FROM user_devices
WHERE expo_push_token = $1
`

func (q *Queries) DeleteDeviceByToken(ctx context.Context, expoPushToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, expoPushToken)
	return err
}

const getUserPushPreferences = `-- name: GetUserPushPreferences :one
SELECT
    push_notifications_enabled,
    push_asset_uploads_enabled,
    push_asset_reviews_enabled,
    push_invitation_updates_enabled,
    push_group_membership_updates_enabled,
    push_coaching_booking_updates_enabled
FROM user_preferences
WHERE user_id = $1
`

type GetUserPushPreferencesRow struct {
	PushNotificationsEnabled          bool `json:"push_notifications_enabled"`
	PushAssetUploadsEnabled           bool `json:"push_asset_uploads_enabled"`
	PushAssetReviewsEnabled           bool `json:"push_asset_reviews_enabled"`
	PushInvitationUpdatesEnabled      bool `json:"push_invitation_updates_enabled"`
	PushGroupMembershipUpdatesEnabled bool `json:"push_group_membership_updates_enabled"`
	PushCoachingBookingUpdatesEnabled bool `json:"push_coaching_booking_updates_enabled"`
}

func (q *Queries) GetUserPushPreferences(ctx context.Context, userID string) (GetUserPushPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPushPreferences, userID)
	var i GetUserPushPreferencesRow
	err := row.Scan(
		&i.PushNotificationsEnabled,
		&i.PushAssetUploadsEnabled,
		&i.PushAssetReviewsEnabled,
		&i.PushInvitationUpdatesEnabled,
		&i.PushGroupMembershipUpdatesEnabled,
		&i.PushCoachingBookingUpdatesEnabled,
	)
	return i, err
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT id, user_id, expo_push_token, platform, created_at, last_seen_at FROM user_devices
WHERE user_id = $1
`

func (q *Queries) ListDevicesForUser(ctx context.Context, userID string) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpoPushToken,
			&i.Platform,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPushPreferences = `-- name: UpdateUserPushPreferences :one
UPDATE user_preferences
SET push_notifications_enabled            = $2,
    push_asset_uploads_enabled            = $3,
    push_asset_reviews_enabled            = $4,
    push_invitation_updates_enabled       = $5,
    push_group_membership_updates_enabled = $6,
    push_coaching_booking_updates_enabled = $7,
    updated_at                            = NOW()
WHERE user_id = $1
RETURNING user_id, language, created_at, updated_at, avatar, timezone, email_notifications_enabled, email_asset_uploads_enabled, email_asset_reviews_enabled, email_invitation_updates_enabled, email_group_membership_updates_enabled, email_coaching_booking_updates_enabled, email_coaching_reminders_enabled, first_name, last_name, push_notifications_enabled, push_asset_uploads_enabled, push_asset_reviews_enabled, push_invitation_updates_enabled, push_group_membership_updates_enabled, push_coaching_booking_updates_enabled
`

type UpdateUserPushPreferencesParams struct {
	UserID                            string `json:"user_id"`
	PushNotificationsEnabled          bool   `json:"push_notifications_enabled"`
	PushAssetUploadsEnabled           bool   `json:"push_asset_uploads_enabled"`
	PushAssetReviewsEnabled           bool   `json:"push_asset_reviews_enabled"`
	PushInvitationUpdatesEnabled      bool   `json:"push_invitation_updates_enabled"`
	PushGroupMembershipUpdatesEnabled bool   `json:"push_group_membership_updates_enabled"`
	PushCoachingBookingUpdatesEnabled bool   `json:"push_coaching_booking_updates_enabled"`
}

func (q *Queries) UpdateUserPushPreferences(ctx context.Context, arg UpdateUserPushPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPushPreferences,
		arg.UserID,
		arg.PushNotificationsEnabled,
		arg.PushAssetUploadsEnabled,
		arg.PushAssetReviewsEnabled,
		arg.PushInvitationUpdatesEnabled,
		arg.PushGroupMembershipUpdatesEnabled,
		arg.PushCoachingBookingUpdatesEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Timezone,
		&i.EmailNotificationsEnabled,
		&i.EmailAssetUploadsEnabled,
		&i.EmailAssetReviewsEnabled,
		&i.EmailInvitationUpdatesEnabled,
		&i.EmailGroupMembershipUpdatesEnabled,
		&i.EmailCoachingBookingUpdatesEnabled,
		&i.EmailCoachingRemindersEnabled,
		&i.FirstName,
		&i.LastName,
		&i.PushNotificationsEnabled,
		&i.PushAssetUploadsEnabled,
		&i.PushAssetReviewsEnabled,
		&i.PushInvitationUpdatesEnabled,
		&i.PushGroupMembershipUpdatesEnabled,
		&i.PushCoachingBookingUpdatesEnabled,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO user_devices (user_id, expo_push_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (expo_push_token) DO UPDATE
    SET user_id      = excluded.user_id,
        platform     = excluded.platform,
        last_seen_at = now()
RETURNING id, user_id, expo_push_token, platform, created_at, last_seen_at
`

type UpsertDeviceParams struct {
	UserID        string      `json:"user_id"`
	ExpoPushToken string      `json:"expo_push_token"`
	Platform      pgtype.Text `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.ExpoPushToken, arg.Platform)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpoPushToken,
		&i.Platform,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
