// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedbackSubmission = `-- name: CreateFeedbackSubmission :one
INSERT INTO feedback_submissions (
  user_id,
  user_display_name,
  rating,
  message,
  page_url,
  user_agent,
  discord_channel_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, user_id, user_display_name, rating, message, page_url, user_agent, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, created_at, updated_at
`

type CreateFeedbackSubmissionParams struct {
	UserID           string `json:"user_id"`
	UserDisplayName  string `json:"user_display_name"`
	Rating           int32  `json:"rating"`
	Message          string `json:"message"`
	PageUrl          string `json:"page_url"`
	UserAgent        string `json:"user_agent"`
	DiscordChannelID string `json:"discord_channel_id"`
}

func (q *Queries) CreateFeedbackSubmission(ctx context.Context, arg CreateFeedbackSubmissionParams) (FeedbackSubmission, error) {
	row := q.db.QueryRow(ctx, createFeedbackSubmission,
		arg.UserID,
		arg.UserDisplayName,
		arg.Rating,
		arg.Message,
		arg.PageUrl,
		arg.UserAgent,
		arg.DiscordChannelID,
	)
	var i FeedbackSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserDisplayName,
		&i.Rating,
		&i.Message,
		&i.PageUrl,
		&i.UserAgent,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFeedbackDiscordFailed = `-- name: MarkFeedbackDiscordFailed :exec
UPDATE feedback_submissions
SET
  discord_status = 'failed',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1
`

type MarkFeedbackDiscordFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkFeedbackDiscordFailed(ctx context.Context, arg MarkFeedbackDiscordFailedParams) error {
	_, err := q.db.Exec(ctx, markFeedbackDiscordFailed, arg.ID, arg.DiscordError)
	return err
}

const markFeedbackDiscordPosted = `-- name: MarkFeedbackDiscordPosted :exec
UPDATE feedback_submissions
SET
  discord_status = 'posted',
  discord_thread_id = $2,
  discord_message_id = $3,
  discord_error = '',
  updated_at = NOW()
WHERE id = $1
`

type MarkFeedbackDiscordPostedParams struct {
	ID               pgtype.UUID `json:"id"`
	DiscordThreadID  string      `json:"discord_thread_id"`
	DiscordMessageID string      `json:"discord_message_id"`
}

func (q *Queries) MarkFeedbackDiscordPosted(ctx context.Context, arg MarkFeedbackDiscordPostedParams) error {
	_, err := q.db.Exec(ctx, markFeedbackDiscordPosted, arg.ID, arg.DiscordThreadID, arg.DiscordMessageID)
	return err
}

const markFeedbackDiscordSkipped = `-- name: MarkFeedbackDiscordSkipped :exec
UPDATE feedback_submissions
SET
  discord_status = 'skipped',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1
`

type MarkFeedbackDiscordSkippedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkFeedbackDiscordSkipped(ctx context.Context, arg MarkFeedbackDiscordSkippedParams) error {
	_, err := q.db.Exec(ctx, markFeedbackDiscordSkipped, arg.ID, arg.DiscordError)
	return err
}
