// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id) VALUES ($1, $2)
`

type AddUserToGroupParams struct {
	UserID  string      `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const checkUserGroup = `-- name: CheckUserGroup :one
SELECT EXISTS(SELECT 1 FROM user_groups WHERE user_id = $1 AND group_id = $2)
`

type CheckUserGroupParams struct {
	UserID  string      `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) CheckUserGroup(ctx context.Context, arg CheckUserGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserGroup, arg.UserID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, owner_id, avatar, description) VALUES ($1, $2, $3, $4) RETURNING id, name, owner_id, avatar, created_at, updated_at, description
`

type CreateGroupParams struct {
	Name        string `json:"name"`
	OwnerID     string `json:"owner_id"`
	Avatar      string `json:"avatar"`
	Description string `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.OwnerID,
		arg.Avatar,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const createGroupInvitation = `-- name: CreateGroupInvitation :one
INSERT INTO group_invitations (group_id, inviter_id, email, code)
VALUES ($1, $2, $3, $4) RETURNING id, group_id, inviter_id, email, code, status, created_at
`

type CreateGroupInvitationParams struct {
	GroupID   pgtype.UUID `json:"group_id"`
	InviterID string      `json:"inviter_id"`
	Email     string      `json:"email"`
	Code      string      `json:"code"`
}

func (q *Queries) CreateGroupInvitation(ctx context.Context, arg CreateGroupInvitationParams) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, createGroupInvitation,
		arg.GroupID,
		arg.InviterID,
		arg.Email,
		arg.Code,
	)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterID,
		&i.Email,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND owner_id = $2
`

type DeleteGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.OwnerID)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, owner_id, avatar, created_at, updated_at, description FROM groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const getGroupInvitationByCode = `-- name: GetGroupInvitationByCode :one
SELECT id, group_id, inviter_id, email, code, status, created_at FROM group_invitations
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetGroupInvitationByCode(ctx context.Context, code string) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, getGroupInvitationByCode, code)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterID,
		&i.Email,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupInvitationByID = `-- name: GetGroupInvitationByID :one
SELECT id, group_id, inviter_id, email, code, status, created_at FROM group_invitations
WHERE id = $1 AND group_id = $2 LIMIT 1
`

type GetGroupInvitationByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetGroupInvitationByID(ctx context.Context, arg GetGroupInvitationByIDParams) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, getGroupInvitationByID, arg.ID, arg.GroupID)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterID,
		&i.Email,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT user_id FROM user_groups
WHERE group_id = $1
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.owner_id, g.avatar, g.description, g.created_at, g.updated_at
FROM groups g
JOIN user_groups ug ON g.id = ug.group_id
WHERE ug.user_id = $1
ORDER BY g.created_at DESC
`

type ListUserGroupsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	OwnerID     string             `json:"owner_id"`
	Avatar      string             `json:"avatar"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID string) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Avatar,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_groups WHERE user_id = $1 AND group_id = $2
`

type RemoveUserFromGroupParams struct {
	UserID  string      `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = $2, description = $3, avatar = $4, updated_at = NOW() WHERE id = $1 RETURNING id, name, owner_id, avatar, created_at, updated_at, description
`

type UpdateGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Avatar      string      `json:"avatar"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Avatar,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const updateGroupInvitationStatus = `-- name: UpdateGroupInvitationStatus :exec
UPDATE group_invitations SET status = $1 WHERE id = $2
`

type UpdateGroupInvitationStatusParams struct {
	Status InvitationStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateGroupInvitationStatus(ctx context.Context, arg UpdateGroupInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateGroupInvitationStatus, arg.Status, arg.ID)
	return err
}
