// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbound_email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimInboundEmailByResendID = `-- name: ClaimInboundEmailByResendID :one
WITH candidate AS (
  SELECT pending.id
  FROM inbound_emails AS pending
  WHERE pending.resend_email_id = $1
    AND pending.processing_status IN ('pending', 'failed')
    AND pending.next_attempt_at <= NOW()
    AND (pending.claim_until IS NULL OR pending.claim_until <= NOW())
    AND pending.processing_attempts < 10
  FOR UPDATE SKIP LOCKED
)
UPDATE inbound_emails AS email
SET
  processing_status = 'processing',
  processing_attempts = processing_attempts + 1,
  last_attempt_at = NOW(),
  claim_until = NOW() + INTERVAL '5 minutes',
  updated_at = NOW()
FROM candidate
WHERE email.id = candidate.id
RETURNING email.id, email.resend_email_id, email.svix_id, email.inbox, email.inbox_address, email.sender, email.recipients, email.cc, email.bcc, email.subject, email.message_id, email.received_at, email.body_text, email.attachments, email.processing_status, email.processing_attempts, email.last_attempt_at, email.next_attempt_at, email.claim_until, email.processed_at, email.discord_status, email.discord_channel_id, email.discord_thread_id, email.discord_message_id, email.discord_error, email.forwarding_status, email.forwarding_email_id, email.forwarding_error, email.created_at, email.updated_at
`

func (q *Queries) ClaimInboundEmailByResendID(ctx context.Context, resendEmailID string) (InboundEmail, error) {
	row := q.db.QueryRow(ctx, claimInboundEmailByResendID, resendEmailID)
	var i InboundEmail
	err := row.Scan(
		&i.ID,
		&i.ResendEmailID,
		&i.SvixID,
		&i.Inbox,
		&i.InboxAddress,
		&i.Sender,
		&i.Recipients,
		&i.Cc,
		&i.Bcc,
		&i.Subject,
		&i.MessageID,
		&i.ReceivedAt,
		&i.BodyText,
		&i.Attachments,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.ClaimUntil,
		&i.ProcessedAt,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.ForwardingStatus,
		&i.ForwardingEmailID,
		&i.ForwardingError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPendingInboundEmails = `-- name: ClaimPendingInboundEmails :many
WITH candidates AS (
  SELECT pending.id
  FROM inbound_emails AS pending
  WHERE pending.processing_status IN ('pending', 'failed')
    AND pending.next_attempt_at <= NOW()
    AND (pending.claim_until IS NULL OR pending.claim_until <= NOW())
    AND pending.processing_attempts < 10
  ORDER BY pending.next_attempt_at, pending.received_at
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
UPDATE inbound_emails AS email
SET
  processing_status = 'processing',
  processing_attempts = processing_attempts + 1,
  last_attempt_at = NOW(),
  claim_until = NOW() + INTERVAL '5 minutes',
  updated_at = NOW()
FROM candidates
WHERE email.id = candidates.id
RETURNING email.id, email.resend_email_id, email.svix_id, email.inbox, email.inbox_address, email.sender, email.recipients, email.cc, email.bcc, email.subject, email.message_id, email.received_at, email.body_text, email.attachments, email.processing_status, email.processing_attempts, email.last_attempt_at, email.next_attempt_at, email.claim_until, email.processed_at, email.discord_status, email.discord_channel_id, email.discord_thread_id, email.discord_message_id, email.discord_error, email.forwarding_status, email.forwarding_email_id, email.forwarding_error, email.created_at, email.updated_at
`

func (q *Queries) ClaimPendingInboundEmails(ctx context.Context, limit int32) ([]InboundEmail, error) {
	rows, err := q.db.Query(ctx, claimPendingInboundEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboundEmail
	for rows.Next() {
		var i InboundEmail
		if err := rows.Scan(
			&i.ID,
			&i.ResendEmailID,
			&i.SvixID,
			&i.Inbox,
			&i.InboxAddress,
			&i.Sender,
			&i.Recipients,
			&i.Cc,
			&i.Bcc,
			&i.Subject,
			&i.MessageID,
			&i.ReceivedAt,
			&i.BodyText,
			&i.Attachments,
			&i.ProcessingStatus,
			&i.ProcessingAttempts,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
			&i.ClaimUntil,
			&i.ProcessedAt,
			&i.DiscordStatus,
			&i.DiscordChannelID,
			&i.DiscordThreadID,
			&i.DiscordMessageID,
			&i.DiscordError,
			&i.ForwardingStatus,
			&i.ForwardingEmailID,
			&i.ForwardingError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboundEmailDiscordFailed = `-- name: MarkInboundEmailDiscordFailed :exec
UPDATE inbound_emails
SET
  discord_status = 'failed',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1 AND discord_status <> 'posted'
`

type MarkInboundEmailDiscordFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkInboundEmailDiscordFailed(ctx context.Context, arg MarkInboundEmailDiscordFailedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailDiscordFailed, arg.ID, arg.DiscordError)
	return err
}

const markInboundEmailDiscordPosted = `-- name: MarkInboundEmailDiscordPosted :exec
UPDATE inbound_emails
SET
  discord_status = 'posted',
  discord_thread_id = $2,
  discord_message_id = $3,
  discord_error = '',
  updated_at = NOW()
WHERE id = $1 AND discord_status <> 'posted'
`

type MarkInboundEmailDiscordPostedParams struct {
	ID               pgtype.UUID `json:"id"`
	DiscordThreadID  string      `json:"discord_thread_id"`
	DiscordMessageID string      `json:"discord_message_id"`
}

func (q *Queries) MarkInboundEmailDiscordPosted(ctx context.Context, arg MarkInboundEmailDiscordPostedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailDiscordPosted, arg.ID, arg.DiscordThreadID, arg.DiscordMessageID)
	return err
}

const markInboundEmailDiscordSkipped = `-- name: MarkInboundEmailDiscordSkipped :exec
UPDATE inbound_emails
SET
  discord_status = 'skipped',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1 AND discord_status <> 'posted'
`

type MarkInboundEmailDiscordSkippedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkInboundEmailDiscordSkipped(ctx context.Context, arg MarkInboundEmailDiscordSkippedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailDiscordSkipped, arg.ID, arg.DiscordError)
	return err
}

const markInboundEmailForwarded = `-- name: MarkInboundEmailForwarded :exec
UPDATE inbound_emails
SET
  forwarding_status = 'forwarded',
  forwarding_email_id = $2,
  forwarding_error = '',
  updated_at = NOW()
WHERE id = $1 AND forwarding_status <> 'forwarded'
`

type MarkInboundEmailForwardedParams struct {
	ID                pgtype.UUID `json:"id"`
	ForwardingEmailID string      `json:"forwarding_email_id"`
}

func (q *Queries) MarkInboundEmailForwarded(ctx context.Context, arg MarkInboundEmailForwardedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailForwarded, arg.ID, arg.ForwardingEmailID)
	return err
}

const markInboundEmailForwardingFailed = `-- name: MarkInboundEmailForwardingFailed :exec
UPDATE inbound_emails
SET
  forwarding_status = 'failed',
  forwarding_error = $2,
  updated_at = NOW()
WHERE id = $1 AND forwarding_status <> 'forwarded'
`

type MarkInboundEmailForwardingFailedParams struct {
	ID              pgtype.UUID `json:"id"`
	ForwardingError string      `json:"forwarding_error"`
}

func (q *Queries) MarkInboundEmailForwardingFailed(ctx context.Context, arg MarkInboundEmailForwardingFailedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailForwardingFailed, arg.ID, arg.ForwardingError)
	return err
}

const markInboundEmailForwardingSkipped = `-- name: MarkInboundEmailForwardingSkipped :exec
UPDATE inbound_emails
SET
  forwarding_status = 'skipped',
  forwarding_error = $2,
  updated_at = NOW()
WHERE id = $1 AND forwarding_status <> 'forwarded'
`

type MarkInboundEmailForwardingSkippedParams struct {
	ID              pgtype.UUID `json:"id"`
	ForwardingError string      `json:"forwarding_error"`
}

func (q *Queries) MarkInboundEmailForwardingSkipped(ctx context.Context, arg MarkInboundEmailForwardingSkippedParams) error {
	_, err := q.db.Exec(ctx, markInboundEmailForwardingSkipped, arg.ID, arg.ForwardingError)
	return err
}

const releaseInboundEmailClaim = `-- name: ReleaseInboundEmailClaim :exec
UPDATE inbound_emails
SET
  processing_status = CASE
    WHEN discord_status IN ('posted', 'skipped')
      AND forwarding_status IN ('forwarded', 'skipped') THEN 'processed'
    ELSE 'failed'
  END,
  processed_at = CASE
    WHEN discord_status IN ('posted', 'skipped')
      AND forwarding_status IN ('forwarded', 'skipped') THEN NOW()
    ELSE processed_at
  END,
  next_attempt_at = CASE
    WHEN discord_status IN ('posted', 'skipped')
      AND forwarding_status IN ('forwarded', 'skipped') THEN next_attempt_at
    ELSE NOW() + LEAST(60, CAST(POWER(2, LEAST(processing_attempts, 6)) AS INTEGER)) * INTERVAL '1 minute'
  END,
  claim_until = NULL,
  updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ReleaseInboundEmailClaim(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseInboundEmailClaim, id)
	return err
}

const updateInboundEmailContent = `-- name: UpdateInboundEmailContent :exec
UPDATE inbound_emails
SET
  sender = $2,
  recipients = $3,
  cc = $4,
  bcc = $5,
  subject = $6,
  message_id = $7,
  received_at = $8,
  body_text = $9,
  attachments = $10,
  updated_at = NOW()
WHERE id = $1
`

type UpdateInboundEmailContentParams struct {
	ID          pgtype.UUID        `json:"id"`
	Sender      string             `json:"sender"`
	Recipients  []string           `json:"recipients"`
	Cc          []string           `json:"cc"`
	Bcc         []string           `json:"bcc"`
	Subject     string             `json:"subject"`
	MessageID   string             `json:"message_id"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	BodyText    string             `json:"body_text"`
	Attachments []byte             `json:"attachments"`
}

func (q *Queries) UpdateInboundEmailContent(ctx context.Context, arg UpdateInboundEmailContentParams) error {
	_, err := q.db.Exec(ctx, updateInboundEmailContent,
		arg.ID,
		arg.Sender,
		arg.Recipients,
		arg.Cc,
		arg.Bcc,
		arg.Subject,
		arg.MessageID,
		arg.ReceivedAt,
		arg.BodyText,
		arg.Attachments,
	)
	return err
}

const upsertInboundEmail = `-- name: UpsertInboundEmail :one
INSERT INTO inbound_emails (
  resend_email_id,
  svix_id,
  inbox,
  inbox_address,
  sender,
  recipients,
  cc,
  bcc,
  subject,
  message_id,
  received_at,
  discord_channel_id,
  forwarding_status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13
)
ON CONFLICT (resend_email_id) DO UPDATE SET
  svix_id = CASE WHEN inbound_emails.svix_id = '' THEN EXCLUDED.svix_id ELSE inbound_emails.svix_id END,
  inbox = EXCLUDED.inbox,
  inbox_address = EXCLUDED.inbox_address,
  sender = EXCLUDED.sender,
  recipients = EXCLUDED.recipients,
  cc = EXCLUDED.cc,
  bcc = EXCLUDED.bcc,
  subject = EXCLUDED.subject,
  message_id = EXCLUDED.message_id,
  received_at = EXCLUDED.received_at,
  discord_channel_id = EXCLUDED.discord_channel_id,
  updated_at = NOW()
RETURNING id, resend_email_id, svix_id, inbox, inbox_address, sender, recipients, cc, bcc, subject, message_id, received_at, body_text, attachments, processing_status, processing_attempts, last_attempt_at, next_attempt_at, claim_until, processed_at, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, forwarding_status, forwarding_email_id, forwarding_error, created_at, updated_at
`

type UpsertInboundEmailParams struct {
	ResendEmailID    string             `json:"resend_email_id"`
	SvixID           string             `json:"svix_id"`
	Inbox            string             `json:"inbox"`
	InboxAddress     string             `json:"inbox_address"`
	Sender           string             `json:"sender"`
	Recipients       []string           `json:"recipients"`
	Cc               []string           `json:"cc"`
	Bcc              []string           `json:"bcc"`
	Subject          string             `json:"subject"`
	MessageID        string             `json:"message_id"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	DiscordChannelID string             `json:"discord_channel_id"`
	ForwardingStatus string             `json:"forwarding_status"`
}

func (q *Queries) UpsertInboundEmail(ctx context.Context, arg UpsertInboundEmailParams) (InboundEmail, error) {
	row := q.db.QueryRow(ctx, upsertInboundEmail,
		arg.ResendEmailID,
		arg.SvixID,
		arg.Inbox,
		arg.InboxAddress,
		arg.Sender,
		arg.Recipients,
		arg.Cc,
		arg.Bcc,
		arg.Subject,
		arg.MessageID,
		arg.ReceivedAt,
		arg.DiscordChannelID,
		arg.ForwardingStatus,
	)
	var i InboundEmail
	err := row.Scan(
		&i.ID,
		&i.ResendEmailID,
		&i.SvixID,
		&i.Inbox,
		&i.InboxAddress,
		&i.Sender,
		&i.Recipients,
		&i.Cc,
		&i.Bcc,
		&i.Subject,
		&i.MessageID,
		&i.ReceivedAt,
		&i.BodyText,
		&i.Attachments,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.ClaimUntil,
		&i.ProcessedAt,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.ForwardingStatus,
		&i.ForwardingEmailID,
		&i.ForwardingError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
