// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetStatus string

const (
	AssetStatusWaitingUpload AssetStatus = "waiting_upload"
	AssetStatusPending       AssetStatus = "pending"
	AssetStatusCompleted     AssetStatus = "completed"
)

func (e *AssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetStatus(s)
	case string:
		*e = AssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetStatus: %T", src)
	}
	return nil
}

type NullAssetStatus struct {
	AssetStatus AssetStatus `json:"asset_status"`
	Valid       bool        `json:"valid"` // Valid is true if AssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetStatus), nil
}

type VideoStatus string

const (
	VideoStatusWaitingUpload VideoStatus = "waiting_upload"
	VideoStatusReady         VideoStatus = "ready"
	VideoStatusFailed        VideoStatus = "failed"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus `json:"video_status"`
	Valid       bool        `json:"valid"` // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type Asset struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      AssetStatus        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GroupID     pgtype.UUID        `json:"group_id"`
	OwnerID     string             `json:"owner_id"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	Avatar    []byte             `json:"avatar"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        string           `json:"id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Email     string           `json:"email"`
	Language  string           `json:"language"`
	Avatar    []byte           `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserGroup struct {
	UserID    string             `json:"user_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Video struct {
	ID          pgtype.UUID        `json:"id"`
	AssetID     pgtype.UUID        `json:"asset_id"`
	MuxUploadID string             `json:"mux_upload_id"`
	MuxAssetID  pgtype.Text        `json:"mux_asset_id"`
	PlaybackID  pgtype.Text        `json:"playback_id"`
	Status      VideoStatus        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VideoReview struct {
	ID        pgtype.UUID        `json:"id"`
	VideoID   pgtype.UUID        `json:"video_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
