// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationReport = `-- name: CreateModerationReport :one
INSERT INTO moderation_reports (
  reporter_user_id,
  reporter_display_name,
  subject_type,
  target_review_id,
  target_video_id,
  target_user_id,
  target_display_name,
  target_review_content,
  reason,
  details,
  page_url,
  user_agent,
  discord_channel_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13
)
RETURNING id, reporter_user_id, reporter_display_name, subject_type, target_review_id, target_video_id, target_user_id, target_display_name, target_review_content, reason, details, page_url, user_agent, status, resolved_by_user_id, resolved_at, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, created_at, updated_at
`

type CreateModerationReportParams struct {
	ReporterUserID      string      `json:"reporter_user_id"`
	ReporterDisplayName string      `json:"reporter_display_name"`
	SubjectType         string      `json:"subject_type"`
	TargetReviewID      pgtype.UUID `json:"target_review_id"`
	TargetVideoID       pgtype.UUID `json:"target_video_id"`
	TargetUserID        string      `json:"target_user_id"`
	TargetDisplayName   string      `json:"target_display_name"`
	TargetReviewContent string      `json:"target_review_content"`
	Reason              string      `json:"reason"`
	Details             string      `json:"details"`
	PageUrl             string      `json:"page_url"`
	UserAgent           string      `json:"user_agent"`
	DiscordChannelID    string      `json:"discord_channel_id"`
}

func (q *Queries) CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, createModerationReport,
		arg.ReporterUserID,
		arg.ReporterDisplayName,
		arg.SubjectType,
		arg.TargetReviewID,
		arg.TargetVideoID,
		arg.TargetUserID,
		arg.TargetDisplayName,
		arg.TargetReviewContent,
		arg.Reason,
		arg.Details,
		arg.PageUrl,
		arg.UserAgent,
		arg.DiscordChannelID,
	)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.ReporterDisplayName,
		&i.SubjectType,
		&i.TargetReviewID,
		&i.TargetVideoID,
		&i.TargetUserID,
		&i.TargetDisplayName,
		&i.TargetReviewContent,
		&i.Reason,
		&i.Details,
		&i.PageUrl,
		&i.UserAgent,
		&i.Status,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModerationReport = `-- name: GetModerationReport :one
SELECT id, reporter_user_id, reporter_display_name, subject_type, target_review_id, target_video_id, target_user_id, target_display_name, target_review_content, reason, details, page_url, user_agent, status, resolved_by_user_id, resolved_at, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, created_at, updated_at
FROM moderation_reports
WHERE id = $1
`

func (q *Queries) GetModerationReport(ctx context.Context, id pgtype.UUID) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, getModerationReport, id)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.ReporterDisplayName,
		&i.SubjectType,
		&i.TargetReviewID,
		&i.TargetVideoID,
		&i.TargetUserID,
		&i.TargetDisplayName,
		&i.TargetReviewContent,
		&i.Reason,
		&i.Details,
		&i.PageUrl,
		&i.UserAgent,
		&i.Status,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewModerationTarget = `-- name: GetReviewModerationTarget :one
SELECT
  r.id AS review_id,
  r.video_id,
  r.author_id AS target_user_id,
  r.content AS target_review_content,
  COALESCE(NULLIF(trim(up.first_name || ' ' || up.last_name), ''), 'User')::text AS target_display_name
FROM video_reviews r
LEFT JOIN user_preferences up ON up.user_id = r.author_id
WHERE r.id = $1
`

type GetReviewModerationTargetRow struct {
	ReviewID            pgtype.UUID `json:"review_id"`
	VideoID             pgtype.UUID `json:"video_id"`
	TargetUserID        pgtype.Text `json:"target_user_id"`
	TargetReviewContent string      `json:"target_review_content"`
	TargetDisplayName   string      `json:"target_display_name"`
}

func (q *Queries) GetReviewModerationTarget(ctx context.Context, id pgtype.UUID) (GetReviewModerationTargetRow, error) {
	row := q.db.QueryRow(ctx, getReviewModerationTarget, id)
	var i GetReviewModerationTargetRow
	err := row.Scan(
		&i.ReviewID,
		&i.VideoID,
		&i.TargetUserID,
		&i.TargetReviewContent,
		&i.TargetDisplayName,
	)
	return i, err
}

const listModerationReports = `-- name: ListModerationReports :many
SELECT id, reporter_user_id, reporter_display_name, subject_type, target_review_id, target_video_id, target_user_id, target_display_name, target_review_content, reason, details, page_url, user_agent, status, resolved_by_user_id, resolved_at, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, created_at, updated_at
FROM moderation_reports
WHERE
  ($1::text = '' OR status = $1::text)
  AND ($2::text = '' OR subject_type = $2::text)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListModerationReportsParams struct {
	StatusFilter      string `json:"status_filter"`
	SubjectTypeFilter string `json:"subject_type_filter"`
	OffsetCount       int32  `json:"offset_count"`
	LimitCount        int32  `json:"limit_count"`
}

func (q *Queries) ListModerationReports(ctx context.Context, arg ListModerationReportsParams) ([]ModerationReport, error) {
	rows, err := q.db.Query(ctx, listModerationReports,
		arg.StatusFilter,
		arg.SubjectTypeFilter,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationReport
	for rows.Next() {
		var i ModerationReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterUserID,
			&i.ReporterDisplayName,
			&i.SubjectType,
			&i.TargetReviewID,
			&i.TargetVideoID,
			&i.TargetUserID,
			&i.TargetDisplayName,
			&i.TargetReviewContent,
			&i.Reason,
			&i.Details,
			&i.PageUrl,
			&i.UserAgent,
			&i.Status,
			&i.ResolvedByUserID,
			&i.ResolvedAt,
			&i.DiscordStatus,
			&i.DiscordChannelID,
			&i.DiscordThreadID,
			&i.DiscordMessageID,
			&i.DiscordError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModerationReportDiscordFailed = `-- name: MarkModerationReportDiscordFailed :exec
UPDATE moderation_reports
SET
  discord_status = 'failed',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1
`

type MarkModerationReportDiscordFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkModerationReportDiscordFailed(ctx context.Context, arg MarkModerationReportDiscordFailedParams) error {
	_, err := q.db.Exec(ctx, markModerationReportDiscordFailed, arg.ID, arg.DiscordError)
	return err
}

const markModerationReportDiscordPosted = `-- name: MarkModerationReportDiscordPosted :exec
UPDATE moderation_reports
SET
  discord_status = 'posted',
  discord_thread_id = $2,
  discord_message_id = $3,
  discord_error = '',
  updated_at = NOW()
WHERE id = $1
`

type MarkModerationReportDiscordPostedParams struct {
	ID               pgtype.UUID `json:"id"`
	DiscordThreadID  string      `json:"discord_thread_id"`
	DiscordMessageID string      `json:"discord_message_id"`
}

func (q *Queries) MarkModerationReportDiscordPosted(ctx context.Context, arg MarkModerationReportDiscordPostedParams) error {
	_, err := q.db.Exec(ctx, markModerationReportDiscordPosted, arg.ID, arg.DiscordThreadID, arg.DiscordMessageID)
	return err
}

const markModerationReportDiscordSkipped = `-- name: MarkModerationReportDiscordSkipped :exec
UPDATE moderation_reports
SET
  discord_status = 'skipped',
  discord_error = $2,
  updated_at = NOW()
WHERE id = $1
`

type MarkModerationReportDiscordSkippedParams struct {
	ID           pgtype.UUID `json:"id"`
	DiscordError string      `json:"discord_error"`
}

func (q *Queries) MarkModerationReportDiscordSkipped(ctx context.Context, arg MarkModerationReportDiscordSkippedParams) error {
	_, err := q.db.Exec(ctx, markModerationReportDiscordSkipped, arg.ID, arg.DiscordError)
	return err
}

const updateModerationReportStatus = `-- name: UpdateModerationReportStatus :one
UPDATE moderation_reports
SET
  status = $2,
  resolved_by_user_id = $3,
  resolved_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND status = 'open'
RETURNING id, reporter_user_id, reporter_display_name, subject_type, target_review_id, target_video_id, target_user_id, target_display_name, target_review_content, reason, details, page_url, user_agent, status, resolved_by_user_id, resolved_at, discord_status, discord_channel_id, discord_thread_id, discord_message_id, discord_error, created_at, updated_at
`

type UpdateModerationReportStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	Status           string      `json:"status"`
	ResolvedByUserID string      `json:"resolved_by_user_id"`
}

func (q *Queries) UpdateModerationReportStatus(ctx context.Context, arg UpdateModerationReportStatusParams) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, updateModerationReportStatus, arg.ID, arg.Status, arg.ResolvedByUserID)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.ReporterDisplayName,
		&i.SubjectType,
		&i.TargetReviewID,
		&i.TargetVideoID,
		&i.TargetUserID,
		&i.TargetDisplayName,
		&i.TargetReviewContent,
		&i.Reason,
		&i.Details,
		&i.PageUrl,
		&i.UserAgent,
		&i.Status,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.DiscordStatus,
		&i.DiscordChannelID,
		&i.DiscordThreadID,
		&i.DiscordMessageID,
		&i.DiscordError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
