// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (recipient_id, type, payload)
VALUES ($1, $2, $3)
RETURNING id, recipient_id, type, payload, read_at, created_at
`

type CreateNotificationParams struct {
	RecipientID string           `json:"recipient_id"`
	Type        NotificationType `json:"type"`
	Payload     []byte           `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.RecipientID, arg.Type, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_id, type, payload, read_at, created_at FROM notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_id, type, payload, read_at, created_at FROM notifications
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsParams struct {
	RecipientID string `json:"recipient_id"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Type,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE id = $1 AND recipient_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID          pgtype.UUID `json:"id"`
	RecipientID string      `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	return err
}
