// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUserAccess(ctx context.Context, arg ActivateUserAccessParams) (UserAccess, error)
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	AssignBookingRecordingAsset(ctx context.Context, arg AssignBookingRecordingAssetParams) (CoachingBooking, error)
	CancelBooking(ctx context.Context, arg CancelBookingParams) (CoachingBooking, error)
	CheckUserGroup(ctx context.Context, arg CheckUserGroupParams) (bool, error)
	CheckVideoVisibleToUser(ctx context.Context, arg CheckVideoVisibleToUserParams) (bool, error)
	ClaimInboundEmailByResendID(ctx context.Context, resendEmailID string) (InboundEmail, error)
	// === Simple recording parts ===
	ClaimNextRecordingPart(ctx context.Context, arg ClaimNextRecordingPartParams) (CoachingBookingRecording, error)
	ClaimPendingInboundEmails(ctx context.Context, limit int32) ([]InboundEmail, error)
	ClaimPendingRecordingPartImports(ctx context.Context, limit int32) ([]ClaimPendingRecordingPartImportsRow, error)
	ClearRecordingPartEmptySince(ctx context.Context, bookingID pgtype.UUID) error
	ConsumeSignupCode(ctx context.Context, arg ConsumeSignupCodeParams) (SignupCode, error)
	CountConflictingBookings(ctx context.Context, arg CountConflictingBookingsParams) (int64, error)
	CountFreshBookingParticipants(ctx context.Context, arg CountFreshBookingParticipantsParams) (int64, error)
	CountSignupCodesByOwner(ctx context.Context, ownerUserID string) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID string) (int64, error)
	CountVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	// === Availability ===
	CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (CoachingAvailability, error)
	// === Blocked Slots ===
	CreateBlockedSlot(ctx context.Context, arg CreateBlockedSlotParams) (CoachingBlockedSlot, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CoachingBooking, error)
	// === Booking Reminders ===
	CreateBookingReminder(ctx context.Context, arg CreateBookingReminderParams) error
	CreateFeedbackSubmission(ctx context.Context, arg CreateFeedbackSubmissionParams) (FeedbackSubmission, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupInvitation(ctx context.Context, arg CreateGroupInvitationParams) (GroupInvitation, error)
	CreateLandingContactSubmission(ctx context.Context, arg CreateLandingContactSubmissionParams) (LandingContactSubmission, error)
	CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (ModerationReport, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrderedVideoFromMuxAsset(ctx context.Context, arg CreateOrderedVideoFromMuxAssetParams) (Video, error)
	// === Session Types ===
	CreateSessionType(ctx context.Context, arg CreateSessionTypeParams) (CoachingSessionType, error)
	CreateSignupCodeWithinLimit(ctx context.Context, arg CreateSignupCodeWithinLimitParams) (SignupCode, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoFromMuxAsset(ctx context.Context, arg CreateVideoFromMuxAssetParams) (Video, error)
	CreateVideoReview(ctx context.Context, arg CreateVideoReviewParams) (VideoReview, error)
	DeactivateSessionType(ctx context.Context, arg DeactivateSessionTypeParams) (int64, error)
	DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) (int64, error)
	DeleteBlockedSlot(ctx context.Context, arg DeleteBlockedSlotParams) (int64, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) error
	DeleteVideoReview(ctx context.Context, arg DeleteVideoReviewParams) error
	EnsureRecordingPartImport(ctx context.Context, arg EnsureRecordingPartImportParams) (CoachingRecordingImport, error)
	EnsureUserAccess(ctx context.Context, userID string) (UserAccess, error)
	ExchangeRecordingRendererCapability(ctx context.Context, rendererTokenHash []byte) (ExchangeRecordingRendererCapabilityRow, error)
	GetActiveRecordingPart(ctx context.Context, bookingID pgtype.UUID) (CoachingBookingRecording, error)
	GetAsset(ctx context.Context, id pgtype.UUID) (GetAssetRow, error)
	GetAssetOwnerByVideoID(ctx context.Context, id pgtype.UUID) (GetAssetOwnerByVideoIDRow, error)
	GetAssetStatusByVideoID(ctx context.Context, id pgtype.UUID) (AssetStatus, error)
	GetAssetVideos(ctx context.Context, assetID pgtype.UUID) ([]GetAssetVideosRow, error)
	GetBooking(ctx context.Context, arg GetBookingParams) (CoachingBooking, error)
	GetBookingForRecordingAssetUpdate(ctx context.Context, id pgtype.UUID) (CoachingBooking, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupInvitationByCode(ctx context.Context, code string) (GroupInvitation, error)
	GetGroupInvitationByID(ctx context.Context, arg GetGroupInvitationByIDParams) (GroupInvitation, error)
	GetGroupInvitationsByCodes(ctx context.Context, dollar_1 []string) ([]GroupInvitation, error)
	GetModerationReport(ctx context.Context, id pgtype.UUID) (ModerationReport, error)
	GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error)
	GetReviewModerationTarget(ctx context.Context, id pgtype.UUID) (GetReviewModerationTargetRow, error)
	GetSessionType(ctx context.Context, arg GetSessionTypeParams) (CoachingSessionType, error)
	GetUserAccess(ctx context.Context, userID string) (UserAccess, error)
	GetUserEmailPreferences(ctx context.Context, userID string) (GetUserEmailPreferencesRow, error)
	GetUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	// === Timezone ===
	GetUserTimezone(ctx context.Context, userID string) (string, error)
	GetVideoReview(ctx context.Context, id pgtype.UUID) (GetVideoReviewRow, error)
	GetVisibleAsset(ctx context.Context, arg GetVisibleAssetParams) (GetVisibleAssetRow, error)
	HasVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (bool, error)
	IsRecordingAssetStillOpen(ctx context.Context, recordingAssetID pgtype.UUID) (bool, error)
	LeaveGroupIfNotLastMember(ctx context.Context, arg LeaveGroupIfNotLastMemberParams) (int64, error)
	ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error)
	ListAllMyBookings(ctx context.Context, expertID string) ([]ListAllMyBookingsRow, error)
	ListAvailabilityByExpertGroup(ctx context.Context, arg ListAvailabilityByExpertGroupParams) ([]CoachingAvailability, error)
	ListAvailabilityByExpertGroupDay(ctx context.Context, arg ListAvailabilityByExpertGroupDayParams) ([]CoachingAvailability, error)
	ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingAvailability, error)
	ListBlockedSlots(ctx context.Context, arg ListBlockedSlotsParams) ([]CoachingBlockedSlot, error)
	// === Bookings ===
	ListBookingsByExpertInRange(ctx context.Context, arg ListBookingsByExpertInRangeParams) ([]CoachingBooking, error)
	ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBookingsRow, error)
	ListGroupInvitations(ctx context.Context, groupID pgtype.UUID) ([]GroupInvitation, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]string, error)
	ListModerationReports(ctx context.Context, arg ListModerationReportsParams) ([]ModerationReport, error)
	ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPendingReminders(ctx context.Context) ([]ListPendingRemindersRow, error)
	ListRecordingPartsReadyToStop(ctx context.Context, arg ListRecordingPartsReadyToStopParams) ([]CoachingBookingRecording, error)
	ListSessionTypesByExpertGroup(ctx context.Context, arg ListSessionTypesByExpertGroupParams) ([]CoachingSessionType, error)
	ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingSessionType, error)
	ListSignupCodesByOwner(ctx context.Context, ownerUserID string) ([]SignupCode, error)
	ListStoppedRecordingPartsForDiscovery(ctx context.Context, limit int32) ([]CoachingBookingRecording, error)
	ListUserGroups(ctx context.Context, userID string) ([]ListUserGroupsRow, error)
	ListVideoReviews(ctx context.Context, videoID pgtype.UUID) ([]ListVideoReviewsRow, error)
	// Ready videos without a captured duration. Either identifier may be empty:
	// direct uploads carry mux_upload_id, coaching imports carry mux_asset_id.
	ListVideosMissingDuration(ctx context.Context, limit int32) ([]ListVideosMissingDurationRow, error)
	ListVisibleAssets(ctx context.Context, arg ListVisibleAssetsParams) ([]ListVisibleAssetsRow, error)
	MarkAllNotificationsRead(ctx context.Context, recipientID string) error
	MarkEmptyRecordingPartsWithoutFreshHumans(ctx context.Context, freshSeconds int32) (int64, error)
	MarkFeedbackDiscordFailed(ctx context.Context, arg MarkFeedbackDiscordFailedParams) error
	MarkFeedbackDiscordPosted(ctx context.Context, arg MarkFeedbackDiscordPostedParams) error
	MarkFeedbackDiscordSkipped(ctx context.Context, arg MarkFeedbackDiscordSkippedParams) error
	MarkInboundEmailDiscordFailed(ctx context.Context, arg MarkInboundEmailDiscordFailedParams) error
	MarkInboundEmailDiscordPosted(ctx context.Context, arg MarkInboundEmailDiscordPostedParams) error
	MarkInboundEmailDiscordSkipped(ctx context.Context, arg MarkInboundEmailDiscordSkippedParams) error
	MarkInboundEmailForwarded(ctx context.Context, arg MarkInboundEmailForwardedParams) error
	MarkInboundEmailForwardingFailed(ctx context.Context, arg MarkInboundEmailForwardingFailedParams) error
	MarkInboundEmailForwardingSkipped(ctx context.Context, arg MarkInboundEmailForwardingSkippedParams) error
	MarkLandingContactEmailFailed(ctx context.Context, arg MarkLandingContactEmailFailedParams) error
	MarkLandingContactEmailSent(ctx context.Context, arg MarkLandingContactEmailSentParams) error
	MarkModerationReportDiscordFailed(ctx context.Context, arg MarkModerationReportDiscordFailedParams) error
	MarkModerationReportDiscordPosted(ctx context.Context, arg MarkModerationReportDiscordPostedParams) error
	MarkModerationReportDiscordSkipped(ctx context.Context, arg MarkModerationReportDiscordSkippedParams) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkNotificationReadByInviteCode(ctx context.Context, arg MarkNotificationReadByInviteCodeParams) error
	MarkRecordingPartFailed(ctx context.Context, arg MarkRecordingPartFailedParams) error
	MarkRecordingPartImportFailed(ctx context.Context, arg MarkRecordingPartImportFailedParams) error
	MarkRecordingPartImportMuxCreated(ctx context.Context, arg MarkRecordingPartImportMuxCreatedParams) (CoachingRecordingImport, error)
	MarkRecordingPartImportReady(ctx context.Context, arg MarkRecordingPartImportReadyParams) (CoachingRecordingImport, error)
	MarkRecordingPartStarted(ctx context.Context, arg MarkRecordingPartStartedParams) (CoachingBookingRecording, error)
	MarkRecordingPartStopped(ctx context.Context, id pgtype.UUID) (CoachingBookingRecording, error)
	MarkRecordingPartStopping(ctx context.Context, id pgtype.UUID) (CoachingBookingRecording, error)
	MarkReminderSent(ctx context.Context, id pgtype.UUID) error
	RefreshBookingPresence(ctx context.Context, arg RefreshBookingPresenceParams) (CoachingBookingPresence, error)
	ReleaseInboundEmailClaim(ctx context.Context, id pgtype.UUID) error
	ReleaseSignupCode(ctx context.Context, id pgtype.UUID) error
	RemoveBookingPresence(ctx context.Context, arg RemoveBookingPresenceParams) (int64, error)
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	// Past, non-cancelled sessions the expert ran. Title is the session type name.
	ReportSessionEventsForExpert(ctx context.Context, expertID string) ([]ReportSessionEventsForExpertRow, error)
	// Past, non-cancelled sessions the student attended. Title is the session type name.
	ReportSessionEventsForStudent(ctx context.Context, studentID string) ([]ReportSessionEventsForStudentRow, error)
	// Reports list a user's own video uploads and live coaching sessions as
	// individual events. The frontend ports buildReport(): it nests events by
	// group then leaf (student for experts, expert for students), aggregates totals,
	// and filters by the selected month/quarter/year period — so these queries
	// return the full history with no period/timezone bucketing.
	// Visibility is enforced by always scoping on the requesting user's own id.
	// One row per asset uploaded into a group the expert owns. The reviewing expert
	// is the group owner; the student is the asset owner. Duration sums the asset's
	// video parts.
	ReportUploadEventsForExpert(ctx context.Context, expertID string) ([]ReportUploadEventsForExpertRow, error)
	// One row per asset the student uploaded. The reviewing expert is the group owner.
	ReportUploadEventsForStudent(ctx context.Context, studentID string) ([]ReportUploadEventsForStudentRow, error)
	RevokeGroupInvitation(ctx context.Context, arg RevokeGroupInvitationParams) (GroupInvitation, error)
	SeedUserPreferences(ctx context.Context, arg SeedUserPreferencesParams) (UserPreference, error)
	SeedUserPreferencesWithAvatar(ctx context.Context, arg SeedUserPreferencesWithAvatarParams) (UserPreference, error)
	SetVideoDurationByID(ctx context.Context, arg SetVideoDurationByIDParams) error
	SetVideoDurationByUploadID(ctx context.Context, arg SetVideoDurationByUploadIDParams) error
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error
	UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (CoachingAvailability, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupInvitationStatus(ctx context.Context, arg UpdateGroupInvitationStatusParams) error
	UpdateInboundEmailContent(ctx context.Context, arg UpdateInboundEmailContentParams) error
	UpdateModerationReportStatus(ctx context.Context, arg UpdateModerationReportStatusParams) (ModerationReport, error)
	UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (CoachingSessionType, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UserPreference, error)
	UpdateUserEmailPreferences(ctx context.Context, arg UpdateUserEmailPreferencesParams) (UserPreference, error)
	UpdateUserProfilePreferences(ctx context.Context, arg UpdateUserProfilePreferencesParams) (UserPreference, error)
	UpdateVideoMuxAssetID(ctx context.Context, arg UpdateVideoMuxAssetIDParams) error
	UpdateVideoReview(ctx context.Context, arg UpdateVideoReviewParams) (VideoReview, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
	UpdateVideoStatusByUploadID(ctx context.Context, arg UpdateVideoStatusByUploadIDParams) error
	UpsertBookingPresence(ctx context.Context, arg UpsertBookingPresenceParams) (CoachingBookingPresence, error)
	UpsertInboundEmail(ctx context.Context, arg UpsertInboundEmailParams) (InboundEmail, error)
}

var _ Querier = (*Queries)(nil)
