// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	CancelBooking(ctx context.Context, arg CancelBookingParams) (CoachingBooking, error)
	CheckUserGroup(ctx context.Context, arg CheckUserGroupParams) (bool, error)
	CountConflictingBookings(ctx context.Context, arg CountConflictingBookingsParams) (int64, error)
	CountVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	// === Availability ===
	CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (CoachingAvailability, error)
	// === Blocked Slots ===
	CreateBlockedSlot(ctx context.Context, arg CreateBlockedSlotParams) (CoachingBlockedSlot, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CoachingBooking, error)
	// === Booking Reminders ===
	CreateBookingReminder(ctx context.Context, arg CreateBookingReminderParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupInvitation(ctx context.Context, arg CreateGroupInvitationParams) (GroupInvitation, error)
	// === Session Types ===
	CreateSessionType(ctx context.Context, arg CreateSessionTypeParams) (CoachingSessionType, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoReview(ctx context.Context, arg CreateVideoReviewParams) (VideoReview, error)
	DeactivateSessionType(ctx context.Context, arg DeactivateSessionTypeParams) (int64, error)
	DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) (int64, error)
	DeleteBlockedSlot(ctx context.Context, arg DeleteBlockedSlotParams) (int64, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) error
	DeleteVideoReview(ctx context.Context, id pgtype.UUID) error
	GetAsset(ctx context.Context, id pgtype.UUID) (GetAssetRow, error)
	GetAssetOwnerByVideoID(ctx context.Context, id pgtype.UUID) (GetAssetOwnerByVideoIDRow, error)
	GetAssetStatusByVideoID(ctx context.Context, id pgtype.UUID) (AssetStatus, error)
	GetAssetVideos(ctx context.Context, assetID pgtype.UUID) ([]GetAssetVideosRow, error)
	GetBooking(ctx context.Context, arg GetBookingParams) (CoachingBooking, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupInvitationByCode(ctx context.Context, code string) (GroupInvitation, error)
	GetGroupInvitationByID(ctx context.Context, arg GetGroupInvitationByIDParams) (GroupInvitation, error)
	GetSessionType(ctx context.Context, arg GetSessionTypeParams) (CoachingSessionType, error)
	GetUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	// === Timezone ===
	GetUserTimezone(ctx context.Context, userID string) (string, error)
	HasVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (bool, error)
	ListActiveExpertsInGroup(ctx context.Context, groupID pgtype.UUID) ([]string, error)
	ListAssets(ctx context.Context) ([]ListAssetsRow, error)
	ListAvailabilityByExpertGroup(ctx context.Context, arg ListAvailabilityByExpertGroupParams) ([]CoachingAvailability, error)
	ListAvailabilityByExpertGroupDay(ctx context.Context, arg ListAvailabilityByExpertGroupDayParams) ([]CoachingAvailability, error)
	ListAvailabilityByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingAvailability, error)
	ListBlockedSlots(ctx context.Context, arg ListBlockedSlotsParams) ([]CoachingBlockedSlot, error)
	// === Bookings ===
	ListBookingsByExpertInRange(ctx context.Context, arg ListBookingsByExpertInRangeParams) ([]CoachingBooking, error)
	ListGroupBookings(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBookingsRow, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]string, error)
	ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error)
	ListPendingReminders(ctx context.Context) ([]ListPendingRemindersRow, error)
	ListSessionTypesByExpertGroup(ctx context.Context, arg ListSessionTypesByExpertGroupParams) ([]CoachingSessionType, error)
	ListSessionTypesByGroup(ctx context.Context, groupID pgtype.UUID) ([]CoachingSessionType, error)
	ListUserGroups(ctx context.Context, userID string) ([]ListUserGroupsRow, error)
	ListVideoReviews(ctx context.Context, videoID pgtype.UUID) ([]VideoReview, error)
	MarkReminderSent(ctx context.Context, id pgtype.UUID) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error
	UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (CoachingAvailability, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupInvitationStatus(ctx context.Context, arg UpdateGroupInvitationStatusParams) error
	UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (CoachingSessionType, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UserPreference, error)
	UpdateVideoMuxAssetID(ctx context.Context, arg UpdateVideoMuxAssetIDParams) error
	UpdateVideoReview(ctx context.Context, arg UpdateVideoReviewParams) (VideoReview, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
	UpdateVideoStatusByUploadID(ctx context.Context, arg UpdateVideoStatusByUploadIDParams) error
	UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) (UserPreference, error)
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
	UpsertUserTimezone(ctx context.Context, arg UpsertUserTimezoneParams) error
}

var _ Querier = (*Queries)(nil)
