// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reportSessionEventsForExpert = `-- name: ReportSessionEventsForExpert :many
SELECT
    cb.id AS booking_id,
    COALESCE(cst.name, '') AS title,
    cb.scheduled_at AS at,
    cb.group_id,
    g.name AS group_name,
    cb.student_id,
    cb.expert_id,
    cb.duration_minutes
FROM coaching_bookings cb
JOIN groups g ON g.id = cb.group_id
LEFT JOIN coaching_session_types cst ON cst.id = cb.session_type_id
WHERE cb.expert_id = $1
  AND cb.is_cancelled = false
  AND cb.scheduled_at < NOW()
ORDER BY cb.scheduled_at DESC
`

type ReportSessionEventsForExpertRow struct {
	BookingID       pgtype.UUID        `json:"booking_id"`
	Title           string             `json:"title"`
	At              pgtype.Timestamptz `json:"at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	GroupName       string             `json:"group_name"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	DurationMinutes int32              `json:"duration_minutes"`
}

// Past, non-cancelled sessions the expert ran. Title is the session type name.
func (q *Queries) ReportSessionEventsForExpert(ctx context.Context, expertID string) ([]ReportSessionEventsForExpertRow, error) {
	rows, err := q.db.Query(ctx, reportSessionEventsForExpert, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportSessionEventsForExpertRow
	for rows.Next() {
		var i ReportSessionEventsForExpertRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Title,
			&i.At,
			&i.GroupID,
			&i.GroupName,
			&i.StudentID,
			&i.ExpertID,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSessionEventsForStudent = `-- name: ReportSessionEventsForStudent :many
SELECT
    cb.id AS booking_id,
    COALESCE(cst.name, '') AS title,
    cb.scheduled_at AS at,
    cb.group_id,
    g.name AS group_name,
    cb.student_id,
    cb.expert_id,
    cb.duration_minutes
FROM coaching_bookings cb
JOIN groups g ON g.id = cb.group_id
LEFT JOIN coaching_session_types cst ON cst.id = cb.session_type_id
WHERE cb.student_id = $1
  AND cb.is_cancelled = false
  AND cb.scheduled_at < NOW()
ORDER BY cb.scheduled_at DESC
`

type ReportSessionEventsForStudentRow struct {
	BookingID       pgtype.UUID        `json:"booking_id"`
	Title           string             `json:"title"`
	At              pgtype.Timestamptz `json:"at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	GroupName       string             `json:"group_name"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	DurationMinutes int32              `json:"duration_minutes"`
}

// Past, non-cancelled sessions the student attended. Title is the session type name.
func (q *Queries) ReportSessionEventsForStudent(ctx context.Context, studentID string) ([]ReportSessionEventsForStudentRow, error) {
	rows, err := q.db.Query(ctx, reportSessionEventsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportSessionEventsForStudentRow
	for rows.Next() {
		var i ReportSessionEventsForStudentRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Title,
			&i.At,
			&i.GroupID,
			&i.GroupName,
			&i.StudentID,
			&i.ExpertID,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportUploadEventsForExpert = `-- name: ReportUploadEventsForExpert :many

SELECT
    a.id AS asset_id,
    a.name AS title,
    a.created_at AS at,
    a.group_id,
    g.name AS group_name,
    a.owner_id AS student_id,
    g.owner_id AS expert_id,
    COALESCE(SUM(v.duration_seconds), 0)::double precision AS duration_seconds
FROM assets a
JOIN groups g ON g.id = a.group_id
LEFT JOIN videos v ON v.asset_id = a.id
WHERE g.owner_id = $1
  AND a.status != 'waiting_upload'
GROUP BY a.id, a.name, a.created_at, a.group_id, g.name, a.owner_id, g.owner_id
ORDER BY a.created_at DESC
`

type ReportUploadEventsForExpertRow struct {
	AssetID         pgtype.UUID        `json:"asset_id"`
	Title           string             `json:"title"`
	At              pgtype.Timestamptz `json:"at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	GroupName       string             `json:"group_name"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	DurationSeconds float64            `json:"duration_seconds"`
}

// Reports list a user's own video uploads and live coaching sessions as
// individual events. The frontend ports buildReport(): it nests events by
// group then leaf (student for experts, expert for students), aggregates totals,
// and filters by the selected month/quarter/year period — so these queries
// return the full history with no period/timezone bucketing.
// Visibility is enforced by always scoping on the requesting user's own id.
// One row per asset uploaded into a group the expert owns. The reviewing expert
// is the group owner; the student is the asset owner. Duration sums the asset's
// video parts.
func (q *Queries) ReportUploadEventsForExpert(ctx context.Context, expertID string) ([]ReportUploadEventsForExpertRow, error) {
	rows, err := q.db.Query(ctx, reportUploadEventsForExpert, expertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportUploadEventsForExpertRow
	for rows.Next() {
		var i ReportUploadEventsForExpertRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Title,
			&i.At,
			&i.GroupID,
			&i.GroupName,
			&i.StudentID,
			&i.ExpertID,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportUploadEventsForStudent = `-- name: ReportUploadEventsForStudent :many
SELECT
    a.id AS asset_id,
    a.name AS title,
    a.created_at AS at,
    a.group_id,
    g.name AS group_name,
    a.owner_id AS student_id,
    g.owner_id AS expert_id,
    COALESCE(SUM(v.duration_seconds), 0)::double precision AS duration_seconds
FROM assets a
JOIN groups g ON g.id = a.group_id
LEFT JOIN videos v ON v.asset_id = a.id
WHERE a.owner_id = $1
  AND a.status != 'waiting_upload'
GROUP BY a.id, a.name, a.created_at, a.group_id, g.name, a.owner_id, g.owner_id
ORDER BY a.created_at DESC
`

type ReportUploadEventsForStudentRow struct {
	AssetID         pgtype.UUID        `json:"asset_id"`
	Title           string             `json:"title"`
	At              pgtype.Timestamptz `json:"at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	GroupName       string             `json:"group_name"`
	StudentID       string             `json:"student_id"`
	ExpertID        string             `json:"expert_id"`
	DurationSeconds float64            `json:"duration_seconds"`
}

// One row per asset the student uploaded. The reviewing expert is the group owner.
func (q *Queries) ReportUploadEventsForStudent(ctx context.Context, studentID string) ([]ReportUploadEventsForStudentRow, error) {
	rows, err := q.db.Query(ctx, reportUploadEventsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportUploadEventsForStudentRow
	for rows.Next() {
		var i ReportUploadEventsForStudentRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Title,
			&i.At,
			&i.GroupID,
			&i.GroupName,
			&i.StudentID,
			&i.ExpertID,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
