// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, language, created_at, updated_at, avatar, timezone FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Timezone,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE user_preferences
SET avatar     = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, language, created_at, updated_at, avatar, timezone
`

type UpdateUserAvatarParams struct {
	UserID string `json:"user_id"`
	Avatar string `json:"avatar"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.UserID, arg.Avatar)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Timezone,
	)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :one
INSERT INTO user_preferences (user_id, language, avatar)
VALUES ($1, 'en', $2)
ON CONFLICT (user_id) DO UPDATE
SET avatar     = EXCLUDED.avatar,
    updated_at = NOW()
RETURNING user_id, language, created_at, updated_at, avatar, timezone
`

type UpsertUserAvatarParams struct {
	UserID string `json:"user_id"`
	Avatar string `json:"avatar"`
}

func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserAvatar, arg.UserID, arg.Avatar)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Timezone,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_id, language)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET language = EXCLUDED.language,
    updated_at = NOW()
RETURNING user_id, language, created_at, updated_at, avatar, timezone
`

type UpsertUserPreferencesParams struct {
	UserID   string       `json:"user_id"`
	Language LanguageCode `json:"language"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences, arg.UserID, arg.Language)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Timezone,
	)
	return i, err
}
