// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    first_name,
    last_name,
    email,
    language,
    avatar
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, first_name, last_name, email, language, created_at, updated_at, avatar
`

type CreateUserParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Language  string `json:"language"`
	Avatar    []byte `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Language,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email, language, created_at, updated_at, avatar FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE(NULLIF($1::text, ''), first_name),
    last_name = COALESCE(NULLIF($2::text, ''), last_name),
    language = COALESCE(NULLIF($3::text, ''), language),
    avatar = COALESCE($4::bytea, avatar),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, first_name, last_name, email, language, created_at, updated_at, avatar
`

type UpdateUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Language  string `json:"language"`
	Avatar    []byte `json:"avatar"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Language,
		arg.Avatar,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
	)
	return i, err
}
