// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideoReview = `-- name: CreateVideoReview :one
INSERT INTO video_reviews (
    video_id,
    content
) VALUES (
    $1, $2
) RETURNING id, video_id, content, created_at, updated_at
`

type CreateVideoReviewParams struct {
	VideoID pgtype.UUID `json:"video_id"`
	Content string      `json:"content"`
}

func (q *Queries) CreateVideoReview(ctx context.Context, arg CreateVideoReviewParams) (VideoReview, error) {
	row := q.db.QueryRow(ctx, createVideoReview, arg.VideoID, arg.Content)
	var i VideoReview
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideoReview = `-- name: DeleteVideoReview :exec
DELETE FROM video_reviews
WHERE id = $1
`

func (q *Queries) DeleteVideoReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoReview, id)
	return err
}

const listVideoReviews = `-- name: ListVideoReviews :many
SELECT 
    id,
    video_id,
    content,
    created_at,
    updated_at
FROM video_reviews
WHERE video_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVideoReviews(ctx context.Context, videoID pgtype.UUID) ([]VideoReview, error) {
	rows, err := q.db.Query(ctx, listVideoReviews, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoReview
	for rows.Next() {
		var i VideoReview
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoReview = `-- name: UpdateVideoReview :one
UPDATE video_reviews
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, video_id, content, created_at, updated_at
`

type UpdateVideoReviewParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateVideoReview(ctx context.Context, arg UpdateVideoReviewParams) (VideoReview, error) {
	row := q.db.QueryRow(ctx, updateVideoReview, arg.ID, arg.Content)
	var i VideoReview
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
