// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVideosWithoutReviews = `-- name: CountVideosWithoutReviews :one
SELECT COUNT(*) as count
FROM videos v
LEFT JOIN video_reviews r ON v.id = r.video_id
WHERE v.asset_id = $1
GROUP BY v.asset_id
HAVING COUNT(r.id) = 0
   OR COUNT(DISTINCT v.id) > COUNT(DISTINCT r.video_id)
`

func (q *Queries) CountVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosWithoutReviews, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideoReview = `-- name: CreateVideoReview :one
INSERT INTO video_reviews (
    video_id,
    content
) VALUES (
    $1, $2
) RETURNING id, video_id, content, created_at, updated_at
`

type CreateVideoReviewParams struct {
	VideoID pgtype.UUID `json:"video_id"`
	Content string      `json:"content"`
}

func (q *Queries) CreateVideoReview(ctx context.Context, arg CreateVideoReviewParams) (VideoReview, error) {
	row := q.db.QueryRow(ctx, createVideoReview, arg.VideoID, arg.Content)
	var i VideoReview
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideoReview = `-- name: DeleteVideoReview :exec
DELETE FROM video_reviews
WHERE id = $1
`

func (q *Queries) DeleteVideoReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoReview, id)
	return err
}

const getAssetStatusByVideoID = `-- name: GetAssetStatusByVideoID :one
SELECT a.status
FROM assets a
INNER JOIN videos v ON v.asset_id = a.id
WHERE v.id = $1
`

func (q *Queries) GetAssetStatusByVideoID(ctx context.Context, id pgtype.UUID) (AssetStatus, error) {
	row := q.db.QueryRow(ctx, getAssetStatusByVideoID, id)
	var status AssetStatus
	err := row.Scan(&status)
	return status, err
}

const hasVideosWithoutReviews = `-- name: HasVideosWithoutReviews :one
SELECT EXISTS (
    SELECT 1
    FROM videos v
    LEFT JOIN video_reviews r ON v.id = r.video_id
    WHERE v.asset_id = $1
    GROUP BY v.id
    HAVING COUNT(r.id) = 0
) as has_unreviewed
`

func (q *Queries) HasVideosWithoutReviews(ctx context.Context, assetID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasVideosWithoutReviews, assetID)
	var has_unreviewed bool
	err := row.Scan(&has_unreviewed)
	return has_unreviewed, err
}

const listVideoReviews = `-- name: ListVideoReviews :many
SELECT 
    id,
    video_id,
    content,
    created_at,
    updated_at
FROM video_reviews
WHERE video_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVideoReviews(ctx context.Context, videoID pgtype.UUID) ([]VideoReview, error) {
	rows, err := q.db.Query(ctx, listVideoReviews, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoReview
	for rows.Next() {
		var i VideoReview
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoReview = `-- name: UpdateVideoReview :one
UPDATE video_reviews
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, video_id, content, created_at, updated_at
`

type UpdateVideoReviewParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateVideoReview(ctx context.Context, arg UpdateVideoReviewParams) (VideoReview, error) {
	row := q.db.QueryRow(ctx, updateVideoReview, arg.ID, arg.Content)
	var i VideoReview
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
